<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/de/explain.php 
 * 
 * Contao extension: helpdesk 1.2.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Peter Koch (acenes), http://ibk-software.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['0']['0'] = "Privater Support";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['0']['1'] = "Ticket-Support für Einzelpersonen: Die Tickets können nur vom Ersteller selbst im Frontend eingesehen werden. Verwenden Sie diese Kategorie zum Beispiel für individuellen Support. In einem solchen Fall besteht keine Notwendigkeit, für jeden Kunden eine Kategorie zu erstellen.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['1']['0'] = "Gemeinsamer Support";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['1']['1'] = "Ticket-Support für Gruppen: In dieser Kategorie können die Kunden alle anderen Tickets einsehen und beantworten. Ein Anwendungsfalls für diese Kategorie wäre der Support für ein Unternehmen, in dem mehrere Mitarbeiter alle Ticket-Aktivitäten überblicken müssen. In einem solchen Fall sollten Sie für jedes Unternehmen eine eigene gemeinsame Kategorie erstellen.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['2']['0'] = "Öffentlicher Support";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['2']['1'] = "Öffentlicher Ticket-Support: Alle Tickets in dieser Kategorie können von jedem Frontend-Benutzer eingesehen werden, egal ob der Benutzer angemeldet ist oder nicht. Allerdings dürfen nur angemeldete Benutzer Tickets öffnen und beantworten.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['3']['0'] = "Eingeschränktes Forum";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['3']['1'] = "Ein allgemeines Forum, das nur für angemeldete Mitglieder sichtbar und vor öffentlichem Zugriff verborgen ist.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['4']['0'] = "Öffentliches Forum";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['4']['1'] = "Ein allgemeines Forum, das von jedem Benutzer eingesehen werden kann, egal ob der Benutzer angemeldet ist oder nicht. Allerdings dürfen nur registrierte Benutzer Nachrichten verfassen und beantworten.";
 
?>
