<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/de/helpdesk.php 
 * 
 * TYPOlight extension: helpdesk 1.2.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Peter Koch (acenes), http://ibk-software.com 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['helpdesk']['useserverdef'] = "Standardeinstellung des Servers verwenden";
$GLOBALS['TL_LANG']['helpdesk']['today'] = "Heute";
$GLOBALS['TL_LANG']['helpdesk']['yesterday'] = "Gestern";
$GLOBALS['TL_LANG']['helpdesk']['ungrouped'] = "Nicht gruppierte";
 
?>
