<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/de/modules.php 
 * 
 * Contao extension: helpdesk 1.2.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Peter Koch (acenes), http://ibk-software.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['helpdesk_comments']['0'] = "Forum/Helpdesk Kommentare";
$GLOBALS['TL_LANG']['CTE']['helpdesk_comments']['1'] = "Dieses Inhaltselement erlaubt die Kommentierung von Artikeln in einem Forenthema.";
$GLOBALS['TL_LANG']['MOD']['helpdesk'] = "Forum/Helpdesk";
$GLOBALS['TL_LANG']['MOD']['helpdesk_discuss']['0'] = "Diskussion";
$GLOBALS['TL_LANG']['MOD']['helpdesk_discuss']['1'] = "An den Diskussionen in Foren und Helpdesks teilnehmen.";
$GLOBALS['TL_LANG']['MOD']['helpdesk_structure']['0'] = "Struktur";
$GLOBALS['TL_LANG']['MOD']['helpdesk_structure']['1'] = "Verwaltung von Kategorien der Forum/Helpdesk-Anwendung";
$GLOBALS['TL_LANG']['MOD']['helpdesk_settings']['0'] = "Einstellungen";
$GLOBALS['TL_LANG']['MOD']['helpdesk_settings']['1'] = "Kontrollieren und anpassen der übergeordneten Einstellungen";
$GLOBALS['TL_LANG']['FMD']['helpdesktitle']['0'] = "Forum/Helpdesk Titel";
$GLOBALS['TL_LANG']['FMD']['helpdesktitle']['1'] = "Zeigt einen Titel für Forum/Helpdesk Seiten an mit globalen Funktionen.";
$GLOBALS['TL_LANG']['FMD']['helpdesk']['0'] = "Forum/Helpdesk Block";
$GLOBALS['TL_LANG']['FMD']['helpdesk']['1'] = "Dieses Modul repräsentiert eine oder mehrere Forum/Helpdesk-Kategorien im Frontend.";
 
?>
