<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/de/tl_content.php 
 * 
 * Contao extension: helpdesk 1.2.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Peter Koch (acenes), http://ibk-software.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['helpdesk_category']['0'] = "Kategorie";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_category']['1'] = "Bitte die Kategorie wählen in welcher das Kommentierungsthema angelegt werden soll.";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_reference']['0'] = "Zu kommentierendes Objekt";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_reference']['1'] = "Bitte das Objekt wählen auf welches sich die Kommentierung beziehen soll.";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_legend'] = "Forum/Helpdesk Kommentar Einstellungen";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_item']['page'] = "Diese Seite";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_item']['article'] = "Dieser Artikel";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_item']['news'] = "Nachricht im Leser-Modul auf dieser Seite";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_item']['faq'] = "FAQ im Leser-Modul auf dieser Seite";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_item']['event'] = "Event im Leser-Modul auf dieser Seite";
 
?>
