<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/de/tl_helpdesk_categories.php 
 * 
 * Contao extension: helpdesk 1.2.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Peter Koch (acenes), http://ibk-software.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['header']['0'] = "Kopftext";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['header']['1'] = "Kopftext zum Beginn einer neuen Kategorien-Gruppe. Sonst leer lassen.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['title']['1'] = "Titel dieser Kategorie.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['description']['0'] = "Beschreibung";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['description']['1'] = "Eine optionale Beschreibung dieser Kategorie.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['buttons']['0'] = "Editor Knöpfe";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['buttons']['1'] = "Eingabe einer Liste von Editor Knöpfen. Einzelne Knöpfe mit Komma abtrennen, Gruppen mit Semikolon. Neue Zeile durch Zeilenvorschub.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access']['0'] = "Zugriff";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access']['1'] = "Zugriffsmodus der Kategorie für das Frontend.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['replyonly']['0'] = "Nur antworten";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['replyonly']['1'] = "Neue Themen oder Tickets können nur durch Moderatoren oder Supporter angelegt werden.<br/> Beechtigte Mitglieder/Kunden können nur auf bestehende Themen antworten.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['published']['0'] = "Veröffentlicht";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['published']['1'] = "Die Kategorie wird den erlaubten Teilnehmern im Frontend angezeigt.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_clients']['0'] = "Frontend-Benutzer";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_clients']['1'] = "Frontend-Benutzer, die als Mitglieder dieser Kategorie eingetragen sind.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_supporters']['0'] = "Frontend Moderatoren/Supporter";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_supporters']['1'] = "Frontend-Mitglieder, die als Moderatoren/Supporter dieser Kategorie eingetragen sind.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_clients']['0'] = "Backend Benutzer";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_clients']['1'] = "Backend-Benutzer, die als Mitglieder dieser Kategorie eingetragen sind.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_supporters']['0'] = "Backend Moderatoren/Supporter";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_supporters']['1'] = "Backend-Mitglieder, die als Moderatoren/Supporter dieser Kategorie eingetragen sind.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['feed']['0'] = "RSS-Feeds aktivieren";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['feed']['1'] = "Auswählen, um RSS-Feeds für diese Kategorie aktivieren.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch']['0'] = "Anhänge aktivieren";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch']['1'] = "Anhänge in Nachrichten aktivieren.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_dir']['0'] = "Verzeichnis für Anhänge";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_dir']['1'] = "Geben Sie den Pfad an, in dem die Anhänge gespeichert werden sollen.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_size']['0'] = "Größe von Anhängen";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_size']['1'] = "Geben Sie die maximale Größe aller Anhänge in einer Nachricht an.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_types']['0'] = "Dateitypen für Anhänge";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_types']['1'] = "Geben Sie eine per Komma getrennte Liste aller erlaubten Dateierweiterungen an welche für Anhhänge erlaubt sind.<br />Geben Sie * ein, um alle Dateierweiterungen zu erlauben.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify']['0'] = "Benachrichtigung aktivieren";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify']['1'] = "Benachrichtigung der Abonnenten per Email.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_astext']['0'] = "Als Text senden";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_astext']['1'] = "Auswählen, um als reinen Text zu versenden. Auswahl entfernen, um als HTML zu versenden.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_name']['0'] = "Absender-Name";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_name']['1'] = "Leer lassen, um nur die Email-Adresse zu verwenden.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_sender']['0'] = "Absender-Mail";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_sender']['1'] = "Leer lassen, um die Administrator-Email-Adresse zu verwenden.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_fe_url']['0'] = "Frontend-URL für Benachrichtigungen und Feeds";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_fe_url']['1'] = "Die URL sollte den folgenden Aufbau haben <em>http://www.beispiel.com/forum</em><br /> Verwendet für Benachrichtigungen, RSS Feeds und Artikel-Kommentierung.<br/> Lassen Sie das Feld leer um diese Funktionen zu deaktivieren.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_be_url']['0'] = "Backend-URL Basis";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_be_url']['1'] = "Die URL sollte den folgenden Aufbau haben <em>http://www.ihrewebsite.com/Contao/main.php?do=helpdesk</em><br />Lassen Sie das Feld leer, um Benachrichtigungen für Backend-Benutzer zu deaktivieren.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newsubj']['0'] = "Titel für neue Beiträge";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newsubj']['1'] = "Sie können die Begrenzer [[poster]], [[subject]] und [[replytag]] verwenden.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newtext']['0'] = "Nachrichtentext für neue Beiträge";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newtext']['1'] = "Sie können die Begrenzer [[poster]], [[subject]], [[message]] und [[link]] verwenden.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_replysubj']['0'] = "Titel für Antworten";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_replysubj']['1'] = "Sie können die Begrenzer [[poster]], [[subject]] und [[replytag]] verwenden.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_replytext']['0'] = "Nachrichtentext für Antworten";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_replytext']['1'] = "Sie können die Begrenzer [[poster]], [[subject]], [[message]] und [[link]] verwenden.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import']['0'] = "Email-Import aktivieren";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import']['1'] = "Import von Supportanfragen per Email aktivieren.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_server']['0'] = "Mail-Server";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_server']['1'] = "Name des IMAP4/POP3 Servers.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_port']['0'] = "Port";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_port']['1'] = "Portnummer angeben oder leer lassen für den Standard-Port.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_type']['0'] = "Postfach-Typ";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_type']['1'] = "Wählen Sie den Postfach-Typ aus.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tls']['0'] = "Transport Layer Security (TLS)";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tls']['1'] = "Wählen Sie den TLS/SSL Modus.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_username']['0'] = "Benutzername";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_username']['1'] = "Geben Sie den Benutzernamen des Mailzugangs ein.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_password']['0'] = "Kennwort";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_password']['1'] = "Geben Sie das Kennwort für den Mailzugang ein.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_email']['0'] = "An: Email";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_email']['1'] = "Geben Sie die <em>An</em> Email-Adresse ein oder lassen Sie das Feld leer, um die gesamte Mail abzuarbeiten.<br />(Diese sollte der Absenderadresse der Benachrichtigungen entsprechen.)";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['0'] = "Privater Support";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['1'] = "Gemeinsamer Support";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['2'] = "Öffentlicher Support";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['3'] = "Eingeschränktes Forum";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['4'] = "Öffentliches Forum";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_types']['0'] = "POP3";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_types']['1'] = "IMAP4";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['0'] = "Kein TLS verwenden, selbst wenn der Server es unterstützt.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['1'] = "TLS verwenden, wenn der Server es unterstützt. Zertifikat validieren.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['2'] = "TLS verwenden, wenn der Server es unterstützt. Zertifikat nicht validieren.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['3'] = "TLS erzwingen, Zertifikat validieren.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['4'] = "TLS erzwingen, Zertifikat nicht validieren.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['5'] = "SSL verwenden, Zertifikat validieren.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['6'] = "SSL verwenden, Zertifikat nicht validieren.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['new']['0'] = "Neue Kategorie";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['new']['1'] = "Eine neue Kategorie erzeugen.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['edit']['0'] = "Bearbeiten";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['edit']['1'] = "Einstellungen der Kategorie %s bearbeiten";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['copy']['0'] = "Klonen";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['copy']['1'] = "Diese Kategorie klonen (duplizieren)";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['delete']['0'] = "Löschen";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['delete']['1'] = "Kategorie %s mit allen Tickets löschen";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_notify']['0'] = "Benachrichtigung aktivieren";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_notify']['1'] = "Benachrichtigung für die Kategorie %s aktivieren";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_notify']['0'] = "Benachrichtigung deaktivieren";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_notify']['1'] = "Benachrichtigung für die Kategorie %s deaktivieren";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_import']['0'] = "Mail-Import aktivieren";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_import']['1'] = "Import von Emails für die Kategorie %s aktivieren";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_import']['0'] = "Mail-Import deaktivieren";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_import']['1'] = "Import von Emails für die Kategorie %s deaktivieren";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['publish']['0'] = "Veröffentlichen";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['publish']['1'] = "Kategorie %s für Teilnehmer veröffentlichen";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['unpublish']['0'] = "Veröffentlichung zurücknehmen";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['unpublish']['1'] = "Veröffentlichung der Kategorie %s für die Teilnehmer zurücknehmen";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderup']['0'] = "Nach oben";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderup']['1'] = "Kategorie nach oben verschieben";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderdown']['0'] = "Nach unten";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderdown']['1'] = "Kategorie nach unten verschieben";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['tickets'] = "Tickets";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['replies'] = "Antworten";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_subject']['new'] = "Neues Ticket: [[subject]] [[replytag]]";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_subject']['reply'] = "Antwort an: [[subject]] [[replytag]]";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_text']['new'] = "[[poster]] hat ein neues Ticket in einer Kategorie erzeugt, die Sie abonniert haben:<br /> <hr /> [[message]] <hr /> Das Ticket liegt in:<br /> [[link]]<br /> ---<br /> Contao Helpdesk Mailer<br /> (Bitte behalten Sie den Titel in der Antwortzeile bei, wenn per Email antworten)<br />";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_text']['reply'] = "[[poster]] hat auf ein Ticket geantwortet, das Sie abonniert haben:<br /> <hr /> [[message]] <hr /> Die Nachricht befindet sich in:<br /> [[link]]<br /> ---<br /> Contao Helpdesk Mailer<br /> (Bitte behalten Sie den Titel in der Antwortzeile bei, wenn per Email antworten)<br />";
$GLOBALS['TL_LANG']['tl_helpdesk_fcategories']['tickets'] = "Themen";
 
?>
