<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/de/tl_helpdesk_frontend.php 
 * 
 * Contao extension: helpdesk 1.2.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Peter Koch (acenes), http://ibk-software.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_support']['advanced'] = "Erweiterte Einstellungen";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['mine'] = "Meine";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['recent'] = "Aktuell";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['views'] = "Aufrufe";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unanswered'] = "Unbeantwortet";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unread'] = "Ungelesen";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['category'] = "Kategorie";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['index'] = "Index";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['ticket'] = "Ticket";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['tickets'] = "Tickets";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['newticket'] = "Neues Ticket";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['createticket'] = "Ticket erzeugen";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nopaste'] = "Einfügen abbrechen";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['cutmessage'] = "Nachr. ausschn.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['cutticket'] = "Ticket ausschn.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['paste'] = "Einfügen";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['postreply'] = "Antwort erstellen";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['updatemessage'] = "Nachricht aktualisieren";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message'] = "Nachricht";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['replies'] = "Antworten";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['latestpost'] = "Letzter Beitrag";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['postedby'] = "von %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['lastedit'] = "[Zuletzt bearbeitet %s, %s]";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['subject'] = "Titel";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['client'] = "Kunde";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['supporter'] = "Supporter";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['owner'] = "Besitzer";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['creator'] = "Ersteller";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['poster'] = "Absender";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nocategories'] = "Keine Kategorien gefunden.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['notickets'] = "Keine Tickets gefunden.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nomessages'] = "Keine Beiträge gefunden.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status'] = "Status";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status-0'] = "Unbeantwortet";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status-1'] = "Beantwortet";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status-2'] = "Geschlossen";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['reply'] = "Antwort";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['close'] = "Schließen";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['open'] = "Öffnen";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['edit'] = "Bearbeiten";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['quote'] = "Zitieren";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['delete'] = "Löschen";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['publish'] = "Veröffentlichen";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unpublish'] = "Unveröffentlichen";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['pinup'] = "Anheften";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unpin'] = "Losheften";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['markcatread'] = "Kategorie gelesen";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['markallread'] = "Alle gelesen";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['feed'] = "RSS Feed";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['globfeed'] = "Globaler RSS Feed";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['wrote'] = "%s schrieb:";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['deleteMessageConfirm'] = "Wollen Sie wirklich diesen Beitrag löschen?";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['deleteTicketConfirm'] = "Wollen Sie wirklich dieses Ticket mit allen Beiträgen löschen?";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['client_hint'] = "Wählen Sie den Kunden aus, in dessen Auftrag Sie dieses Ticket erzeugen oder lassen Sie das Feld leer.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['subject_missing'] = "Sie müssen einen Titel angeben!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['subject_hint'] = "Geben Sie eine kurze Beschreibung des Grundes an, aus dem Sie dieses Ticket erstellen.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_missing']['create'] = "Sie müssen eine ausführliche Beschreibung angeben!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_missing']['reply'] = "Sie müssen einen Text angeben!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_missing']['edit'] = "Sie müssen einen Text angeben!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_hint']['create'] = "Geben Sie eine ausführliche Beschreibung des Problems mit allen bekannten Fakten an.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_hint']['reply'] = "Geben Sie bitte Ihren Antworttext an.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_hint']['edit'] = "Bearbeiten Sie bitte den Antworttext.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['published'] = "Veröffentlicht";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['published_hint'] = "Die Nachricht wird im Frontend für autorisierte Personen angezeigt.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messages_reverse'] = "Vorherige Beiträge in umgekehrter Reihenfolge:";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['firstpage'] = "« Erste";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['prevpage'] = "Zurück";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nextpage'] = "Nächste";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['lastpage'] = "Letzte »";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['page_n_of_m'] = "Seite %s von %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['gotopage'] = "Gehe zu Seite %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['attachments'] = "Anhänge";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['atch_size'] = "Maximalgröße aller Anhänge:";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['atch_types'] = "Erlaubte Dateitypen:";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['atchtobig'] = "Die Anhänge überschreiten die erlaubte Maximalgröße.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['filetobig'] = "%s überschreitet die maximale Dateigröße für den Upload auf diesen Server (bitte überprüfen Sie die php.ini Einstellungen).";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['filepartial'] = "%s wurde nur teilweise hochgeladen.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['filebadtype'] = "%s ist kein erlaubter Dateityp.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['matchinfo'] = "Beste %s von total %s Treffern";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['search'] = "Suche";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchresult'] = "Ergebnisse";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchinfo'] = "[#%s von %s, Relevanz %s]";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchterms'] = "Suchbegriffe";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchterms_missing'] = "Sie müssen mindestens einen Suchbegriff eingeben!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchterms_hint'] = "Geben Sie einen oder mehrere Suchbegriffe ein.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['findmode'] = "Auflistung";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['findmode_hint'] = "Auswahl was aufgelistet werden soll";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmode'] = "Suchmodus";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmode_hint'] = "Auswahl des Suchmodus.<br/> Die Volltextsuche ist in der <a href=\"http://dev.mysql.com/doc/refman/5.5/en/fulltext-search.html\">MySQL Dokumentation</a> beschrieben.<br/> Bei der 'ähnlichen' (like) Suche können die SQL Jokerzeichen % und _ verwendet werden.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchparts'] = "Durchsuchte Teile";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchparts_unchecked'] = "Sie müssen einen oder mehrere Teile für die Suche auswählen!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchparts_hint'] = "Wählen Sie einen oder mehrere teile für die Suche aus.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchcats'] = "Durchsuchte Kategorien";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchcats_unchecked'] = "Sie müssen mindestens eine Kategorie auswählen!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchcats_hint'] = "Wählen Sie eine oder mehrere Kategorien für die Suche aus.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nomatches'] = "Es wurden keine Ergebnisse gefunden.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['postcount'] = "Beiträge: %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['fromloc'] = "Von: %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['viewprofile'] = "Profil ansehen";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['warnsearchflood'] = "Bitte vor absenden einer neuen Suchanfrage %s Sekunden warten.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['warnpostflood'] = "Bitte vor absenden eines neuen Beitrags %s Sekunden warten.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['continue'] = "Weiter";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messagetitle']['info'] = "Intormation";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messagetitle']['warning'] = "Warnung";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messagetitle']['error'] = "Fehler";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmodes']['natural'] = "Volltext natürlich";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmodes']['boolean'] = "Volltext boolesch";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmodes']['like'] = "Ähnlich";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmodes']['binary'] = "Ähnlich binär";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['findmodes']['messages'] = "Alle relevanten Meldungen";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['findmodes']['topics'] = "Erster Treffer in relevanten Themen";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['ticket'] = "Thema";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['tickets'] = "Themen";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['newticket'] = "Neues Thema";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['createticket'] = "Thema erzeugen";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['cutticket'] = "Thema ausschn.";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['client'] = "Mitglied";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['supporter'] = "Moderator";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['owner'] = "Ersteller";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['notickets'] = "Keine Themen gefunden.";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['status-0'] = "Angeheftet";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['status-1'] = "Normal";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['deleteTicketConfirm'] = "Wollen Sie wirklich dieses Thema mit allen Beiträgen löschen?";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['client_hint'] = "Wählen Sie das Mitglied aus, in dessen Namen Sie diesen Beitrag erzeugen oder lassen Sie das Feld leer.";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['subject_hint'] = "Geben Sie eine kurze Beschreibung des Titels dieses Themas an.";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['message_hint']['create'] = "Geben Sie eine ausführliche Beschreibung an.";
 
?>
