<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/de/tl_helpdesk_settings.php 
 * 
 * Contao extension: helpdesk 1.2.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Peter Koch (acenes), http://ibk-software.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['title'] = "Forum/Helpdesk Allgemeine Einstellungen";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['version'] = "Version";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['yes'] = "Ja";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['no'] = "Nein";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['confsync'] = "Soll die Synchronisation aller Statistiken and Cache-Werte jetzt wirklich durchgeführt werden?";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['synchronize']['0'] = "Synchronisieren";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['synchronize']['1'] = "Alle Statistiken und Cache-Werte neu ermitteln und berechnen";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['edit']['0'] = "Bearbeiten";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['edit']['1'] = "Bearbeiten der Einstellungen";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['tpage']['0'] = "Themen/Tickets pro Seite";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['tpage']['1'] = "Eingabe der Anzahl von Themen/Tickets pro Seite. 0 oder leer deaktiviert den Seitenwechsel.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['mpage']['0'] = "Nachrichten pro Seite";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['mpage']['1'] = "Eingabe der Anzahl der Nachrichten pro Seite. 0 oder leer deaktiviert den Seitenwechsel.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['spage']['0'] = "Suchergebnisse pro Seite";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['spage']['1'] = "Eingabe der Anzahl gefundener Nachrichten pro Seite. 0 oder leer deaktiviert den Seitenwechsel.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavsize']['0'] = "Seitennavigation Anzahl";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavsize']['1'] = "Anzahl Seiten welche in der Seitennavigation aufgelistet werden. Bei 0 wird statt dessen \"Seite N von M\" angezeigt.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavctl']['0'] = "Seitennavigation Darstellung";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavctl']['1'] = "Auswahl der Darstellung der Seitennavigations-Funktionen.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['edits']['0'] = "Bearbeitungen markieren von";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['edits']['1'] = "Stufenauswahl der Registrierung von Bearbeitungen.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editswait']['0'] = "Bearbeitungen markieren nach (Sekunden)";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editswait']['1'] = "Wie lange ein neuer Betrag noch geändert werden kann ohne als bearbeitet markiert zu werden.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['postdelay']['0'] = "Wartezeit zwischen Beiträgen (Sekunden)";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['postdelay']['1'] = "Minimale Wartezeit zwischen dem Ansenden von zwei Beiträgen.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['searchdelay']['0'] = "Wartezeit zwischen Suchanfragen (Sekunden)";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['searchdelay']['1'] = "Minimale Wartezeit zwischen dem Absenden von zwei Suchanfragen.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['searchmax']['0'] = "Maximale Suchresultate";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['searchmax']['1'] = "Maximale Anzahl bester Treffer welche als Suchresultat geliefert werden.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['tlsearch']['0'] = "Contao Suche verwenden";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['tlsearch']['1'] = "Schaltet, zusätzlich zur integrierten Suche, auch noch die Indizierung von Themen durch die Contao Suchmaschine ein.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['recenthours']['0'] = "Zeitbereich für 'aktuell'";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['recenthours']['1'] = "Maximales Alter in Stunden damit ein Beitrag noch als aktuell gilt.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['images']['0'] = "Frontend Bildverzeichnis";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['images']['1'] = "Leer lassen, um die Default Icons und Bilder zu verwenden.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feeds']['0'] = "Aktiviere Forum/Helpdesk Feeds";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feeds']['1'] = "Auswählen, um RSS Feeds der Foren und Helpdesks zu aktivieren.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedmax']['0'] = "Anzahl der Nachrichten in einem Feed";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedmax']['1'] = "Geben Sie die maximale Anzahl der Nachrichten an, die in einem Feed aufgeführt werden sollen.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedlimit']['0'] = "Maximale Meldungslänge";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedlimit']['1'] = "Eingabe der maximalen Anzahl Zeichen pro Meldung";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedlink']['0'] = "Basisname des Feeds";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedlink']['1'] = "Geben Sie z.B. <em>helpdesk</em> für den Feed mit dem Namen http://www.example.com/helpdesk&lt;category-number&gt;.xml ein.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedtitle']['0'] = "Titel des Feeds";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedtitle']['1'] = "Der Titel wird zum Beispiel in Browser-Tabulatoren angezeigt und als Kurzname für den Feed verwendet.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feeddescription']['0'] = "Beschreibung des Feeds";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feeddescription']['1'] = "Die Beschreibung wird von den meisten Browsern und Feed-Readern als Untertitel des Feeds angezeigt.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['logging']['0'] = "Logging";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['logging']['1'] = "Die Logging-Stufe auswählen. Log Nachrichten werden in die Dateien system/logs/Helpdesk*.log eingetragen.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['loglevel']['0'] = "aus";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['loglevel']['1'] = "kurz";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['loglevel']['2'] = "ausführlich";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['loglevel']['3'] = "maximal (debug)";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavoptions']['0'] = "Text";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavoptions']['1'] = "Symbole";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editoptions']['0'] = "Niemand";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editoptions']['1'] = "Nur normale Benutzer";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editoptions']['2'] = "Jedermann";
 
?>
