<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/de/tl_helpdesk_bbcode.php 
 * 
 * TYPOlight extension: helpdesk 1.2.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Peter Koch (acenes), http://ibk-software.com 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['code'] = "Code:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['note'] = "Notiz:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['edit'] = "Bearbeitung:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['quote'] = "Zitat:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['caution'] = "Vorsicht:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['bold'] = "Fett";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['italics'] = "Kursiv";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['underlined'] = "Unterstrichen";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['superscript'] = "Hochgestellt";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['subscript'] = "Tiefgestellt";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['centered'] = "Zentriert";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['rightaligned'] = "Rechtsbündig";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['justified'] = "Blocksatz";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['list'] = "Unsortierte Liste";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['numberedlist'] = "Dezimal nummerierte Liste";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['romanlist'] = "Römisch nummerierte Liste";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['alphalist'] = "Alfabetisch nummerierte Liste";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['listitem'] = "Listenpunkt";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['code'] = "Code";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['php'] = "PHP Code";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['js'] = "Javascript Code";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['xml'] = "XML Code";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['html'] = "HTML Code";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['css'] = "CSS code";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['c++'] = "C++ code";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['qt'] = "Qt code";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['table'] = "Tabelle";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['tablerow'] = "Tabellenzeile";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['tablecell'] = "Tabellenzelle";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['quote'] = "Zitat";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['information'] = "Information";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['warning'] = "Warnung";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['hyperlink'] = "Hyperlink";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['image'] = "Bild";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['preview'] = "Vorschau";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['help'] = "Hilfe";
 
?>
