<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/de/tl_helpdesk_comments.php 
 * 
 * TYPOlight extension: helpdesk 1.2.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Peter Koch (acenes), http://ibk-software.com 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['commentsfor']['0'] = "[c]Kommentare und Diskussion zu:";
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['commentsfor']['1'] = "[url=[[url]]][big][b][[title]][/b][/big][/url]";
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['commentsfor']['2'] = "(Sie müssen angemeldet sein um einen Beitrag zu erstellen)[/c]";
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['writecomment'] = "Kommentieren";
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['readcomment'] = "Kommentare lesen (1 Beitrag)";
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['readcomments'] = "Kommentare lesen (%s Beiträge)";
 
?>
