<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/de/tl_module.php 
 * 
 * TYPOlight extension: helpdesk 1.2.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Peter Koch (acenes), http://ibk-software.com 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['helpdesk_text']['0'] = "Text";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_text']['1'] = "Geben Sie einen Text an, der in der Titelzeile angezeigt werden soll. Sie dürfen HTML-Auszeichnungen verwenden.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_categories']['0'] = "Kategorien";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_categories']['1'] = "Bitte wählen Sie eine oder mehrere Kategorien aus, die von diesem Modul angezeigt werden sollen.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_links']['0'] = "Index Funktionen";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_links']['1'] = "Zeige die Funktionen auf den Indexseite.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_hideempty']['0'] = "Verstecken wenn leer";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_hideempty']['1'] = "Zeigen Sie dieses Modul nicht an, wenn keine der Kategorien gefunden wurde.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode']['0'] = "Profil Link anzeigen";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode']['1'] = "Auswahl ob und wem Profil Links angezeigt werden.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode_options']['0'] = "Nie";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode_options']['1'] = "An Moderatoren/Supporter der Kategorie";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode_options']['2'] = "An Benutzer/Kunden der Kategorie";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode_options']['3'] = "An jedermann";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profpage']['0'] = "Profil Seitenname";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profpage']['1'] = "Seitenname resp. URL der TYPOlight Mitgliederliste, ohne die Mitglieder-ID angehängt.<br/> Beispiel: <em>http://www.example.com/memberlist.html</em>";
 
?>
