<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/de/tl_user.php 
 * 
 * TYPOlight extension: helpdesk 1.2.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Peter Koch (acenes), http://ibk-software.com 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_user']['helpdesk_timezone']['0'] = "Eigene Zeitzone";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_timezone']['1'] = "Auswahl der eigenen Zeitzone.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_role']['0'] = "Rolle";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_role']['1'] = "Eingabe der Rolle zur Anzeige in Forenbeiträgen.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_location']['0'] = "Ortsangabe";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_location']['1'] = "Ortsangabe (Ort, Land) zur Anzeige in Forum/Helpdesk beiträgen.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_showrealname']['0'] = "Richtigen Namen anzeigen";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_showrealname']['1'] = "Anzeige des richtigen Namens in Forum/Helpdesk Beiträgen.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_showlocation']['0'] = "Ortsangabe anzeigen";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_showlocation']['1'] = "Anzeige von Ort und Land in Forum/Helpdesk Beiträgen.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_signature']['0'] = "Signatur";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_signature']['1'] = "Eingabe der Signatur für Forum/Helpdesk. Zur Formatierung BBCode verwenden.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_subscriptions']['0'] = "Helpdesk-Abonnements";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_subscriptions']['1'] = "Wählen Sie aus, worüber Sie per Email benachrichtigt werden wollen.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_legend'] = "Forum/Helpdesk";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_notifymytickets'] = "Meine eigenen Tickets und Themen";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_notifymyreplies'] = "Tickets und Themen, zu denen ich beigetragen habe";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_allincategory'] = "Alle in %s";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_noyes']['0'] = "Nein";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_noyes']['1'] = "Ja";
 
?>
