<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/it/explain.php 
 * 
 * TYPOlight extension: helpdesk 0.9.0 stable 
 * Italian translation file 
 * 
 * Copyright : (c) 2007, 2008 by Acenes 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Dan (dan), http://www.dss.uniud.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['0']['0'] = "Supporto Privato";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['0']['1'] = "Suppporto ticket per privati: I ticket possono essere visti soltanto dall'autore stesso nel frontend. Usa questa categoria per supporto formale dei singoli privati. In questo caso non c'è bisogno di creare una categoria per ogni cliente.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['1']['0'] = "Supporto Condiviso";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['1']['1'] = "Supporto ticket per gruppi: In questa categoria i clienti possono vedere (ed eventualmente rispondere a) tutti gli altri clienti del gruppo. L'utilizzo di questa categoria è per il supporto informale in un'azienda in cui ci sono tanti membri dello staff e che hanno bisogno di vedere tutte le attività. In questo caso si dovrebbe creare una categoria distinta condivisa per ogni azienda.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['2']['0'] = "Suppporto Pubblico.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['2']['1'] = "Supporto ticket pubblico: Tutti i ticket in questa categoria possono essere visti da chiunque nel frontend, non importa se loggati o appartenenti ad un certo gruppo. Ad ogni modo, soltanto i clienti registrati possono aprire o rispondeer ai ticket.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['3']['0'] = "Forum Riservato";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['3']['1'] = "Un forum normale ma nascosto al pubblico visibile soltanto ai membri registrati.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['4']['0'] = "Forum Pubblico";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['4']['1'] = "Un forum normale che può essere visualizzato da tutti, non importa se loggati o appartenenti a un certo gruppo. Ad ogni modo, soltanto i membri registrati nella categoria spcifica possono creare o rispondere agli argomenti.";
 
?>
