<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/it/helpdesk.php 
 * 
 * TYPOlight extension: helpdesk 0.9.0 stable 
 * Italian translation file 
 * 
 * Copyright : (c) 2007, 2008 by Acenes 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Dan (dan), http://www.dss.uniud.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['helpdesk']['useserverdef'] = "Usa le preimpostazioni del server";
$GLOBALS['TL_LANG']['helpdesk']['today'] = "Oggi";
$GLOBALS['TL_LANG']['helpdesk']['yesterday'] = "Ieri";
$GLOBALS['TL_LANG']['helpdesk']['ungrouped'] = "Senza gruppo";
 
?>
