<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/it/modules.php 
 * 
 * TYPOlight extension: helpdesk 0.9.0 stable 
 * Italian translation file 
 * 
 * Copyright : (c) 2007, 2008 by Acenes 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Dan (dan), http://www.dss.uniud.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['helpdesk_comments']['0'] = "Commenti Forum/Helpdek";
$GLOBALS['TL_LANG']['CTE']['helpdesk_comments']['1'] = "Questo elemento permette ai visitatori di aggiungere commenti in un filone o un ticket forum.";
$GLOBALS['TL_LANG']['MOD']['helpdesk'] = "Forum/Helpdesk";
$GLOBALS['TL_LANG']['MOD']['helpdesk_discuss']['0'] = "Discussioni";
$GLOBALS['TL_LANG']['MOD']['helpdesk_discuss']['1'] = "Partecipa all'helpdesk e ai forum dal backend";
$GLOBALS['TL_LANG']['MOD']['helpdesk_structure']['0'] = "Struttura";
$GLOBALS['TL_LANG']['MOD']['helpdesk_structure']['1'] = "Manutenzione categorie forum/helpdesk";
$GLOBALS['TL_LANG']['MOD']['helpdesk_settings']['0'] = "Impostazioni";
$GLOBALS['TL_LANG']['MOD']['helpdesk_settings']['1'] = "Visualizza e modifica le impostazioni generiche del forum/helpdesk";
$GLOBALS['TL_LANG']['FMD']['helpdesktitle']['0'] = "Titolo del Forum/Helpdesk";
$GLOBALS['TL_LANG']['FMD']['helpdesktitle']['1'] = "Mostra il titolo di una pagina forum/helpdesk con le funzioni page-wide.";
$GLOBALS['TL_LANG']['FMD']['helpdesk']['0'] = "Sezione Forum/Helpdesk";
$GLOBALS['TL_LANG']['FMD']['helpdesk']['1'] = "Mostra una sezione di categorie del forum/helpdesk.";
 
?>
