<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/it/tl_content.php 
 * 
 * TYPOlight extension: helpdesk 0.9.0 stable 
 * Italian translation file 
 * 
 * Copyright : (c) 2007, 2008 by Acenes 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Dan (dan), http://www.dss.uniud.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['helpdesk_category']['0'] = "Categoria";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_category']['1'] = "Per cortesia seleziona la categoria da utilizzare per i commenti filone/ticket.";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_ticket']['0'] = "ID Argomento/Ticket";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_ticket']['1'] = "Lascia non compilato per creare l'argomento in automatico con il primo commento.";
 
?>
