<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/it/tl_helpdesk_bbcode.php 
 * 
 * TYPOlight extension: helpdesk 0.9.0 stable 
 * Italian translation file 
 * 
 * Copyright : (c) 2007, 2008 by Acenes 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Dan (dan), http://www.dss.uniud.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['code'] = "Codice:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['note'] = "Note:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['edit'] = "Modifica:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['quote'] = "Cita:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['caution'] = "Attenzione:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['bold'] = "Grassetto:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['italics'] = "Corsivo";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['underlined'] = "Sottolineato";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['superscript'] = "Apice";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['subscript'] = "Pedice";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['centered'] = "Centrato";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['rightaligned'] = "Allineato a destra";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['justified'] = "Giustificato";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['list'] = "Elenco non ordinato";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['numberedlist'] = "Elenco con numeri decimali";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['romanlist'] = "Elenco con caratteri romani";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['alphalist'] = "Elenco con caratteri alfanumerici";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['listitem'] = "Elemento di elenco";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['code'] = "Codice";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['php'] = "Codice PHP";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['js'] = "Codice Javascript";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['xml'] = "Codice XML";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['html'] = "Codice HTML";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['css'] = "Codice CSS";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['c++'] = "Codice C++";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['qt'] = "Codice Qt";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['table'] = "Tabella";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['tablerow'] = "Riga di tabella";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['tablecell'] = "Cella di tabella";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['quote'] = "Cita";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['information'] = "Informazioni";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['warning'] = "Avviso";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['hyperlink'] = "Collegamento ipertestuale";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['image'] = "Immagine";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['preview'] = "Anteprima";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['help'] = "Aiuto";
 
?>
