<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/it/tl_helpdesk_settings.php 
 * 
 * TYPOlight extension: helpdesk 0.9.0 stable 
 * Italian translation file 
 * 
 * Copyright : (c) 2007, 2008 by Acenes 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Dan (dan), http://www.dss.uniud.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['title'] = "Impostazioni Generali Forum/Helpdesk";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['version'] = "Versione";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['yes'] = "Sì";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['no'] = "No";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['confsync'] = "Vuoi veramente sincronizzare (ricostruire) tutte le statistiche e i valori della cache adesso?";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['synchronize']['0'] = "Sincronizza";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['synchronize']['1'] = "Sincronizza (ricostruisci) tutte le statistiche e i valori della cache";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['edit']['0'] = "Modifica";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['edit']['1'] = "Modifica le impostazioni forum/helpdesk";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['tpage']['0'] = "Argomenti/ticket per pagina";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['tpage']['1'] = "Inserisci il numero di argomenti/ticket presenti su una pagina. 0 o vuoto disabilita la paginazione.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['mpage']['0'] = "Messaggio per";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['mpage']['1'] = "Inserisci il numero di messaggi su una pagina. 0 o vuoto disabilita la paginazione.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['spage']['0'] = "Cerca i risultati per pagina";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['spage']['1'] = "Inserisci il numero dei messaggi trovati in una pagina. 0 o vuoto disabilita la paginazione.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavsize']['0'] = "Dimensione della navigazione pagine";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavsize']['1'] = "Numero di pagine elencato nella navigazione della pagina. Metti 0 o mostra invece \"Pagina N di M\".";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavctl']['0'] = "Controlli di navigazione pagine";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavctl']['1'] = "Seleziona i controlli di navigazione pagina";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['edits']['0'] = "Salva le modifiche di";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['edits']['1'] = "Seleziona il livello di modifica registrazione operazioni.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['postdelay']['0'] = "Re-inserisci tempo di attesa (secondi)";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['postdelay']['1'] = "Numero minimo di secondi tra due post.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['searchdelay']['0'] = "Tempo di attesa tra due ricerche (secondi)";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['searchdelay']['1'] = "Numero minimo di secondi tra due ricerche per evitare attacchi DOS.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['searchmax']['0'] = "Numero # massimo di risultati";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['searchmax']['1'] = "Numero massimo di risultati migliori da far vedere come insieme di risultati della ricerca.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['recenthours']['0'] = "Quadro temporale recente";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['recenthours']['1'] = "Durata massima dei post espressa in ore per mostrare gli argomenti / i ticket recenti.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['images']['0'] = "Cartella immagini frontend";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['images']['1'] = "Lascia vuoto per usare le immagini e le icone preimpostate.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feeds']['0'] = "Abilita feed";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feeds']['1'] = "Spunta per abilitare i RSS feed dei forum e helpdesk.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedmax']['0'] = "Numero di messaggi in un feed";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedmax']['1'] = "Inserisci il numero massimo di messaggi elencato nel feed";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedlimit']['0'] = "Limite dimensione messaggio";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedlimit']['1'] = "Inserisci il numero massimo di carratteri in un messaggio";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedlink']['0'] = "Nome base del feed";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedlink']['1'] = "Inserisci ad esempio <em>helpdesk</em> per i nomi dei feed http://www.example.com/helpdesk&lt;category-number&gt;.xml";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedtitle']['0'] = "Titolo feed";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedtitle']['1'] = "Per esempio, il titolo sarà mostrato in un tab del browser e suggerito come nome abbreviato.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feeddescription']['0'] = "Descrizione feed";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feeddescription']['1'] = "Mostrato come sototitolo nella maggior parte dei browser e lettori di feed.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['logging']['0'] = "Logging";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['logging']['1'] = "Seleziona il livello di logging. I messaggi di log saranno salvati nei file system/logs/Helpdesk*.log";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['loglevel']['0'] = "Chiuso";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['loglevel']['1'] = "Breve";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['loglevel']['2'] = "Dettagliato";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['loglevel']['3'] = "Debug";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavoptions']['0'] = "Testo";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavoptions']['1'] = "Icone";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editoptions']['0'] = "Nessuno";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editoptions']['1'] = "Solo membri";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editoptions']['2'] = "Chiunque";
 
?>
