<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/it/tl_helpdesk_categories.php 
 * 
 * TYPOlight extension: helpdesk 0.9.0 stable 
 * Italian translation file 
 * 
 * Copyright : (c) 2007, 2008 by Acenes 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Dan (dan), http://www.dss.uniud.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['header']['0'] = "Intestazione";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['header']['1'] = "Intestazione per iniziare una nuova categoria. Altrimenti lascia non compilato.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['title']['0'] = "Titolo";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['title']['1'] = "Titolo di questa categoria";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['description']['0'] = "Descrizione";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['description']['1'] = "Una descrizione facoltativa di questa categoria.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['buttons']['0'] = "Editor di Pulsanti";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['buttons']['1'] = "Inserisci un elenco di editor per i bottoni separato da virgola. Separa i gruppi con un punto e virgola. Separa le righe con una newline.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access']['0'] = "Accesso";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access']['1'] = "Modo di accesso alla categoria del frontend.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['replyonly']['0'] = "Soltanto risposta";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['replyonly']['1'] = "I nuvi argomenti/ticket possono essere creati soltanto dai moderatori/assistenti.<br/>\nI memberi/clienti autorizzati possono solo rispondere agli argomenti esistenti.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['published']['0'] = "Pubblicato";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['published']['1'] = "Categoria visualizzata nel frontend per i clienti con credenziali di accesso.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_clients']['0'] = "Clienti/Membri Frontend.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_clients']['1'] = "Membri del frontend autorizzati come membero/cliente di questa categoria.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_supporters']['0'] = "Moderatori/Assistenti Frontend.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_supporters']['1'] = "Membri del frontend autorizzati come moderatori/assistenti per questa categoria.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_clients']['0'] = "Membri/Clienti Backend";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_clients']['1'] = "Membri del backend autorizzati come membri/clienti di questa categoria.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_supporters']['0'] = "Moderatori/Assistenti Backend";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_supporters']['1'] = "Backend users authorized as moderator/supporter of this category.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['feed']['0'] = "Attiva i feed RSS";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['feed']['1'] = "Spunta per attivare i feed RSS in questa categoria.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch']['0'] = "Abilita allegati";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch']['1'] = "Abilita l'utilizzo di allegati";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_dir']['0'] = "Cartella allegati";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_dir']['1'] = "Inserisci il percorso per salvare gli allegati";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_size']['0'] = "Dimensioni allegato";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_size']['1'] = "Inserisi la dimensione totale di tutti gli allegati per un unico post.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_types']['0'] = "Tipi di allegati";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_types']['1'] = "Inserisci l'elenco delle estensioni dei file permessi come allegati, separati da virgola<br />Inserisci * per permettere tutte le estensioni.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify']['0'] = "Abilita notifica";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify']['1'] = "Avvisa gli iscritti per email.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_astext']['0'] = "Invia come testo";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_astext']['1'] = "Spunta per inviare come testo, togli lo spunto per inviare come HTML.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_name']['0'] = "Nome mittente";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_name']['1'] = "Lascia non compilato per usare soltanto l'indirizzo di mail.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_sender']['0'] = "Indirizzo destinatario";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_sender']['1'] = "Lascia non compilato per usare l'indirizzo dell'amministratore.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_fe_url']['0'] = "Base URL frontend";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_fe_url']['1'] = "Dovrebbe essere qualcosa come <em>http://www.example.com/forum</em><br/>\nUsate per gli avvisi frontend, feed RSS e commenti agli articoli.<br/>\nLascia vuoto per disabilitare queste opzioni.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_be_url']['0'] = "Base URL backend";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_be_url']['1'] = "Dovrebbe essere qualcosa come <em>http://www.yoursite.com/typolight/main.php?do=helpdesk</em><br />Lascia non compilato per disabilitare gli avvisi per gli utenti backend.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newsubj']['0'] = "Oggetto per i nuovi argomenti.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newsubj']['1'] = "Puoi usare i tag [[poster]], [[subject]] e [[replytag]].";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newtext']['0'] = "Corpo del testo per nuovi argomenti";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newtext']['1'] = "Puoi usare i tag [[poster]], [[subject]], [[message]] e [[link]].";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_replysubj']['0'] = "Oggetto per le risposte";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_replysubj']['1'] = "Puoi usare i tag [[poster]], [[subject]] e [[replytag]].";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_replytext']['0'] = "Corpo del testo per le risposte";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_replytext']['1'] = "Puoi usare i tag [[poster]], [[subject]], [[message]] e [[link]].";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import']['0'] = "Abilita l'import di mail";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import']['1'] = "Abilita l'import di assistenza richiesta per email.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_server']['0'] = "Server di posta";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_server']['1'] = "Inserisi il nome del server IMAP4/POP3.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_port']['0'] = "Numero porta";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_port']['1'] = "Inserisci il numero di porta, oppure lascia non compilato per usare i valori preimpostati.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_type']['0'] = "Tipo di casella di posta";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_type']['1'] = "Selezione il tipo di casella di posta.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tls']['0'] = "Transport Layer Security (TLS)";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tls']['1'] = "Selezione il tipo TLS/SSL.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_username']['0'] = "Username";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_username']['1'] = "Inserisci lo username del conto di posta.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_password']['0'] = "Password";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_password']['1'] = "Inserisci la password del conto di posta.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_email']['0'] = "A: email";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_email']['1'] = "Inserisci <em>to</em> l'indirizzo di mail, o lascia vuoto per processare tutte le mail.<br />(Questo dovrebbe essere collegato all'indirizzo del mittente degli avvisi.)";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['0'] = "Supporto Privato";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['1'] = "Supporto Condiviso";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['2'] = "Supporto Pubblico";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['3'] = "Forum con Restrizioni";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['4'] = "Forum Pubblico";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_types']['0'] = "POP3";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_types']['1'] = "IMAP4";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['0'] = "Non usare il TLS, anche se il host lo supporta.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['1'] = "Usa il TLS se il host lo sopporta, validare il certificato.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['2'] = "Usa il TLS se il host lo sopporta, non validare il certificato";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['3'] = "Richede il TLS, valida certificato.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['4'] = "Richiede il TLS, non validare il certificato.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['5'] = "Usa SSL, valida il certificato";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['6'] = "Usa SSL, non validare il certificato";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['new']['0'] = "Nuova categoria";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['new']['1'] = "Crea nuoa categoria";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['edit']['0'] = "Modifica";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['edit']['1'] = "Modifica le impostazioni della categoria %s";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['copy']['0'] = "Clona";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['copy']['1'] = "Clona (duplica) questa categoria";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['delete']['0'] = "Cancella";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['delete']['1'] = "Cancella la categoria %s inclusi tutti i ticket";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_notify']['0'] = "Abilita avviso";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_notify']['1'] = "Abilita avviso per la categoria %s";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_notify']['0'] = "Disabilita avviso";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_notify']['1'] = "Disabilita avviso per la categoria %s";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_import']['0'] = "Abilita l''import della mail";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_import']['1'] = "Abilita l'import della mail per la categoria %s";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_import']['0'] = "Disabilita l'import della mail";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_import']['1'] = "Disabilita l'import della mail per la categoria %s";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['publish']['0'] = "Pubblica";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['publish']['1'] = "Pubblica la categoria %s per i clienti";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['unpublish']['0'] = "Rimuovi la pubblicazione";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['unpublish']['1'] = "Rimuovi la categoria %s per i clienti";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderup']['0'] = "Sposta in alto";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderup']['1'] = "Sposta la categoria in alto di una posizione";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderdown']['0'] = "Sposta in basso";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderdown']['1'] = "Sposta la categoria in basso di una posizione";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['tickets'] = "Ticket";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['replies'] = "Risposte";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_subject']['new'] = "Nuovo ticket: [[subject]] [[replytag]]";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_subject']['reply'] = "Rispondi a: [[subject]] [[replytag]]";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_text']['new'] = "[[poster]] ha creato un nuovo ticket in una categoria alla quale sei iscritto:<br /> <hr /> [[message]] <hr /> Il ticket si trova al:<br /> [[link]]<br /> ---<br /> Postino TYPOlight Helpdesk<br /> (Per cortesia non modificare il tag nell'oggetto della mail quando rispondi per email)<br />";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_text']['reply'] = "[[poster]] ha risposto a un ticket al quale sei iscritto:<br />\n<hr />\n[[message]]\n<hr />\nIl messaggio si trova al:<br />\n[[link]]<br />\n---<br />\nPostino TYPOlight Helpdesk<br />\n(Per cortesia non modificare il tag nell'oggetto della mail quando rispondi per email)<br />";
 
?>
