<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/it/tl_helpdesk_frontend.php 
 * 
 * TYPOlight extension: helpdesk 0.9.0 stable 
 * Italian translation file 
 * 
 * Copyright : (c) 2007, 2008 by Acenes 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Dan (dan), http://www.dss.uniud.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_support']['mine'] = "Miei";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['recent'] = "Recenti";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['views'] = "Viste";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unanswered'] = "Nessuna risposta";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unread'] = "Non letti";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['category'] = "Categoria";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['index'] = "Indice";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['ticket'] = "Ticket";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['tickets'] = "Ticket";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['newticket'] = "Nuovo ticket";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['createticket'] = "Crea ticket";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nopaste'] = "Cancella taglia/incolla";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['cutmessage'] = "Taglia messaggio";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['cutticket'] = "Taglia ticket";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['paste'] = "Incolla";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['postreply'] = "Inserisci risposta";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['updatemessage'] = "Aggiorna messaggio";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message'] = "Messaggio";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['replies'] = "Risposte";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['latestpost'] = "L'ultimo post";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['postedby'] = "di %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['lastedit'] = "[L'ultima modifica di %s, %s]";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['subject'] = "Oggetto";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['client'] = "Cliente";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['supporter'] = "Assistente";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['owner'] = "Proprietario";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['creator'] = "Autore";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['poster'] = "Scritto da";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nocategories'] = "Nessuna categoria trovata.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['notickets'] = "Nessun ticket trovato.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nomessages'] = "Nessun messaggio trovato.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status'] = "Status";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status-0'] = "Nessuna risposta";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status-1'] = "Risposte";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status-2'] = "Chiuso";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['reply'] = "Rispondi";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['close'] = "Chiudi";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['open'] = "Apri";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['edit'] = "Modifica";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['quote'] = "Cita";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['delete'] = "Cancella";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['publish'] = "Pubblica";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unpublish'] = "Togli la pubblicazione";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['pinup'] = "Blocca";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unpin'] = "Togli il blocco";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['markcatread'] = "Categoria letta";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['markallread'] = "Tutti letti";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['feed'] = "Feed RSS";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['globfeed'] = "Feed RSS Globali";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['wrote'] = "%s ha scritto:";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['deleteMessageConfirm'] = "Vuoi veramente cancellare questo messaggio?";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['deleteTicketConfirm'] = "Vuoi veramente cancellare questo ticket insieme a tutti i suoi messaggi?";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['client_hint'] = "Per cortesia seleziona il cliente per il quale crei questo ticket, altrimenti lascia vuoto.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['subject_missing'] = "Devi inserire un argomento!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['subject_hint'] = "Per cortesia inserisci una piccola descrizione per il motivo della creazione di questo ticket.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_missing']['create'] = "Devi inserire una descrizione dettagliata!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_missing']['reply'] = "Devi inserire un messaggio di testo!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_missing']['edit'] = "Devi inserire un messaggio di testo!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_hint']['create'] = "Per cortesia inserisci le descrizioni dettagliate del problema insieme a tutte le informazioni aggiuntive.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_hint']['reply'] = "Per cortesia inserisci il testo della risposta.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_hint']['edit'] = "Per cortesia modifica il testo della risposta.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['published'] = "Pubblicato";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['published_hint'] = "Il messaggio è visibile nel frontend alle persone autorizzate.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messages_reverse'] = "I messaggi precedenti in ordine inverso:";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['firstpage'] = "« Primo";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['prevpage'] = "Precedente";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nextpage'] = "Seguente";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['lastpage'] = "Ultimo »";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['page_n_of_m'] = "Pagina %s di %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['gotopage'] = "Vai alla pagina %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['attachments'] = "Allegati";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['atch_size'] = "Numero massimo di allegati:";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['atch_types'] = "Tipi di file ammessi:";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['atchtobig'] = "Gli allegati superano la dimensione massima consentita.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['filetobig'] = "%s supera la dimensione massima per il caricamento di un file per questo server (verifica le impostazioni php.ini)";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['filepartial'] = "% è stato solo parzialmente caricato.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['filebadtype'] = "% non è tipo di file permesso.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['matchinfo'] = "Migliore %s di un totale di %s risultati";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['search'] = "Cerca";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchresult'] = "Risultati";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchinfo'] = "[#%s per %s, rilevanza %s]";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchterms'] = "Cerca termini";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchterms_missing'] = "Devi inserire uno più termini da cercare!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchterms_hint'] = "Per cortesia inserisci un o più termini.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['findmode'] = "Elenco";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['findmode_hint'] = "Seleziona le entità da elencare come risultato.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmode'] = "Tipologia ricerca";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmode_hint'] = "Seleziona la tipologia di ricerca.<br/> Consulta <a href=\"http://dev.mysql.com/doc/refman/6.0/en/fulltext-search.html\">la documentazione MySQL</a> per informazioni sulle ricerche.<br/> i caratteri SQL % e _ possono essere usati in 'like' modi di ricerca.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchparts'] = "Parti cercate";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchparts_unchecked'] = "Devi spuntare una o più parti per cercare!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchparts_hint'] = "Per cortesia spunti una o più parti per cercare.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchcats'] = "Categorie cercate";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchcats_unchecked'] = "Devi spuntare almeno una categoria!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchcats_hint'] = "Per cortesia spunti una o più categorie da cercare.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nomatches'] = "La ricerca non ha fornito risultati.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['postcount'] = "Post: %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['fromloc'] = "Da: %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['viewprofile'] = "Visualizza profilo";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['warnsearchflood'] = "Per cortesia aspetta %s secondi prima di eseguire la prossima ricerca.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['warnpostflood'] = "Per cortesia aspetta %s secondi prima di inserire il prossimo post.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['continue'] = "Continua";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messagetitle']['info'] = "Informazioni";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messagetitle']['warning'] = "Avviso";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messagetitle']['error'] = "Errore";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmodes']['natural'] = "Tutto il testo naturale";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmodes']['boolean'] = "Tutto il testo booleano";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmodes']['like'] = "Identico";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmodes']['binary'] = "Identico binario";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['findmodes']['messages'] = "Tutti i messaggi rilevanti";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['findmodes']['topics'] = "Il primo risultato degli argomenti rilevanti";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['ticket'] = "Argomento";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['tickets'] = "Argomenti";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['newticket'] = "Nuovo argomento";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['createticket'] = "Crea argomento";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['cutticket'] = "Taglia argomento";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['client'] = "Membro";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['supporter'] = "Moderatore";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['owner'] = "Autore";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['notickets'] = "Nessun argomento trovato.";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['status-0'] = "Bloccato";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['status-1'] = "Normale";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['deleteTicketConfirm'] = "Vuoi veramente cancellare questo argomento insieme ai messaggi?";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['client_hint'] = "Per cortesia seleziona il membro se sei l'autore di questo messaggio, altrimenti lascia vuoto.";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['subject_hint'] = "Per cortesia inserisci una breve descrizione dell'oggetto di questo argomento.";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['message_hint']['create'] = "Per cortesia, inserisci una descrizione dettagliata.";
 
?>
