<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/it/tl_helpdesk_comments.php 
 * 
 * TYPOlight extension: helpdesk 0.9.0 stable 
 * Italian translation file 
 * 
 * Copyright : (c) 2007, 2008 by Acenes 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Dan (dan), http://www.dss.uniud.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['commentsfor'] = "[c]Commenti e discussioni per:\n\n[url=[[url]]][big][b][[title]][/b][/big][/url]\n\nDevi essere loggato per poter scrivere un messaggio.[/c]";
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['writecomment'] = "Scrivi un commento";
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['readcomment'] = "Leggi commenti (1 messaggio)";
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['readcomments'] = "Leggi commenti (%s messaggi)";
 
?>
