<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/it/tl_module.php 
 * 
 * TYPOlight extension: helpdesk 0.9.0 stable 
 * Italian translation file 
 * 
 * Copyright : (c) 2007, 2008 by Acenes 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Dan (dan), http://www.dss.uniud.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['helpdesk_text']['0'] = "Indice testo";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_text']['1'] = "Inserisci il testo che sarà mostrato sotto l'intestazione dell pagine indice. Puoi usaer i tag HTML.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_categories']['0'] = "Categorie";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_categories']['1'] = "Per cortesia seleziona una o più categorie da mostrare in questa sezione.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_links']['0'] = "Indice funzioni";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_links']['1'] = "Mostra le funzioni sulla pagina indice.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_hideempty']['0'] = "Nascondi quando vuoto";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_hideempty']['1'] = "Nascondi il modulo quando non viene mostrata nessuna delle categorie selezionate.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode']['0'] = "Mostra i link del profilo.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode']['1'] = "Seleziona quando e a chi saranno visualizzati i link del profilo.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode_options']['0'] = "Mai";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode_options']['1'] = "Alla categoria moderatori/assistenti";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode_options']['2'] = "Alla categoria membri/clienti";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode_options']['3'] = "A tutti";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profpage']['0'] = "Nome pagina del profilo";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profpage']['1'] = "Nome pagina/url del profilo del membro TYPOlight,senza il parametro ID.<br/> Esempio: <em>http://www.example.com/memberlist.html</em>";
 
?>
