<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/it/tl_member.php 
 * 
 * TYPOlight extension: helpdesk 0.9.0 stable 
 * Italian translation file 
 * 
 * Copyright : (c) 2007, 2008 by Acenes 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Dan (dan), http://www.dss.uniud.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_member']['helpdesk_timezone']['0'] = "Fuso orario";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_timezone']['1'] = "Seleziona il fuso orario";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_role']['0'] = "Ruolo";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_role']['1'] = "Inserisci il ruolo da visualizzaer nei post forum/helpdesk.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_showrealname']['0'] = "Mostra il nome reale";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_showrealname']['1'] = "Mostra il nome reale nei post forum/helpdesk.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_showlocation']['0'] = "Mostra dove ti trovi.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_showlocation']['1'] = "Mostra dove ti trovi (città, paese) nei post forum/helpdesk.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_signature']['0'] = "Firma";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_signature']['1'] = "Inserisci una firma per il forum/helpdesk. Usa il BBCode per formattare.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_subscriptions']['0'] = "Iscrizioni";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_subscriptions']['1'] = "Seleziona se vuoi essere avvisato per email.";
$GLOBALS['TL_LANG']['tl_member']['helpdeskDetails'] = "Forum/Helpdesk";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_notifymytickets'] = "I mei argomenti e ticket";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_notifymyreplies'] = "Argomenti e ticket ai quali ho contribuito";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_allincategory'] = "Tutti in %s";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_noyes']['0'] = "No";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_noyes']['1'] = "Sì";
 
?>
