<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/it/tl_user.php 
 * 
 * TYPOlight extension: helpdesk 0.9.0 stable 
 * Italian translation file 
 * 
 * Copyright : (c) 2007, 2008 by Acenes 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Dan (dan), http://www.dss.uniud.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_user']['helpdesk_timezone']['0'] = "Il tuo fuso orario";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_timezone']['1'] = "Seleziona il fuso orario.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_role']['0'] = "Ruolo";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_role']['1'] = "Inserisci il ruolo che hai e che sarà visibile nei post forum/helpdesk.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_location']['0'] = "Il posto in cui ti trovi.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_location']['1'] = "Il posto in cui ti trovi (città, paese) da mostrare nei post forum/helpdesk.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_showrealname']['0'] = "Mostra il vero nome";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_showrealname']['1'] = "Visualizza il vero nome nei post forum/helpdesk.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_showlocation']['0'] = "Mostra dove ti trovi";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_showlocation']['1'] = "Visualizza in che (città, paese) ti trovi nei post forum/helpdesk.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_signature']['0'] = "Firma";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_signature']['1'] = "Inserisci una firma per il forum/helpdesk. Usa il BBCode per la formattazione.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_subscriptions']['0'] = "Iscrizioni";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_subscriptions']['1'] = "Seleziona se vuoi essere avvisato per email.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_notifymytickets'] = "I miei argomenti e ticket";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_notifymyreplies'] = "Ticket e argomenti ai quali ho contribuito";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_allincategory'] = "Tutto in %s";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_noyes']['0'] = "No";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_noyes']['1'] = "Sì";
 
?>
