<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/cs/explain.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Czech translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['0']['0'] = "Soukromá podpora";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['0']['1'] = "Podpora pro jednotlivce: Příspěvky může vidět ve frontend pouze jejich tvůrce. Použijte tuto kategorii pro příklad formální podpory jednotlivců. Není potřeba zde vytvářet kategorii pro každého uživatele.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['1']['0'] = "Sdílená podpora";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['1']['1'] = "Podpora pro skupiny: V této skupině může uživatel vidět příspěvky ostatních uživatelů. Tato kategorie se využívá u formální podpory pro společnosti, kde více zaměstnanců potřebuje vidět všechny aktivity. V tomto případě byste vytvořili odlišnou, sdílenou kategorii pro každou společnost.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['2']['0'] = "Veřejná podpora";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['2']['1'] = "Veřejná podpora: Všechny příspěvky v této kategorii může ve frontend vidět kdokoli, nezáleží, zda je registrován nebo k jaké skupině patří. Ale pouze uživatele registrovaní v této kategorii mohou příspěvky otevřít nebo na ně odpovídat.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['3']['0'] = "Omezené fórum";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['3']['1'] = "Společné fórum, které vidí pouze registrovaní uživatelé, skryto před veřejností.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['4']['0'] = "Veřejné fórum";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['4']['1'] = "Společné fórum, které může vidět kdokoli, nezáleží, zda je registrován nebo k jaké skupině patří. Ale pouze registrovaní uživatelé v této kategorii mohou vytvářet témata a příspěvky nebo na ně odpovídat.";
 
?>
