<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/cs/helpdesk.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Czech translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['helpdesk']['useserverdef'] = "Použít výchozí nastavení";
$GLOBALS['TL_LANG']['helpdesk']['today'] = "Dnes";
$GLOBALS['TL_LANG']['helpdesk']['yesterday'] = "Včera";
$GLOBALS['TL_LANG']['helpdesk']['ungrouped'] = "Neseskupeno";
 
?>
