<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/cs/modules.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Czech translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['helpdesk_comments']['0'] = "Komentáře Fórum/Helpdesk";
$GLOBALS['TL_LANG']['CTE']['helpdesk_comments']['1'] = "Tento prvek umožní uživatelům přidat komentář k tématu nebo příspěvku na fóru nebo helpdesku.";
$GLOBALS['TL_LANG']['MOD']['helpdesk'] = "Fórum/Helpdesk";
$GLOBALS['TL_LANG']['MOD']['helpdesk_discuss']['0'] = "Diskuze";
$GLOBALS['TL_LANG']['MOD']['helpdesk_discuss']['1'] = "Účast ve fórech nebo helpdescích z administrace.";
$GLOBALS['TL_LANG']['MOD']['helpdesk_structure']['0'] = "Struktura";
$GLOBALS['TL_LANG']['MOD']['helpdesk_structure']['1'] = "Správa kategorií fóra nebo helpdesku.";
$GLOBALS['TL_LANG']['MOD']['helpdesk_settings']['0'] = "Nastavení";
$GLOBALS['TL_LANG']['MOD']['helpdesk_settings']['1'] = "Veškerá nastavení fóra nebo helpdesku.";
$GLOBALS['TL_LANG']['FMD']['helpdesktitle']['0'] = "Hlavička fóra nebo helpdesku";
$GLOBALS['TL_LANG']['FMD']['helpdesktitle']['1'] = "Přidá nadpis a popis fóra nebo helpdesku včetně ovladacích funkcí.";
$GLOBALS['TL_LANG']['FMD']['helpdesk']['0'] = "Hlavička a tělo fóra nebo helpdesku";
$GLOBALS['TL_LANG']['FMD']['helpdesk']['1'] = "Přidá kompletní forum nebo helpdesk včetně ovladacích funkcí.";
 
?>
