<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/cs/tl_content.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Czech translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['helpdesk_category']['0'] = "Výběr kategorie";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_category']['1'] = "Vyberte kategorii fóra nebo helpdesku, která bude použita pro komentáře.";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_reference']['0'] = "Předmět komentáře";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_reference']['1'] = "Vyberte předmět, ke kterému se vztahuje komentář.";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_legend'] = "Nastavení komentáře";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_item']['page'] = "Tato strana";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_item']['article'] = "Tento článek";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_item']['news'] = "K novinkám v tomto článku";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_item']['faq'] = "K FAQ v tomto článku";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_item']['event'] = "K událostem v tomto článku";
 
?>
