<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/cs/tl_helpdesk_comments.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Czech translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['commentsfor']['0'] = "[c]Komentáře a diskuze pro:";
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['commentsfor']['1'] = "[url=[[url]]][big][b][[title]][/b][/big][/url]";
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['commentsfor']['2'] = "(Abyste přidal zprávu, musíte být přihlášen.)[/c]";
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['writecomment'] = "Přidat komentář";
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['readcomment'] = "Přečíst komentář (1 příspěvek)";
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['readcomments'] = "Přečíst komentáře (%s příspěvků)";
 
?>
