<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/cs/tl_helpdesk_categories.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Czech translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['header']['0'] = "Název skupiny kategorií";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['header']['1'] = "Název skupiny zadejte pouze pokud chcete kategorie rozdělit do skupin. Uvádějte vždy u první ze skupiny v ostatních případech nechte prázdné.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['title']['0'] = "Název kategorie";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['title']['1'] = "Název této kategorie";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['description']['0'] = "Popis kategorie";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['description']['1'] = "Přidejte doplňující informace k této kategorii.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['buttons']['0'] = "Povolená tlačítka pro editor";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['buttons']['1'] = "Zadejte seznam tlačítek pro editor oddělený čárkou. Zvláštní skupiny oddělené středníkem. Samostatné řádky v editoru odělené novým řádkem.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access']['0'] = "Volby přístupu";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access']['1'] = "Vyberte jednu z úrovní přístupnosti této kategorie (viz. nápověda).";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['replyonly']['0'] = "Povolit pouze odpovědi";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['replyonly']['1'] = "Nová témata mohou vytvořit pouze moderátoři a administrátoři. Registrování členové a klienti mohou pouze odpovědět na stávající témata a příspěvky.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['published']['0'] = "Publikovat";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['published']['1'] = "Tímto zveřejníte tuto kategorii ve svém fóru nebo helpdesku.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_clients']['0'] = "Frontend Členové/Klienti";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_clients']['1'] = "Vyberte skupinu členů autorizovanou jako Frontend Členové/Klienti této kategorie.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_supporters']['0'] = "Frontend Moderátoři/Administrátoři";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_supporters']['1'] = "Vyberte skupinu členů autorizovanou jako Frontend Moderátoři/Administrátoři této kategorie.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_clients']['0'] = "Backend Členové/Klienti";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_clients']['1'] = "Vyberte skupinu uživatelů autorizovanou jako Backend Členové/Klienti této kategorie.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_supporters']['0'] = "Backend Moderátoři/Administrátoři";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_supporters']['1'] = "Vyberte skupinu uživatelů autorizovanou jako Backend Moderátoři/Administrátoři této kategorie.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['feed']['0'] = "Povolit kanál RSS";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['feed']['1'] = "Zkontrolujte, zda je povolen kanál RSS v nastavení.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch']['0'] = "Povolit přílohy";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch']['1'] = "Zde můžete povolit použití příloh.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_dir']['0'] = "Adresář příloh";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_dir']['1'] = "Zadejte cestu, kde jsou uloženy přílohy.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_size']['0'] = "Velikost přílohy";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_size']['1'] = "Zadejte maximální povolenou velikost všech příloh v jedné poště.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_types']['0'] = "Typ přílohy";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_types']['1'] = "Zadejte čárkou oddělený seznam přípon povolených pro přílohy. Zadejte * pro povolení všech přípon.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify']['0'] = "Povolit oznámení";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify']['1'] = "Upozornit uživatele e-mailem.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_astext']['0'] = "Poslat jako text";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_astext']['1'] = "Zde zadáte zaslání emailu jako text, jinak bude zasláno jako HTML.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_name']['0'] = "Jméno odesílatele";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_name']['1'] = "Zanechte prázdné, pokud chcete použít emailovou adresu.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_sender']['0'] = "Adresa odesílatele";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_sender']['1'] = "Zanechte prázdné, pokud chcete použít emailovou adresu administrátora.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_fe_url']['0'] = "Frontend cesta k fóru nebo helpdesku";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_fe_url']['1'] = "Něco jako <em>http://www.domena.cz/forum</em> Využívá se pro oznámení, kanál RSS a komenáře. Zanechte prázdné, pokud nechcete využívat tyto funkce.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_be_url']['0'] = "Backend cesta k fóru nebo helpdesku";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_be_url']['1'] = "Něco jako <em>http://www.domena.cz/contao/main.php?do=helpdesk</em> Zanechte prázde, pokud nechcete povolit oznámení pro backend uživatele.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newsubj']['0'] = "Předmět zprávy pro nová témata";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newsubj']['1'] = "Můžete využít tagy  [[poster]], [[subject]] a [[replytag]].";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newtext']['0'] = "Textové pole zprávy pro nová témata";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newtext']['1'] = "Můžete využít tagy [[poster]], [[subject]], [[message]] a [[link]].";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_replysubj']['0'] = "Předmět zprávy pro nové odpovědi";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_replysubj']['1'] = "Můžete využít tagy  [[poster]], [[subject]] a [[replytag]].";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_replytext']['0'] = "Textové pole zprávy pro nové odpovědi";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_replytext']['1'] = "Můžete využít tagy [[poster]], [[subject]], [[message]] a [[link]].";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import']['0'] = "Povolit import emailem";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import']['1'] = "Zde můžete povolit import požadavků na helpdesk emailem.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_server']['0'] = "Server příchozí pošty";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_server']['1'] = "Zadejte název serveru příchozí pošty POP3/IMAP4.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_port']['0'] = "Číslo portu";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_port']['1'] = "Zadejte číslo portu nebo ponechte prázdné, když chcete zachovat defaultní nastavení.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_type']['0'] = "Typ protokolu";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_type']['1'] = "Vyberte typ protokolu POP3/IMAP4.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tls']['0'] = "Protokol zabezpečené komunikace";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tls']['1'] = "Vyberte protokol zabezpečené komunikace TLS/SSL.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_username']['0'] = "Uživatelské jméno";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_username']['1'] = "Zadejte uživatelské jméno pro přihlášení k mailu.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_password']['0'] = "Heslo";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_password']['1'] = "Zadejte heslo pro přihlášení k mailu.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_email']['0'] = "Adresa pro odpověď";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_email']['1'] = "Zadejte emailovou adresu pro odpověď nebo ponechte prázdné, aby se provedlo u všech mailů. (To by mělo vzájemně souviset s adresou odesílatele oznámení.)";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['0'] = "Soukromá podpora";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['1'] = "Sdílená podpora";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['2'] = "Veřejná podpora";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['3'] = "Omezené fórum";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['4'] = "Veřejné fórum";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_types']['0'] = "POP3";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_types']['1'] = "IMAP4";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['0'] = "Nepoužívejte TLS ani když ho host podporuje.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['1'] = "Pokud host podporuje TLS, použijte ho, validujte certifikát.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['2'] = "Pokud host podporuje TLS, použijte ho, nevalidujte certifikát.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['3'] = "Vyžadujte TLS, validujte certifikát.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['4'] = "Vyžadujte TLS, nevalidujte certifikát";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['5'] = "Použijte SSL, validujte certifikát";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['6'] = "Použijte SSL, nevalidujte certifikát";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['new']['0'] = "Nová kategorie";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['new']['1'] = "Vytvořit novou kategorii.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['edit']['0'] = "Upravit";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['edit']['1'] = "Upravit kategorii %s.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['copy']['0'] = "Duplikovat";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['copy']['1'] = "Duplikovat kategorii %s.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['delete']['0'] = "Odstranit";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['delete']['1'] = "Odstranit kategorii %s včetně všech témat a zpráv.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_notify']['0'] = "Povolit oznámení";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_notify']['1'] = "Povolit oznámení pro kategorii %s.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_notify']['0'] = "Zakázat oznámení";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_notify']['1'] = "Zakázat oznámení pro kategorii %s.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_import']['0'] = "Povolit import emailem";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_import']['1'] = "Povolit import emailem pro kategorii %s.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_import']['0'] = "Zakázat import emailem";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_import']['1'] = "Zakázat import emailem pro kategorii %s.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['publish']['0'] = "Publikovat";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['publish']['1'] = "Publikovat kategorii %s.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['unpublish']['0'] = "Nepublikovat";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['unpublish']['1'] = "Nepublikovat kategorii %s.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderup']['0'] = "Přesunout nahoru";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderup']['1'] = "Přesunout kategorii %s o jednu pozici výše.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderdown']['0'] = "Přesunout dolů";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderdown']['1'] = "Přesunout kategorii %s o jednu pozici dolů.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['tickets'] = "Příspěvky";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['replies'] = "Příspěvky";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_subject']['new'] = "Nový příspěvek: [[subject]] [[replytag]]";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_subject']['reply'] = "Odpověď: [[subject]] [[replytag]]";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_text']['new'] = "[[poster]] byl přidán nový příspěvek v kategorii, kterou jste vytvořil<br /><br />\n<hr /> [[message]] <hr /><br />\nZpráva je umístěna [[link]]<br /><br />\n -------<br /><br />\nContao Fórum/Helpdesk Mail<br />\n(Pokud odpovídáte na tento email, ponechte nezměněný předmět emailu.)<br />";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_text']['reply'] = "[[poster]] byl přidán nový příspěvek v kategorii, kterou jste vytvořil<br /><br />\n<hr /> [[message]] <hr /><br />\nZpráva je umístěna [[link]]<br /><br />\n -------<br /><br />\nContao Fórum/Helpdesk Mail<br />\n(Pokud odpovídáte na tento email, ponechte nezměněný předmět emailu.)<br />";
$GLOBALS['TL_LANG']['tl_helpdesk_fcategories']['tickets'] = "Témata";
 
?>
