<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/cs/tl_helpdesk_frontend.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Czech translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_support']['advanced'] = "Nastavení vyhledávání";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['mine'] = "Moje příspěvky";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['recent'] = "Nedávné";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['views'] = "Zobrazení";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unanswered'] = "Nezodpovězené";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unread'] = "Nepřečtené";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['category'] = "Kategorie";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['index'] = "Index";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['ticket'] = "Téma";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['tickets'] = "Témata";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['newticket'] = "Nové téma";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['createticket'] = "Vytvořit nové téma";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nopaste'] = "Zrušit vyjmout/vložit";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['cutmessage'] = "Vyjmout";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['cutticket'] = "Vyjmout";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['paste'] = "Vložit";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['postreply'] = "Odpovědět";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['updatemessage'] = "Aktualizovat příspěvek";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message'] = "Příspěvek";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['replies'] = "Příspěvky";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['latestpost'] = "Poslední příspěvek";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['postedby'] = "od %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['lastedit'] = "[Poslední úprava od %s, %s]";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['subject'] = "Předmět";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['client'] = "Klient";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['supporter'] = "Podpora";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['owner'] = "Vlastník";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['creator'] = "Tvůrce";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['poster'] = "Odesláno od";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nocategories'] = "Nenalezeny žádné kategorie.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['notickets'] = "Nenalezena žádná témata.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nomessages'] = "Nenalezeny žádné příspěvky.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status'] = "Status";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status-0'] = "Nezodpovězeno";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status-1'] = "Zodpovězeno";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status-2'] = "Zavřeno";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['reply'] = "Odpovědět";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['close'] = "Zavřít";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['open'] = "Otevřít";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['edit'] = "Upravit";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['quote'] = "Citovat";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['delete'] = "Smazat";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['publish'] = "Publikovat";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unpublish'] = "Nepublikovat";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['pinup'] = "Připíchnout";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unpin'] = "Nepřipíchnout";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['markcatread'] = "Přečtená kategorie";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['markallread'] = "Všechno přečtené";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['feed'] = "Kanál RSS";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['globfeed'] = "Globalní kanál  RSS";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['wrote'] = "%s napsal:";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['deleteMessageConfirm'] = "Opravdu chcete smazat tento příspěvek?";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['deleteTicketConfirm'] = "Opravdu chcete smazat toto téma včetně příspěvků, které obsahuje?";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['client_hint'] = "Vyberte klienta, místo kterého chcete vytvořit téma nebo to ponechte prázdné.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['subject_missing'] = "Musíte zadat předmět!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['subject_hint'] = "Zadejte stručný text popisující hlavní důvod tohoto příspěvku.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_missing']['create'] = "Musíte zadat podrobný popis!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_missing']['reply'] = "Musíte zadat text příspěvku!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_missing']['edit'] = "Musíte zadat text příspěvku!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_hint']['create'] = "Zadejte detailní popis záležitosti spolu se všemi známými fakty.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_hint']['reply'] = "Zadejte text odpovědi.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_hint']['edit'] = "Upravte text příspěvku.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['published'] = "Publikovat";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['published_hint'] = "Tímto zveřejníte tento příspěvek.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messages_reverse'] = "Předchozí příspěvky:";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['firstpage'] = "« První";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['prevpage'] = "Předchozí";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nextpage'] = "Další";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['lastpage'] = "Poslední »";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['page_n_of_m'] = "Stránka %s z %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['gotopage'] = "Jdi na stránku %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['attachments'] = "Přílohy";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['atch_size'] = "Maximální velikost všech příloh:&nbsp;";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['atch_types'] = "Povolené typy souborů:&nbsp;";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['atchtobig'] = "Přílohy překročily povolenou maximální velikost.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['filetobig'] = "%s překročil maximální velikost stahovaného souboru pro tento server (zkontrolujte nastavení php.ini).";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['filepartial'] = "%s byl stažen pouze částečně.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['filebadtype'] = "%s nepatří k povolenému typu souboru.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['matchinfo'] = "Nejlepší %s ze všech možných %s variant.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['search'] = "Vyhledat";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchresult'] = "Výsledky";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchinfo'] = "[#%s od %s, platnost %s]";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchterms'] = "Vyhledat klíčová slova:";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchterms_missing'] = "Musíte zadat jednu nebo více podmínek pro vyhledávání!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchterms_hint'] = "Zadejte jednu nebo více podmínek pro vyhledávání.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['findmode'] = "Zobrazit výsledek jako:";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['findmode_hint'] = "Vyberte, které objekty mají být v seznamu jako výsledek.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmode'] = "Prohledávací mód:";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmode_hint'] = "Vyberte vyhledávací mód. <br/>\nVyhledejte si <a href=\"http://dev.mysql.com/doc/refman/6.0/en/fulltext-search.html\" target=\"_blank\">MySQL dokumentaci</a> pro více informací o fulltextovém vyhledávači.<br/>\nJsou povoleny SQL zástupné znaky \"%\" a \"_\".";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchparts'] = "Prohledávané části:";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchparts_unchecked'] = "Musíte vyberat jednu nebo více vyhledávaných částí!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchparts_hint'] = "Vyberte jednu nebo více vyhledávaných částí.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchcats'] = "Prohledávané kategorie:";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchcats_unchecked'] = "Musíte vyberat jednu nebo více kategorií pro vyhledávání!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchcats_hint'] = "Vyberte jednu nebo více kategorií pro vyhledávání.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nomatches'] = "Pro zadaný dotaz nebylo nic nalezeno.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['postcount'] = "Posláno: %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['fromloc'] = "Od: %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['viewprofile'] = "Zobrazit profil";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['warnsearchflood'] = "Počkejte %s sekund před zadáním dalšího vyhledávání.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['warnpostflood'] = "Počkejte %s sekund před zadáním dalšího příspěvku.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['continue'] = "Pokračovat";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messagetitle']['info'] = "Informace";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messagetitle']['warning'] = "Varování";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messagetitle']['error'] = "Chyba";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmodes']['natural'] = "Fulltext natural";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmodes']['boolean'] = "Fulltext boolean";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmodes']['like'] = "Like";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmodes']['binary'] = "Like binary";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['findmodes']['messages'] = "Příspěvky";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['findmodes']['topics'] = "Témata";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['ticket'] = "Téma";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['tickets'] = "Témata";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['newticket'] = "Nové téma";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['createticket'] = "Vytvořit téma";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['cutticket'] = "Vyjmout";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['client'] = "Člen";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['supporter'] = "Moderátor";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['owner'] = "Tvůrce";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['notickets'] = "Nenalezena žádná témata.";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['status-0'] = "Připíchnuto";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['status-1'] = "Normální";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['deleteTicketConfirm'] = "Opravdu chcete smazat toto téma včetně příspěvků, které obsahuje?";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['client_hint'] = "Vyberte člena, místo kterého chcete vytvořit příspěvek nebo zanechte prázdné.";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['subject_hint'] = "Zadejte stručný popis předmětu totoho tématu.";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['message_hint']['create'] = "Zadejte podrobný popis.";
 
?>
