<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/cs/tl_helpdesk_settings.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Czech translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['title'] = "Všeobecné nastavení Fórum/Helpdesk";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['version'] = "Verze";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['yes'] = "Ano";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['no'] = "Ne";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['confsync'] = "Opravdu chcete nyní synchronizovat (znovu obnovit) všechny statistiky a cache hodnoty?";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['synchronize']['0'] = "Synchronizovat";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['synchronize']['1'] = "Synchronizovat (znovu obnovit) všechny statistické a cache hodnoty.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['edit']['0'] = "Upravit";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['edit']['1'] = "Upravit nastavení Fórum/Helpdesk";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['tpage']['0'] = "Počet témat na stránku";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['tpage']['1'] = "Zadejte počet témat na stránku. Zadejte 0, pokud nechcete žádné omezení.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['mpage']['0'] = "Počet příspěvků na stránku";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['mpage']['1'] = "Zadejte počet příspěvků na stránku. Zadejte 0, pokud nechcete žádné omezení.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['spage']['0'] = "Počet výsledků hledání na stránku";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['spage']['1'] = "Zadejte počet nalezených témat nebo příspěvků na stránku. Zadejte 0, pokud nechcete žádné omezení.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavsize']['0'] = "Počet stran v navigaci";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavsize']['1'] = "Zadejte maximální počet stránek uvedených v navigaci stránkování. Zadejte 0, pokud chcete zobrazit pouze \"strana X z Y\".";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavctl']['0'] = "Ovládací prvky navigace";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavctl']['1'] = "Vyberte si ovládací prvky pro navigaci stránkování.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['edits']['0'] = "Označit upravované příspěvky";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['edits']['1'] = "Vyberte úroveň pro označení upravovaných příspěvků.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editswait']['0'] = "Označit upravované příspěvky po (sekundy)";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editswait']['1'] = "Zadejte interval pro označení upravovaných příspěvků.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['postdelay']['0'] = "Interval pro znovu odeslání (sekundy)";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['postdelay']['1'] = "Zadejte minimální interval mezi dvěma příspěvky pro zamezení přetížení.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['searchdelay']['0'] = "Interval pro opětovné vyhledávání (sekundy)";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['searchdelay']['1'] = "Zadejte minimální interval mezi dvěma vyhledáváními, aby bylo zabráněno napadení DOSu.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['searchmax']['0'] = "Maximální # počet vyhledaných záznamů";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['searchmax']['1'] = "Zadejte Maximální počet nejlépe odpovídajícíh vyhledaných záznamů.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['tlsearch']['0'] = "Povolit indexování Contao";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['tlsearch']['1'] = "K již stávajícímu vyhledávání fóra nebo helpdesku povolit indexování témat a příspěvků Contao.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['recenthours']['0'] = "Časový rámec pro Nedávné";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['recenthours']['1'] = "Maximální stáří příspěvku v hodinách pro zobrazení nedávných témat nebo příspěvků.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['images']['0'] = "Frontend adresář obrázků";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['images']['1'] = "Zanechte prázdné, pokud využijete defaultní ikony a obrázky.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feeds']['0'] = "Povolit kanál RSS";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feeds']['1'] = "Zkontrolujte, zda je povolen kanál RSS u fór nebo helpdesků.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedmax']['0'] = "Počet zpráv kanálu RSS";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedmax']['1'] = "Zadejte maximální počet zpráv uvedených v kanálu RSS.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedlimit']['0'] = "Maximální délka zprávy kanálu RSS";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedlimit']['1'] = "Zadejte maximální délku zprávy v kanálu RSS.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedlink']['0'] = "Základ cesty kanálu RSS";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedlink']['1'] = "Zadejte například <em>helpdesk</em> pro kanál RSS http://www.example.com/helpdesk&lt;číslo kategorie&gt;.xml";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedtitle']['0'] = "Název kanálu RSS";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedtitle']['1'] = "Název bude zobrazen například v záložkách prohlížeče a bude navržen jako zkrácený název.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feeddescription']['0'] = "Popis kanálu RSS";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feeddescription']['1'] = "U většiny prohlížečů a čteček je zobrazen jako nadpis.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['logging']['0'] = "Přihlášení";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['logging']['1'] = "Vyberte si přihlašovací úroveň. Přihlašovací zprávy budou nahrány v souborech system/logs/Helpdesk*.log";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['loglevel']['0'] = "Vypnuto";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['loglevel']['1'] = "Stručný";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['loglevel']['2'] = "Detailní";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['loglevel']['3'] = "Ladit";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavoptions']['0'] = "Text";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavoptions']['1'] = "Ikony";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editoptions']['0'] = "Nikdo";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editoptions']['1'] = "Pouze běžní členové";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editoptions']['2'] = "Všichni";
 
?>
