<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/cs/tl_helpdesk_bbcode.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Czech translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['code'] = "Kód:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['note'] = "Poznámka:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['edit'] = "Upravit:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['quote'] = "Zaznamenat:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['caution'] = "Upozornění:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['bold'] = "Tučné";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['italics'] = "Kurzíva";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['underlined'] = "Podtržené";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['superscript'] = "Horní index";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['subscript'] = "Dolní Index";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['centered'] = "Na střed";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['rightaligned'] = "Vpravo";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['justified'] = "Do bloku";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['list'] = "Jednoduchý seznam";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['numberedlist'] = "Seznam 1,2,3";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['romanlist'] = "Seznam I,II,III";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['alphalist'] = "Seznam A,B,C";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['listitem'] = "Položka seznamu";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['code'] = "Kód";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['php'] = "PHP kód";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['js'] = "Javascript kód";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['xml'] = "XML kód";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['html'] = "HTML kód";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['css'] = "CSS kód";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['c++'] = "C++ kód";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['qt'] = "Qt kód";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['table'] = "Tabulka";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['tablerow'] = "Řádek tabulky";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['tablecell'] = "Buňka tabulky";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['quote'] = "Záznam";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['information'] = "Informace";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['warning'] = "Varování";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['hyperlink'] = "Odkaz";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['image'] = "Obrázek";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['preview'] = "Náhled";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['help'] = "Nápověda";
 
?>
