<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/cs/tl_module.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Czech translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['helpdesk_text']['0'] = "Text";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_text']['1'] = "Zadejte text, jaký chcete, aby se zobrazil pod nadpisem na stránce indexu. Můžete použít HTML tagy.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_categories']['0'] = "Kategorie";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_categories']['1'] = "Vyberte prosím jednu nebo více kategorií, které se zobrazí v tomto bloku.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_links']['0'] = "Povolit ovladací funkce";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_links']['1'] = "Zde povolíte zobrazení ovladacích funkcí na stránce indexu.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_hideempty']['0'] = "Skrýt, pokud je prázdné";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_hideempty']['1'] = "Skrýt tento modul, když se nezobrazí žádná z vybraných kategorií.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode']['0'] = "Zobrazit odkaz profilu";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode']['1'] = "Vyberte, kdy a komu se zobrazí odkazy profilu.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode_options']['0'] = "Nikdy";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode_options']['1'] = "Pro kategorii Moderátoři/Administrátoři";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode_options']['2'] = "Pro kategorii Členové/Klienti";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode_options']['3'] = "Pro všechny";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profpage']['0'] = "Stránka profilu";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profpage']['1'] = "Zadejte název stránky nebo url ke stránce profilu, bez ID parameteru člena. Příklad: <em>http://www.example.com/memberlist.html</em>";
 
?>
