<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/cs/tl_member.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Czech translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_member']['helpdesk_timezone']['0'] = "Vaše časové pásmo";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_timezone']['1'] = "Vyberte si své časové pásmo.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_role']['0'] = "Role";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_role']['1'] = "Vyberte si svou roli, která se bude zobrazovat v příspěvcích fóra nebo helpdesku.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_showrealname']['0'] = "Zobrazit skutečné jméno";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_showrealname']['1'] = "Zobrazit skutečné jméno v příspěvcích fóra nebo helpdesku.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_showlocation']['0'] = "Zobrazit umístění";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_showlocation']['1'] = "Zobrazit umístění (město, země) v příspěvcích fóra nebo helpdesku.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_signature']['0'] = "Podpis";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_signature']['1'] = "Zadejte podpis pro fórum nebo helpdesk. Pro formátování použijte BBCode.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_subscriptions']['0'] = "Upozornění";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_subscriptions']['1'] = "Vyberte si, kde chcete být informování emailem o změnách.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_legend'] = "Fórum/Helpdesk";
$GLOBALS['TL_LANG']['tl_member']['helpdeskDetails'] = "Fórum/Helpdesk";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_notifymytickets'] = "Má vlastní témata a příspěvky";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_notifymyreplies'] = "Témata a příspěvky, kam přispívám";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_allincategory'] = "Vše v %s";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_noyes']['0'] = "Ne";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_noyes']['1'] = "Ano";
 
?>
