<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/lv/explain.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Latvian translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Maris Celmins (warrior), http://www.bauskasbiblioteka.lv 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['0']['0'] = "Privāts atbalsts";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['0']['1'] = "Biļešu atbalsts personām: biļetes var redzēt biļetes autors pats Frontend-ā. Izmantojiet šo kategorijas veidu, lai sniegtu piemēram, par oficiālu (formal) atbalstu individuālai personai. Šajā gadījumā katram klientam nav nepieciešams izveidot atsvišķu kategoriju.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['1']['0'] = "Kopīgs atbalsts";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['1']['1'] = "Biļešu atbalsts grupām: Šajā kategorijā klienti var redzēt (un nepieciešamības gadījumā var atbildēt) cits cita biļetes. Šīs kategorijas veidu Izmanto oficiāla (formal) atbalsta sneigšanai uzņēmumam(-iem), kuros vairākiem darbiniekiem nepieciešams redzēt visas darbības. Šajā gadījumā jums katram uzņēmumam jāizveido atšķirīga (distinct) kopīgota (shared) kategorija.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['2']['0'] = "Publisks atbalsts";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['2']['1'] = "Publisks Biļešu atbalsts: Šajā kategorijā visas biļetes Frontend-ā var redzēt ikviens, neatkarīgi vai ir autentifikācija veikta, jeb - nē. Tomēr, tikai reģistrētie klienti šajā kategorijā var atvērt biļetes vai atbildēt uz tām.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['3']['0'] = "Ierobežots forums";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['3']['1'] = "Kopīgs forums, kas ir redzams tikai reģistrētiem lietotājiem un ir slēpts no publiskas apskates.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['4']['0'] = "Publisks forums";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['4']['1'] = "Kopīgs forums, kas ir redzams visiem, neatkarīgi no tā kādām lietotāju grupās lietotājs(-a) ir iekļauts(-a). Tomēr, tikai reģistrētie klienti šajā kategorijā var atvērt biļetes vai atbildēt uz tām.";
 
?>
