<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/lv/modules.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Latvian translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Maris Celmins (warrior), http://www.bauskasbiblioteka.lv 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['helpdesk_comments']['0'] = "Foruma/Helpdesk komentāri";
$GLOBALS['TL_LANG']['CTE']['helpdesk_comments']['1'] = "Šis saturs elements ļauj jūsu apmeklētājiem pievienot komentārus foruma biļetei vai tematam.";
$GLOBALS['TL_LANG']['MOD']['helpdesk'] = "Forum/Helpdesk";
$GLOBALS['TL_LANG']['MOD']['helpdesk_discuss']['0'] = "Diskusija";
$GLOBALS['TL_LANG']['MOD']['helpdesk_discuss']['1'] = "Piedalīties forumos un Heklpdesk no Backend-a";
$GLOBALS['TL_LANG']['MOD']['helpdesk_structure']['0'] = "Struktūra";
$GLOBALS['TL_LANG']['MOD']['helpdesk_structure']['1'] = "Uzturēt kategorijas forumu/Heklpdesk";
$GLOBALS['TL_LANG']['MOD']['helpdesk_settings']['0'] = "Iestatījumi";
$GLOBALS['TL_LANG']['MOD']['helpdesk_settings']['1'] = "Skatīt un rediģēt kopējos foruma/Heklpdesk uzstādījumus";
$GLOBALS['TL_LANG']['FMD']['helpdesktitle']['0'] = "Forum/Helpdesk nosaukums";
$GLOBALS['TL_LANG']['FMD']['helpdesktitle']['1'] = "Attēlot foruma/Helpdesk lapas nosaukumu ar lapu mēroga funkciju.";
$GLOBALS['TL_LANG']['FMD']['helpdesk']['0'] = "Forum/Helpdesk Bloks";
$GLOBALS['TL_LANG']['FMD']['helpdesk']['1'] = "Attēlot foruma/Helpdesk kategoriju bloku.";
 
?>
