<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/lv/tl_content.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Latvian translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Maris Celmins (warrior), http://www.bauskasbiblioteka.lv 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['helpdesk_category']['0'] = "Kategorija";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_category']['1'] = "Lūdzu izvēlieties kategoriju, ko izmantot komentāriem un biļetēm.";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_reference']['0'] = "Komentējamais ieraksts";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_reference']['1'] = "Atlasiet vienumu, uz kuru komentāri attiecas.";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_legend'] = "Helpdesk komentāru iestatījumi";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_item']['page'] = "Šī lapa";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_item']['article'] = "Šis Raksts";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_item']['news'] = "Šī raksta ziņas lasīšanas mudulī";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_item']['faq'] = "Šī raksta BUJ lasīšanas mudulī";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_item']['event'] = "Šī raksta notikumi lasīšanas mudulī";
 
?>
