<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/lv/tl_helpdesk_bbcode.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Latvian translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Maris Celmins (warrior), http://www.bauskasbiblioteka.lv 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['code'] = "Kods:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['note'] = "Piezīme:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['edit'] = "Redakcija:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['quote'] = "Citāts:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['caution'] = "Uzmanību:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['bold'] = "Izcelts";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['italics'] = "Slīpraksts";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['underlined'] = "Pasvītrots";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['superscript'] = "Augšraksts";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['subscript'] = "Apakšraksts";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['centered'] = "Centrēts";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['rightaligned'] = "Izlīdzināts pa labi";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['justified'] = "Izlīdzināts";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['list'] = "Nekārtots saraksts";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['numberedlist'] = "Decimal numbered list";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['romanlist'] = "Roman numbered list";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['alphalist'] = "Alphanumeric numbered list";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['listitem'] = "Saraksta ieraksts";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['code'] = "Kods";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['php'] = "PHP kods";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['js'] = "Javascript kods";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['xml'] = "XML kods";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['html'] = "HTML kods";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['css'] = "CSS kods";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['c++'] = "C++ kods";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['qt'] = "Qt kods";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['table'] = "Tabula";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['tablerow'] = "Tabulas rinda";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['tablecell'] = "Tabulas aile";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['quote'] = "Citāts";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['information'] = "Informācija";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['warning'] = "Brīdinājums";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['hyperlink'] = "Hipersaite";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['image'] = "Attēls";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['preview'] = "Apskates";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['help'] = "Palīdzība";
 
?>
