<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/lv/tl_helpdesk_categories.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Latvian translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Maris Celmins (warrior), http://www.bauskasbiblioteka.lv 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['header']['0'] = "Galvene (Header)";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['header']['1'] = "Ar Galveni iesāk jaunu kategoriju. Citā variantā vēlams atstāt šo lauku tukšu.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['title']['0'] = "Nosaukums";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['title']['1'] = "Kategorijas nosaukums";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['description']['0'] = "Apsraksts";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['description']['1'] = "Neobligāts kategorijas apraksts.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['buttons']['0'] = "Rediģēšanas pogas";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['buttons']['1'] = "Rediģēšanas pogas atdalāmas ar komatu. Atsevišķas grupas - ar semikolu. Atsevišķi pa līnijām - ar jaunu līniju (newline).";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access']['0'] = "Piekļuve";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access']['1'] = "Pieļuve kategorijām Frontend režīmā.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['replyonly']['0'] = "Tikai atbildēt";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['replyonly']['1'] = "Jaunas tēmas/biļetes var izveidot tikai moderatori/atbalstītāji.<br/>Autorizēti dalībnieki/klienti var tikai atbildēt esošajiem tematiem.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['published']['0'] = "Publicēts";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['published']['1'] = "Kategorija ir redzama Frontend-ā atļautajiem klientiem.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_clients']['0'] = "Frontend Dalībnieki/Klienti";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_clients']['1'] = "Frontend lietotāji kā autorizēti dalībnieki/klienti šajā kategorijā.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_supporters']['0'] = "Frontend Moderatori/Atbalstītāji";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_supporters']['1'] = "Frontend lietotāji kā autorizēti moderatori/atbalstītāji šajā kategorijā.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_clients']['0'] = "Backend Dalībnieki/Klienti";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_clients']['1'] = "Backend lietotāji kā autorizēti dalībnieki/klienti šajā kategorijā.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_supporters']['0'] = "Backend Moderatori/Atbalstītāji";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_supporters']['1'] = "Backend lietotāji kā autorizēti moderatori/atbalstītāji šajā kategorijā.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['feed']['0'] = "Atļaut RSS barotnes";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['feed']['1'] = "Atzīmējiet, lai ieslēgtu RSS barotnes šai kategorijai.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch']['0'] = "Atļaut pielikumus";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch']['1'] = "Atļaut izmantot pielikumus.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_dir']['0'] = "Pielikumu direktorija";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_dir']['1'] = "Norādiet direktoriju, kurā tiks uzglabāti pielikumu faili.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_size']['0'] = "Pielikumu apjoms";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_size']['1'] = "Norādiet pieļaujamo pielikumu failu kopējo apjomu vienam ierakstam.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_types']['0'] = "Pielikumu tipi";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_types']['1'] = "Atdalot ar komatu, norādiet atļautos failu paplašinājumus. <br/>Ievadiet * , lai atļautu jebkādu faila paplašinājumu.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify']['0'] = "Ieslēgt apziņošanu";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify']['1'] = "Apziņot abinementus, izmantojot e-pastu.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_astext']['0'] = "Nosūtīt kā tekstu";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_astext']['1'] = "Atzīmē, lai nosūtītu kā vienkāršu tekstu, neatzīmē, lai nosūtītu kā HTML.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_name']['0'] = "Sūtītāja vārds";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_name']['1'] = "Atstājiet tukšu, lai izmantotu tikai veinkāršu e-pasta adresi.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_sender']['0'] = "Sūtītāja adrese";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_sender']['1'] = "Atstājiet tukšu, lai izmantotu administratora e-pasta adresi.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_fe_url']['0'] = "Frontend URL base";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_fe_url']['1'] = "Jābūt kaut kam līdzīgam kā <em>http://www.example.com/forum</em><br/>Lieto Frontend paziņojumu RSS un rakstu komentēšanai.<br/>Atstājiet tukšu, lai izslēgtu šīs funkcijas.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_be_url']['0'] = "Backend URL base";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_be_url']['1'] = "Jābūt kaut kam līdzīgam kā <em>http://www.yoursite.com/contao/main.php?do=helpdesk</em><br />Atstājiet tukšu, lai atspējotu Backend lietotāja paziņojumus.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newsubj']['0'] = "Jaunas tēmas temats";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newsubj']['1'] = "Jūs varat izmantot tagus [[poster]], [[subject]] un [[replytag]].";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newtext']['0'] = "Jaunas tēmas teksta struktūra";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newtext']['1'] = "Jūs varat izmantot tagus [[poster]], [[subject]], [[message]] un [[link]].";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_replysubj']['1'] = "Jūs varat izmantot tagus [[poster]], [[subject]] un [[replytag]].";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_replytext']['0'] = "Atbilžu teksta struktūra";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_replytext']['1'] = "Jūs varat izmantot tagus [[poster]], [[subject]], [[message]] un [[link]].";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import']['0'] = "Ieslēgt e-pastu importu";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_server']['0'] = "E-pasta serveris";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_server']['1'] = "Norādiet IMAP4/POP3 servera nosaukumu.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_port']['0'] = "Porta numurs";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_port']['1'] = "Norādiet porta numuru vai atstājiet šo lauku tukšu.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_type']['0'] = "E-pasta tips";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_type']['1'] = "Izvēleties e-pasta tipu.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tls']['0'] = "Transport Layer Security (TLS)";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tls']['1'] = "Izvēleties TLS/SSL režīmu.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_username']['0'] = "Lietotājvārds";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_username']['1'] = "Norādiet e-pasta adresāta lietotājvārdu.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_password']['0'] = "Parole";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_password']['1'] = "Ievadiet pasta adresāta paroli.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_email']['0'] = "Kam: e-pasts";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_email']['1'] = "Ievadiet <em>to</em> e-pasta adresi vai atstājiet tukšu, lai nosūtītu visus pastus. <br/>(Tas būtu savstarpēji saistīts ar sūtītāja adresi paziņojumos.)";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['0'] = "Privāts atbalsts";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['1'] = "Kopīgs atbalsts";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['2'] = "Publisks atbalsts";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['3'] = "Ierobežots forums";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['4'] = "Publisks forums";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_types']['0'] = "POP3";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_types']['1'] = "IMAP4";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['0'] = "Nelietojiet TLS, pat tad, ja hosts atbalsta to.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['1'] = "Izmantot TLS, ja hosts atbalsta to, apstiprināt sertifikātu.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['2'] = "Izmantot TLS, ja hosts atbalsta to, neapstiprināt sertifikātu.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['3'] = "Nepieciešams TLS, apstiprināt sertifikātu.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['4'] = "Nepieciešams TLS, neapstiprināt sertifikātu.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['5'] = "Lietot SSL, apstiprināt sertifikātu.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['6'] = "Lietot SSL, neapstiprināt sertifikātu.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['new']['0'] = "Jauna kategorija";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['new']['1'] = "Izveidot jaunu kategoriju.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['edit']['0'] = "Rediģēt";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['edit']['1'] = "Rediģēt kategorijas %s iestatījumus.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['copy']['0'] = "Duplicēt";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['copy']['1'] = "Duplicēt šo kategoriju";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['delete']['0'] = "Dzēst";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['delete']['1'] = "Dzēst kategoriju %s kopā ar visiem ierakstiem";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_notify']['0'] = "Ieslēgt apziņošanu";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_notify']['1'] = "Ieslēgt apziņošanu kategorijā %s";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_notify']['0'] = "Izslēgt apziņošanu";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_notify']['1'] = "Izslēgt apziņošanu kategorijā %s";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_import']['0'] = "Ieslēgt e-pasta importu";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_import']['1'] = "Ieslēgt e-pasta importu kategorijā %s";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_import']['0'] = "Izslēgt e-pasta importu";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_import']['1'] = "Izslēgt e-pasta importu kategorijā %s";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['publish']['0'] = "Publicēt";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['publish']['1'] = "Publicēt kategoriju %s klientiem";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['unpublish']['0'] = "Atsaukt publicēšanu";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['unpublish']['1'] = "Atsaukt kategorijas %s publicēšanu klientiem";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderup']['0'] = "Pārvietot uz augšu";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderup']['1'] = "Pārvietot kategoriju uz augšu par vienu pozīciju";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderdown']['0'] = "Pārvietot uz leju";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderdown']['1'] = "Pārvietot kategoriju uz leju par vienu pozīciju";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['tickets'] = "Biļetes";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['replies'] = "Atbildes";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_subject']['new'] = "Jauna biļete: [[subject]] [[replytag]]";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_subject']['reply'] = "Atbilde: [[subject]] [[replytag]]";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_text']['new'] = "[[poster]] ir radījusi jaunu biļeti kategorijā, uz kuru Jūs esat parakstījies:<br /><hr />[[message]]<hr />Ziņa atrodas:<br />[[link]]<br />---<br />Contao Helpdesk Mailer<br />(Lūdzu, saglabājiet atbildes priekšmeta tagu, atbildot uz e-pastu)<br />";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_text']['reply'] = "[[poster]] ir atbildējusi uz biļeti, uz kuru esat abonējis:<br /><hr />[[message]]<hr />Ziņa atrodas:<br />[[link]]<br />---<br />Contao Helpdesk Mailer<br />(Lūdzu, saglabājiet atbildes priekšmeta tagu, atbildot uz e-pastu)<br />";
$GLOBALS['TL_LANG']['tl_helpdesk_fcategories']['tickets'] = "Tēmas";
 
?>
