<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/lv/tl_helpdesk_frontend.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Latvian translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Maris Celmins (warrior), http://www.bauskasbiblioteka.lv 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_support']['advanced'] = "Papildus uzstādījumi";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['mine'] = "Mine";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['recent'] = "Nesenie";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['views'] = "Skatīts";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unanswered'] = "Neatbildēti";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unread'] = "Nelasīti";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['category'] = "Kategorija";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['index'] = "Indekss";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['ticket'] = "Biļete";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['tickets'] = "Biļetes";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['newticket'] = "Jauna biļete";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['createticket'] = "Izveidot biļeti";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nopaste'] = "Atcelt cut/paste";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['cutmessage'] = "Izgriezta ziņa";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['cutticket'] = "Izgriezta biļete";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['paste'] = "Ielīmēt";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['postreply'] = "Atbildēt";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['updatemessage'] = "Atjaunināt ziņu";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message'] = "Ziņa";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['replies'] = "Atbildes";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['latestpost'] = "Jaunākā ziņa";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['postedby'] = "pēc %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['lastedit'] = "[beidzamais rediģēja %s, %s]";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['subject'] = "Tēma";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['client'] = "Klients";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['supporter'] = "Atbalstītājs";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['owner'] = "Īpašnieks";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['creator'] = "Autors";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['poster'] = "Ievietoja";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nocategories'] = "Kategorijas nav atrastas.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['notickets'] = "Biļetes nav atrastas.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nomessages'] = "Ziņas nav atrastas.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status'] = "Statuss";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status-0'] = "Netabildēts";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status-1'] = "Atbildēts";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status-2'] = "Aizvērts";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['reply'] = "Atbildēt";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['close'] = "Aizvērt";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['open'] = "Atvērt";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['edit'] = "Rediģēt";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['quote'] = "Citāts";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['delete'] = "Dzēst";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['publish'] = "Publicēt";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unpublish'] = "Atsaukt publicēšanu";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['pinup'] = "Saspraust";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unpin'] = "Atsaukt saspraušanu";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['markcatread'] = "Kategorija lasīta";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['markallread'] = "Viss lasīts";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['feed'] = "RSS barotne";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['globfeed'] = "Globāla RSS barotne";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['wrote'] = "%s rakstīja:";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['deleteMessageConfirm'] = "Vai jūs tiešām vēlaties izdzēst šo ziņojumu?";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['deleteTicketConfirm'] = "Vai tiešām vēlaties dzēst šo biļeti ar visām tās ziņām?";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['client_hint'] = "Lūdzu, izvēlieties klienta vārdā veidot biļeti, vai atstājiet šo lauku tukšu.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['subject_missing'] = "Jums jānorāda tēma (subject)!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['subject_hint'] = "Lūdzu, ievadiet īsu tekstu, kurā aprakstīta galvenā biļetes būtība.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_missing']['create'] = "You must enter a detailed description!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_missing']['reply'] = "Jums ir jāievada detalizēts apraksts!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_missing']['edit'] = "Jums jāievada ziņojuma teksts!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_hint']['create'] = "Lūdzu, ievadiet detalizētu problēmas aprakstu, kā arī ar visus zināmos faktus.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_hint']['reply'] = "Lūdzu, ievadiet atbildes tekstu.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_hint']['edit'] = "Lūdzu, rediģējiet ziņas tekstu.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['published'] = "Publicēts";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['published_hint'] = "Ziņojums tiek parādīts Frontend tikai autorizētām personām.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messages_reverse'] = "Iepriekšējie ziņojumi apgrieztā secībā:";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['firstpage'] = "« Pirmais";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['prevpage'] = "Iepriekšējais";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nextpage'] = "Nākamais";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['lastpage'] = "Beidzamais »";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['page_n_of_m'] = "Lapa %s no %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['gotopage'] = "Iet uz %s lapu";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['attachments'] = "Pielikumi";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['atch_size'] = "Maksimālais pielikumu apjoms:";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['atch_types'] = "Atļautie failu tipi:";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['atchtobig'] = "Pielikumi nedrīkst pārsniegt maksimāli atļauto apjomu.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['filetobig'] = "%s pārsniedz maksimālo augšupielādes failu lielumu šajā serverī (pārbaudiet php.ini uzstādījumus).";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['filepartial'] = "%s tika tikai daļēji augšupielādēti.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['filebadtype'] = "%s nesatur atļauto failu tipu.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['matchinfo'] = "Labākais meklēšanas rezultāts %s no kopējām %s sakritībām";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['search'] = "Meklēt";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchresult'] = "Rezultāti";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchinfo'] = "[#%s pēc %s, saistībā ar %s]";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchterms'] = "Meklēšanas nosacījumi";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchterms_missing'] = "Jums jāievada viens vai vairāki meklējamie vārdi!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchterms_hint'] = "Lūdzu, ievadiet vienu vai vairākus meklējamos terminus.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['findmode'] = "Saraksts";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['findmode_hint'] = "Izvēlieties kuri objekti būs rezultātu sarakstā.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmode'] = "Meklēšanas režīms";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmode_hint'] = "Izvēlieties meklēšanas režīmu.<br/>Skatīt <a href=\"http://dev.mysql.com/doc/refman/6.0/en/fulltext-search.html\">MySQL dokumentāciju</a> lai iegūtu informāciju par pilnteksta meklēšanu.<br/>SQL aizstājējzīmes % un _ var lietot 'like' meklēšanas režīmos.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchparts'] = "Meklētās daļas";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchparts_unchecked'] = "Jums ir jāpārbauda vienu vai vairākas meklējamās daļas!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchparts_hint'] = "Lūdzu pārbaudiet vienu vai vairākas meklējamās daļas!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchcats'] = "Meklēts kategorijās";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchcats_unchecked'] = "Jums ir jāatzīmē vismaz viena kategorija!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchcats_hint'] = "Lūdzu atzīmē vismaz vienu kategoriju!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nomatches'] = "Meklēšanai nav rezultātu.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['postcount'] = "Atbildes: %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['fromloc'] = "No: %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['viewprofile'] = "Skatīt profilu";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['warnsearchflood'] = "Lūdzu uzgaidiet %s sekundes pirms uzsākat nākamo meklēšanu.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['warnpostflood'] = "Lūdzu uzgaidiet %s sekundes pirms jauna paziņojuma iesniegšanas.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['continue'] = "Turpināt";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messagetitle']['info'] = "Informācija";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messagetitle']['warning'] = "Brīdinājums";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messagetitle']['error'] = "Kļūda";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmodes']['natural'] = "Fulltext natural";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmodes']['boolean'] = "Fulltext boolean";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmodes']['like'] = "Like";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmodes']['binary'] = "Like binary";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['findmodes']['messages'] = "Visi attiecīgie ziņojumi";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['findmodes']['topics'] = "Pirmā atbilstība attiecīgā tēmā";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['ticket'] = "Tēma";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['tickets'] = "Tēmas";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['newticket'] = "Jauna tēma";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['createticket'] = "Izveidot tēmu";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['cutticket'] = "Izgriezt tēmu";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['client'] = "Dalībnieks";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['supporter'] = "Moderators";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['owner'] = "Autors";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['notickets'] = "Tēmas nav atrastas.";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['status-0'] = "Piesprausts";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['status-1'] = "Normāls";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['deleteTicketConfirm'] = "Vai Jūs tiešām vēlaties izdzēst šo tēmu ar visām tās ziņām?";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['client_hint'] = "Lūdzu, izvēlieties kura dalībnieka vārdā esat izveidojis šo ziņojumu, jeb - atstājiet to tukšu.";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['subject_hint'] = "Lūdzu, ievadiet īsu tekstu, kas apraksta priekšmetu šajā tēmā.";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['message_hint']['create'] = "Lūdzu, ievadiet detalizētu aprakstu.";
 
?>
