<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/lv/tl_helpdesk_bbhelp.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Latvian translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Maris Celmins (warrior), http://www.bauskasbiblioteka.lv 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_bbhelp']['help'] = "[h1]Contao Forums/Helpdesk - BBCode Ātrā Atsauce[/h1][h2]Tekts Formatēšana[/h2][table=1][tr] 	[th] Formatēšana [/th]	[th] BB Code [/th]	[th] Izejas dati [/th][/tr]";
 
?>
