<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/lv/tl_helpdesk_settings.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Latvian translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Maris Celmins (warrior), http://www.bauskasbiblioteka.lv 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['title'] = "Foruma/Helpdesk globālie iestatījumi";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['version'] = "Versija";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['yes'] = "Jā";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['no'] = "Nē";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['confsync'] = "Vai tiešām vēlaties tagad sinhronizēt (atjaunot), visu veidu statistiku, un kešatmiņā saglabātos ierakstus?";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['synchronize']['0'] = "Sinhronizēt";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['synchronize']['1'] = "Sinhronizēt (atjaunot), visu veidu statistiku un kešatmiņā saglabātos ierakstus";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['edit']['0'] = "Rediģēt";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['edit']['1'] = "Rediģēt foruma/Helpdesk iestatījumus";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['tpage']['0'] = "Tēmas/biļetes vienā lapā";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['tpage']['1'] = "Ievadiet tēmas/biļetes skaitu vienā lapā. 0 vai tukšs izslēdz lapošanu.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['mpage']['0'] = "Ziņojumi vienā lapā";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['mpage']['1'] = "Ievadiet paziņojumu skaitu vienā lapā. 0 vai tukšs izslēdz lapošanu.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['spage']['0'] = "Meklēšanas rezultāti vienā lapā";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['spage']['1'] = "Ievadiet meklēšanas rezultātu skaitu vienā lapā. 0 vai tukšs izslēdz lapošanu.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavsize']['0'] = "Lapas navigācijas izmērs";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavsize']['1'] = "Lapu skaits lapu navigācijas sarakstā. Iestatiet 0, lai aizstātu \"Page N of M\" paziņojumu.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavctl']['0'] = "Lapas navigācijas kontroles";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavctl']['1'] = "Izvēlaties lapas navigācijas kontroles";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['edits']['0'] = "Atzīmēt labojumus no";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['edits']['1'] = "Izvēlieties informācijas līmeni, rediģēšanas darbības ierakstiem.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editswait']['0'] = "Atzīmēt labojumus pēc (sekundēm)";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editswait']['1'] = "Laiks, cik ilgi jauna ziņa var tikt mainīta, pirms tiek atzīmēta kā rediģēta.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['postdelay']['0'] = "Atkārtotas paziņošanas (re-post) laiks (sekundēs)";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['postdelay']['1'] = "Minimālais laiks satrp divām paziņojumu ievietošanas reizēm, lai kavētu flooding.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['searchdelay']['0'] = "Atkārtotas meklēšanas starplaiks (sekundēs)";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['searchdelay']['1'] = "Minimālais periods starp divām meklēšanas reizēm, lai kavēt DOS uzbrukumus.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['searchmax']['0'] = "Maksimums # no meklēšanas sakritībām";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['searchmax']['1'] = "Maksimālais labāko meklešanas rezultātu skaits.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['tlsearch']['0'] = "Ieslēgt Contao meklēšanu";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['tlsearch']['1'] = "Papildus Helpdesk iekšējai meklēšanai, ieslēdz Contao tēmu/biļešu indeksācijas meklētājprogrammu.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['recenthours']['0'] = "Nesenā terimiņā";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['recenthours']['1'] = "Maksimālais paziņojumu vecums stundās nesen attēlotajās tēmās/biļetēs.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['images']['0'] = "Frontend attēlu direktorija";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['images']['1'] = "Atstājiet tukšu, lai izmantotu noklusētās ikonas un attēlus.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feeds']['0'] = "Ieslēgt barotnes";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feeds']['1'] = "Atzīmējiet, lai ieslēgtu forumos un Helpdesk RSS barotnes.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedmax']['0'] = "Paziņojumu skaits barotnē";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedmax']['1'] = "Norādiet maksimālo paziņojumu skaitu vienas barotnes sarakstā.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedlimit']['0'] = "Paziņojuma apjoma ierobežojums";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedlimit']['1'] = "Norādiet maksimālo skaitļu vai simbolu skaitu vienā paziņojuma tekstā.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedlink']['0'] = "Barotnes bāzes nosaukums";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedlink']['1'] = "Norādiet piemēram <em>helpdesk</em> barotņu nosaukumiem http://www.example.com/helpdesk<category-number>.xml";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedtitle']['0'] = "Barotnes nosaukums";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedtitle']['1'] = "Nosaukums būs, piemēram, parādīts pārlūkprogrammas cilnēs, un piedāvāts kā īsceļa nosaukums.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feeddescription']['0'] = "Barotņu apraksts";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feeddescription']['1'] = "Attēlots kā apakšvirsraksts lielākajā daļā pārlūkprogrammu un barotņu lasītājos.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['logging']['0'] = "Žurnalēšana";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['logging']['1'] = "Izvēlieties žurnalēšanas līmeni. Žurnāla ieraksti tiks ierakstīti failos system/logs/Helpdesk*.log";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['loglevel']['0'] = "Izslēgt";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['loglevel']['1'] = "Kopsavilkums";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['loglevel']['2'] = "Detalizēti";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['loglevel']['3'] = "Debug";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavoptions']['0'] = "Teksts";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavoptions']['1'] = "Ikonas";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editoptions']['0'] = "Neviens";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editoptions']['1'] = "Tikai parastiem dalībniekiem";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editoptions']['2'] = "Visi";
 
?>
