<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/lv/tl_helpdesk_comments.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Latvian translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Maris Celmins (warrior), http://www.bauskasbiblioteka.lv 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['commentsfor']['0'] = "[c]Komentāri un diskusija par:";
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['commentsfor']['1'] = "[url=[[url]]][big][b][[title]][/b][/big][/url]";
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['commentsfor']['2'] = "(Jums jābūt pieteikušamies, lai pievienotu ziņojumu)[/c]";
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['writecomment'] = "Rakstīt komentāru";
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['readcomment'] = "Lasīt komentārus (1 ziņa)";
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['readcomments'] = "Lasīt komentārus (%s ziņas)";
 
?>
