<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/lv/tl_module.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Latvian translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Maris Celmins (warrior), http://www.bauskasbiblioteka.lv 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['helpdesk_text']['0'] = "Ineksa teksts";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_text']['1'] = "Ievadiet tekstu, kas redzams zem virsraksta indeksu lapā. Jūs varat izmantot HTML tagus.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_categories']['0'] = "Kategorijas";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_categories']['1'] = "Lūdzu, izvēlieties vienu vai vairākas kategorijas, ko var redzēt šajā blokā.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_links']['0'] = "Indeksa funkcijas";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_links']['1'] = "Parādīt funkcijas indeksa lapā.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_hideempty']['0'] = "Slēpt, kad tukšs";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_hideempty']['1'] = "Paslēpt moduli, ja netiek parādīta neviena no kategorijām.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode']['0'] = "Parādīt profila saiti";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode']['1'] = "Izvēlieties, kad un kam profila saites tiek parādītas.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode_options']['0'] = "Nekad";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode_options']['1'] = "Kategorijas moderatoriem/atbalstītājiem";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode_options']['2'] = "Kategorijas dalībniekiem/klientiem";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode_options']['3'] = "Visiem";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profpage']['0'] = "Profila lapas nosaukums";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profpage']['1'] = "Contao dalībnieka profila lapas nosaukums/URL, dalībnieka ID parametra.<br/>Piemēram: <em>http://www.example.com/memberlist.html</em>";
 
?>
