<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/lv/tl_member.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Latvian translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Maris Celmins (warrior), http://www.bauskasbiblioteka.lv 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_member']['helpdesk_timezone']['0'] = "Jūsu laika zona";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_timezone']['1'] = "Izvēleties savu laika zonu.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_role']['0'] = "Loma";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_role']['1'] = "Ievadiet savu lomu, ko attēlot foruma/Helpdesk paziņojumos.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_showrealname']['0'] = "Parādīt reālo vārdu";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_showrealname']['1'] = "Parādīt savu reālo vārdu foruma/Helpdesk paziņojumos.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_showlocation']['0'] = "Parādīt atrašanās vietu";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_showlocation']['1'] = "Parādīt atrašanās vietu (pilsētu, valsti) foruma/Helpdesk paziņojumos.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_signature']['0'] = "Paraksts";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_signature']['1'] = "Ievadiet savu formuma/Helpdesk parakstu. Varat lietot BBCode formatējumu.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_subscriptions']['0'] = "Abonementi";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_subscriptions']['1'] = "Izvēlieties, ja vēlaties saņemt e-pasta paziņojumu.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_legend'] = "Forum/Helpdesk";
$GLOBALS['TL_LANG']['tl_member']['helpdeskDetails'] = "Forum/Helpdesk";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_notifymytickets'] = "Manas tēmas un temati";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_notifymyreplies'] = "Tēmas un temati, kurās līdzdarbojos";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_allincategory'] = "Viss no %s";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_noyes']['0'] = "Nē";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_noyes']['1'] = "Jā";
 
?>
