<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/lv/tl_user.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Latvian translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Maris Celmins (warrior), http://www.bauskasbiblioteka.lv 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_user']['helpdesk_timezone']['0'] = "Jūsu laika zona";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_timezone']['1'] = "Norādiet savu laika zonu.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_role']['0'] = "Loma";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_role']['1'] = "Ievadiet lomu, ko parādīt forumā/Helpdesk ziņojumos.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_location']['0'] = "Novietojums";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_location']['1'] = "Atrašanās vieta (pilsēta, valsts), ko parādīt forumā/Helpdesk ziņojumos.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_showrealname']['0'] = "Parādīt īsto vārdu";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_showrealname']['1'] = "Parādīt īsto vārdu Forumā/Helpdesk iesniegumos.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_showlocation']['0'] = "Parādīt novietojumu";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_showlocation']['1'] = "Parādīt novietojumu (pilsēta, valsts) Forumā/Helpdesk iesniegumos.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_signature']['0'] = "Paraksts";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_signature']['1'] = "Ievadiet savu foruma/Helpdesk lietotāja parakstu. Formatēšanā varat lietot BBCode.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_subscriptions']['0'] = "Abonements";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_subscriptions']['1'] = "Izvēlaties par ko gribat saņemt e-pasta paziņojumus.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_legend'] = "Forums/Helpdesk";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_notifymytickets'] = "Manis iesniegtās biļetes un tēmas";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_notifymyreplies'] = "Biļetes un tēmas, ko esmu iesniedzis";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_allincategory'] = "Viss iekš %s";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_noyes']['0'] = "Nē";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_noyes']['1'] = "Jā";
 
?>
