<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/fr/explain.php 
 * 
 * TYPOlight extension: helpdesk 1.3.0 stable 
 * French translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['0']['0'] = "Support privé";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['0']['1'] = "Assistance par tickets privé : les tickets sont visibles par leur auteur uniquement depuis le front-office. Utilisez ce type de catégorie, par exemple, pour un support individualisé. Dans ce cas, il n'est alors pas nécessaire de créer de catégorie individuelle pour chaques client.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['1']['0'] = "Support partagé";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['1']['1'] = "Support destiné à des groupes : avec cette catégorie, les clients peuvent consulter (et éventuellement répondre à) chaques tickets. Une utilisation typique de cette catégorie serait la mise en place d'un support en ligne pour une société où les employés pourraient consulter toutes les requêtes. Vous devrez, dans ce cas, créer une catégorie partagée pour chacune des sociétés.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['2']['0'] = "Support public";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['2']['1'] = "Support public indissocié : tous les tickets de ce type de catégorie peuvent être consultés par quiconque depuis le front-office, sans aucune distinction de connexion préalable ni d'association à un groupe de membres. Toutefois, seuls les clients attachés à cette catégorie ont la possibilité de créer ou de répondre aux tickets.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['3']['0'] = "Forum restreint";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['3']['1'] = "Un forum visible par ses seuls membres enregistrés et inaccessible par les autres visiteurs du site.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['4']['0'] = "Forum public";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['4']['1'] = "Forum visible par quiconque, sans distinction de connexion préalable ni d'association à un groupe de membres. Toutefois, seuls les membres attachés à cette catégorie et enregistrés ont la possibilité de créer ou de répondre aux discussions.";
 
?>
