<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/fr/helpdesk.php 
 * 
 * TYPOlight extension: helpdesk 1.3.0 stable 
 * French translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['helpdesk']['useserverdef'] = "Utiliser le serveur par défaut";
$GLOBALS['TL_LANG']['helpdesk']['today'] = "Aujourd'hui";
$GLOBALS['TL_LANG']['helpdesk']['yesterday'] = "Hier";
$GLOBALS['TL_LANG']['helpdesk']['ungrouped'] = "Dissocié";
 
?>
