<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/fr/modules.php 
 * 
 * TYPOlight extension: helpdesk 1.3.0 stable 
 * French translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['helpdesk_comments']['0'] = "Commentaire du Forum / Assistance";
$GLOBALS['TL_LANG']['CTE']['helpdesk_comments']['1'] = "Cet élément de contenu permet à vos visiteurs d'ajouter des commentaires dans un forum ou fil de discussion.";
$GLOBALS['TL_LANG']['MOD']['helpdesk'] = "Forum/Assistance";
$GLOBALS['TL_LANG']['MOD']['helpdesk_discuss']['0'] = "Discussions";
$GLOBALS['TL_LANG']['MOD']['helpdesk_discuss']['1'] = "Participer à des forums et des services d'assistance à partir du back office";
$GLOBALS['TL_LANG']['MOD']['helpdesk_structure']['0'] = "Structure";
$GLOBALS['TL_LANG']['MOD']['helpdesk_structure']['1'] = "Gestion des catégories de l'application Forum / Assistance.";
$GLOBALS['TL_LANG']['MOD']['helpdesk_settings']['0'] = "Paramètres";
$GLOBALS['TL_LANG']['MOD']['helpdesk_settings']['1'] = "Afficher et modifier les paramètres généraux du Forum / Assistance.";
$GLOBALS['TL_LANG']['FMD']['helpdesktitle']['0'] = "Titre Forum/Assistance";
$GLOBALS['TL_LANG']['FMD']['helpdesktitle']['1'] = "Ce module affiche le titre de l'application Forum/Assistance avec des fonctions de recherche et de navigations.";
$GLOBALS['TL_LANG']['FMD']['helpdesk']['0'] = "Bloc Forum/Assistance";
$GLOBALS['TL_LANG']['FMD']['helpdesk']['1'] = "Ce module affiche une ou plusieurs catégories de l'application Forum/Assistance sur le front office.";
 
?>
