<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/fr/tl_content.php 
 * 
 * TYPOlight extension: helpdesk 1.3.0 stable 
 * French translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['helpdesk_category']['0'] = "Catégorie";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_category']['1'] = "Choisir la catégorie à utiliser pour les commentaires.";
 
?>
