<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/fr/tl_helpdesk_settings.php 
 * 
 * TYPOlight extension: helpdesk 1.3.0 stable 
 * French translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['title'] = "Paramètres du Forum et assistance";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['version'] = "Version";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['yes'] = "Oui";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['no'] = "Non";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['confsync'] = "Voulez-vous vraiment synchroniser (reconstruire) toutes les statistiques et mettre en cache les valeurs ?";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['synchronize']['0'] = "Synchroniser";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['synchronize']['1'] = "Synchroniser (reconstruire) toutes les statistiques et mettre en cache les valeurs";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['edit']['0'] = "Editer";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['edit']['1'] = "Editer les paramètres du Forum et assistance";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['tpage']['0'] = "Discussions/tickets par page";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['tpage']['1'] = "Saisir le nombre de sujets/tickets par page. 0 ou vide désactive la pagination.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['mpage']['0'] = "Messages par page";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['mpage']['1'] = "Saisir le nombre de messages par page. 0 ou vide désactive la pagination.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['spage']['0'] = "Résultats de recherche par page";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['spage']['1'] = "Saisissez le nombre de messages trouvés par page. 0 ou vide désactive la pagination.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavsize']['0'] = "Pagination";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavsize']['1'] = "Nombre de pages listées dans la paginations. Mettez 0 pour afficher \"Page N à M\"";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavctl']['0'] = "Contrôles de pagination";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavctl']['1'] = "Sélectionnez les contrôles de pagination.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['edits']['0'] = "Enregistrer les modifications de";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['postdelay']['0'] = "Temps d'attente entre 2 posts (en secondes)";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['postdelay']['1'] = "Nombre de secondes minimales entre deux posts pour prévenir du flood";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['searchdelay']['0'] = "Temps d'attente entre les recherche (en secondes)";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['searchdelay']['1'] = "Nombre de secondes minimales entre deux recherches pour prévenir des attaques DOS.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['searchmax']['0'] = "Nombre maximum de recherches correspondantes";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['searchmax']['1'] = "Nombre maximum des meilleurs correspondance qui seront retournées en résultat de recherche.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedlink']['0'] = "Nom du flux";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedtitle']['0'] = "Titre du flux";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feeddescription']['0'] = "Description du flux";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['logging']['0'] = "Journalisation";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['loglevel']['0'] = "Arrêté";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['loglevel']['1'] = "Bref";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['loglevel']['2'] = "Détaillé";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['loglevel']['3'] = "Debug";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavoptions']['0'] = "Texte";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavoptions']['1'] = "Icônes";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editoptions']['0'] = "Personne";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editoptions']['1'] = "Membres normaux seulement";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editoptions']['2'] = "Tout le monde";
 
?>
