<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/fr/tl_helpdesk_frontend.php 
 * 
 * TYPOlight extension: helpdesk 1.3.0 stable 
 * French translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_support']['advanced'] = "Paramètres avancés";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['mine'] = "Les miens";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['recent'] = "Récents";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['views'] = "Vus";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unanswered'] = "Sans réponses";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unread'] = "Afficher les non-lus";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['category'] = "Catégorie";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['index'] = "Sommaire";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['ticket'] = "Ticket";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['tickets'] = "Tickets";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['newticket'] = "Nouveau ticket";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['createticket'] = "Créer un ticket";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nopaste'] = "Annuler couper/coller";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['cutmessage'] = "Couper le message";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['cutticket'] = "Couper le ticket";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['paste'] = "Coller";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['postreply'] = "Réponse";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['updatemessage'] = "Mettre à jour le message";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message'] = "Message";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['replies'] = "Réponses";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['latestpost'] = "Messages récents";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['postedby'] = "par %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['lastedit'] = "[Dernière édition par %s, %s]";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['subject'] = "Sujet";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['client'] = "Client";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['supporter'] = "Assistant";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['owner'] = "Propriétaire";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['creator'] = "Créateur";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['poster'] = "Posté par";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nocategories'] = "Aucune catégorie trouvée.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['notickets'] = "Aucun ticket trouvé.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nomessages'] = "Aucun message trouvé.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status'] = "Etat";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status-0'] = "Non répondu";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status-1'] = "Répondu";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status-2'] = "Fermé";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['reply'] = "Réponse";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['close'] = "Fermer";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['open'] = "Ouvert";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['edit'] = "Editer";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['quote'] = "Citation";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['delete'] = "Supprimer";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['publish'] = "Publier";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unpublish'] = "Ne pas publier";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['pinup'] = "Epingler";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unpin'] = "Ne pas épingler";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['markcatread'] = "Marquer la catégorie comme lue";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['markallread'] = "Marquer tout comme lu";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['feed'] = "Flux RSS";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['globfeed'] = "Flux RSS global";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['wrote'] = "%s a écrit :";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['deleteMessageConfirm'] = "Êtes vous sûr de vouloir supprimer ce message ?";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['deleteTicketConfirm'] = "Êtes vous sûr de vouloir supprimer cette discussion ainsi que tous les messages qu'elle contient ?";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['client_hint'] = "Sélectionner le nom du client pour lequel vous créez ce ticket, autrement laissez vide.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['subject_missing'] = "Vous devez saisir un objet !";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['subject_hint'] = "Saisir un bref texte décrivant la raison principale de ce ticket.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_missing']['create'] = "Vous devez saisir une description détaillée !";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_missing']['reply'] = "Vous devez écrire un message !";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_missing']['edit'] = "Vous devez écrire un message !";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_hint']['create'] = "Saisir une description détaillée de votre question, avec tous les faits connus.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_hint']['reply'] = "Veuillez saisir une réponse.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_hint']['edit'] = "Veuillez éditer le message.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['published'] = "Publié";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['published_hint'] = "Le message est affiché sur le front office aux personnes autorisées.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messages_reverse'] = "Messages précédents dans l'ordre inverse :";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['firstpage'] = "« Première";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['prevpage'] = "Précédente";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nextpage'] = "Suivante";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['lastpage'] = "Dernière »";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['page_n_of_m'] = "Page %s de %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['gotopage'] = "Aller à la page %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['attachments'] = "Fichiers attachés";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['atch_size'] = "Taille maximale de tous les fichiers attachés :";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['atch_types'] = "Types de fichiers autorisés :";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['atchtobig'] = "Les fichiers attachés dépassent la taille maximale autorisé.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['filetobig'] = "%s excède la taille maximale autorisée en envoi pour ce serveur (vérifier les paramètres du fichier php.ini).";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['filepartial'] = "%s est partiellement envoyé.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['filebadtype'] = "%s n'est pas un type de fichier autorisé.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['matchinfo'] = "Les %s meilleurs d'un total de %s trouvés.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['search'] = "Rechercher";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchresult'] = "Résultats";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchinfo'] = "[#%s par %s, pertinence %s]";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchterms'] = "Termes recherchés";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchterms_missing'] = "Vous devez saisir un ou plusieurs termes !";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchterms_hint'] = "Saisissez un ou plusieurs termes de recherche.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['findmode'] = "Liste";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['findmode_hint'] = "Sélectionnez les entités à lister en résultat.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmode'] = "Mode de recherche";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmode_hint'] = "Sélectionner le mode de recherche.<br/>Consulter <a href=\"http://dev.mysql.com/doc/refman/6.0/en/fulltext-search.html\">la documentation de MySQL</a> pour plus d'informations sur la recherche plein texte. Les jokers SQL % et _ peuvent être utilisés dans le mode de recherche 'comme'";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchparts'] = "Parties recherchées";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchparts_unchecked'] = "Vous devez sélectionner une ou plusieurs parties à rechercher !";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchparts_hint'] = "Sélectionnez une ou plusieurs parties à rechercher.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchcats'] = "Catégories recherchées";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchcats_unchecked'] = "Vous devez sélectionner au moins une catégorie !";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchcats_hint'] = "Sélectionnez une ou plusieurs catégories à rechercher.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nomatches'] = "La recherche à retournée aucuns résultats.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['postcount'] = "Messages : %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['fromloc'] = "De : %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['viewprofile'] = "Voir le profil";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['warnsearchflood'] = "Veuillez attendre %s secondes avant de procéder à une nouvelle recherche.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['warnpostflood'] = "Veuillez attendre %s secondes avant d'envoyer un nouveau message.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['continue'] = "Continuer";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messagetitle']['info'] = "Information";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messagetitle']['warning'] = "Attention";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messagetitle']['error'] = "Erreur";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmodes']['natural'] = "Plein texte naturel";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmodes']['boolean'] = "Plein texte booléen";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmodes']['like'] = "Comme";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmodes']['binary'] = "Comme binaire";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['findmodes']['messages'] = "Tous les messages";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['findmodes']['topics'] = "Premier trouvé dans les messages";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['ticket'] = "Discussion";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['tickets'] = "Discussions";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['newticket'] = "Nouvelle discussion";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['createticket'] = "Créer une discussion";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['cutticket'] = "Couper le sujet";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['client'] = "Membre";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['supporter'] = "Modérateur";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['owner'] = "Créateur";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['notickets'] = "Aucune discussion trouvée.";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['status-0'] = "Epinglé";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['status-1'] = "Normal";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['deleteTicketConfirm'] = "Êtes vous sûr de vouloir supprimer cette discussion ainsi que tous ses messages ?";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['client_hint'] = "Sélectionner le nom du membre pour lequel vous créez ce message, autrement laissez vide.";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['subject_hint'] = "Saisir un bref texte décrivant le l'objet de cette discussion.";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['message_hint']['create'] = "Saisissez une description détaillée.";
 
?>
