<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/fr/tl_helpdesk_comments.php 
 * 
 * TYPOlight extension: helpdesk 1.3.0 stable 
 * French translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['writecomment'] = "Ecrire un commentaire";
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['readcomment'] = "Lire les commentaires (1 message)";
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['readcomments'] = "Lire les commentaires (%s message)";
 
?>
