<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/fr/tl_helpdesk_categories.php 
 * 
 * TYPOlight extension: helpdesk 1.3.0 stable 
 * French translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['header']['0'] = "Entête";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['header']['1'] = "Entête pour démarrer une nouvelle catégorie. Laisser le champ vide autrement.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['title']['1'] = "Titre de la catégorie.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['description']['0'] = "Description";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['description']['1'] = "Description optionnelle de cette catégorie.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['buttons']['0'] = "Boutons de l'éditeur";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['buttons']['1'] = "Entrez une liste des de boutons de l'éditeur séparés par des virgules. Les groupes sont séparés par un point-virgule. Les lignes sont séparées par un retour à la ligne.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access']['0'] = "Accès";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access']['1'] = "Mode d'accès à partir du front office à cette catégorie.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['replyonly']['0'] = "Répondre seulement";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['replyonly']['1'] = "Les nouveaux sujets / tickets peuvent seulement être créés par les modérateurs / assistants. <br/>Les membres / clients autorisés peuvent répondre seulement aux sujets existants.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['published']['0'] = "Publiée";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['published']['1'] = "Publier la catégorie sur le front office.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_clients']['0'] = "Membres / Clients du front office";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_clients']['1'] = "Membres / Clients du front office  qui seront autorisés dans cette catégorie.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_supporters']['0'] = "Modérateurs / Assistants du front office";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_supporters']['1'] = "Modérateurs / Assistants du front office qui seront autorisés dans cette catégorie.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_clients']['0'] = "Membres / Clients du back office";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_clients']['1'] = "Utilisateurs du back office qui seront Membres / Clients de cette catégorie.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_supporters']['0'] = "Modérateurs / Assistants du back office";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_supporters']['1'] = "Utilisateurs du back office qui seront Modérateurs / Assistants de cette catégorie.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['feed']['0'] = "Activer le flux RSS";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['feed']['1'] = "Activer le flux RSS de cette catégorie.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch']['0'] = "Activer les fichiers attachés";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch']['1'] = "Activer l'utilisation des fichiers attachés.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_dir']['0'] = "Répertoire des fichiers attachés";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_dir']['1'] = "Saisissez le chemin où seront stockés les fichiers attachés.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_size']['0'] = "Taille des fichiers attachés";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_size']['1'] = "Saisissez la taille totale autorisée pour tous les fichiers attachés d'un envoi.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_types']['0'] = "Type des fichiers attachés";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_types']['1'] = "Saisir une liste séparée par des virgules des extensions de fichier autorisées.<br />Saisir * pour autoriser toutes les extensions.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify']['0'] = "Activer la notification";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify']['1'] = "Notifier les utilisateurs ayant souscrit par e-mail.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_astext']['0'] = "Envoyer comme texte";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_astext']['1'] = "Cocher pour envoyer en tant que texte, décocher pour envoyer en HTML.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_name']['0'] = "Nom de l'émetteur";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_name']['1'] = "Cocher pour envoyer en tant que texte, décocher pour envoyer en HTML.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_sender']['0'] = "Nom de l'émetteur";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_sender']['1'] = "Laisser vide pour seulement utiliser l'adresse e-mail.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_fe_url']['0'] = "URL de base du front office";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_fe_url']['1'] = "ex : <em>http://www.votresite.com/forum</em><br />Laisser vide pour désactiver les notifications des utilisateurs du back office.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_be_url']['0'] = "URL de base du back office";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_be_url']['1'] = "ex : <em>http://www.votresite.com/typolight/main.php?do=helpdesk</em><br />Laisser vide pour désactiver les notifications des utilisateurs du back office.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newsubj']['0'] = "Objet pour les nouveaux sujets";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newsubj']['1'] = "Vous pouvez utiliser les balises [[poster]], [[subject]] et [[replytag]].";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newtext']['0'] = "Message pour les nouveaux sujets";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newtext']['1'] = "Vous pouvez utiliser les balises [[poster]], [[subject]], [[message]] et [[link]].";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_replysubj']['0'] = "Objet pour les réponses";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_replysubj']['1'] = "Vous pouvez utiliser les balises [[poster]], [[subject]] et [[replytag]].";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_replytext']['0'] = "Corps du message pour les réponses";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_replytext']['1'] = "Vous pouvez utiliser les balises [[poster]], [[subject]], [[message]] et [[link]].";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import']['0'] = "Activer l'import d'e-mail";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import']['1'] = "Activer l'import des demandes d'aide par e-mail.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_server']['0'] = "Serveur mail";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_server']['1'] = "Saisissez le nom du serveur IMAP4/POP3.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_port']['0'] = "Numéro de port";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_port']['1'] = "Saisissez le numéro de port, ou laissez vide pour utiliser le port par défaut.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_type']['0'] = "Type de boîte mail";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_type']['1'] = "Sélectionnez le type de boîte mail.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tls']['0'] = "Transport Layer Security (TLS)";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tls']['1'] = "Sélectionnez le mode TLS/SSL.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_username']['0'] = "Nom d'utilisateur";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_username']['1'] = "Saisissez le nom d'utilisateur du compte mail.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_password']['0'] = "Mot de passe";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_password']['1'] = "Saisissez le mot de passe du compte mail.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_email']['0'] = "Pour : (e-mail)";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_email']['1'] = "Saisir l'adresse e-mail de destination ou laisser vide pour envoyer à tous les e-mail.<br />(Doit être en corrélation avec l'adresse e-mail de notification.)";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['0'] = "Support privé";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['1'] = "Support partagé";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['2'] = "Support public";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['3'] = "Forum restreint";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['4'] = "Forum public";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_types']['0'] = "POP3";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_types']['1'] = "IMAP4";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['0'] = "Ne pas utiliser TLS, même si l'hébergeur le supporte.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['1'] = "Utiliser TLS si l'hébergeur le supporte, valider le certificat.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['2'] = "Utiliser TLS si l'hébergeur le supporte, ne pas valider le certificat.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['3'] = "Requière TLS, valider le certificat.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['4'] = "Requière TLS, ne pas valider le certificat.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['5'] = "Utiliser SSL, valider le certificat.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['6'] = "Utiliser SSL, ne pas valider le certificat.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['new']['0'] = "Nouvelle catégorie";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['new']['1'] = "Crée une nouvelle catégorie.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['edit']['0'] = "Editer";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['edit']['1'] = "Editer les préférences de la catégorie %s";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['copy']['0'] = "Cloner";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['copy']['1'] = "Cloner (dupliquer) cette catégorie";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['delete']['0'] = "Supprimer";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['delete']['1'] = "Supprimer la catégorie %s et tous les messages inclus";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_notify']['0'] = "Activer la notification";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_notify']['1'] = "Activer la notification pour la catégorie %s";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_notify']['0'] = "Désactiver la notification";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_notify']['1'] = "Désactiver la notification pour la catégorie %s";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_import']['0'] = "Activer l'import d'e-mail";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_import']['1'] = "Activer l'import d'e-mail pour la categorie %s";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_import']['0'] = "Désactiver l'import d'e-mail";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_import']['1'] = "Désactiver l'import d'e-mail pour la categorie %s";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['publish']['0'] = "Publiée";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['publish']['1'] = "Publier la catégorie %s sur le front office";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['unpublish']['0'] = "Annuler la publication";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['unpublish']['1'] = "Annuler la publication du la catégorie %s sur le front office";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderup']['0'] = "Déplacer vers le haut";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderup']['1'] = "Déplacer la catégorie d'une position vers le haut";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderdown']['0'] = "Déplacer vers le bas";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderdown']['1'] = "Déplacer la catégorie d'une position vers le bas";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['tickets'] = "Tickets";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['replies'] = "Réponses";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_subject']['new'] = "Nouveau sujet :";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_subject']['reply'] = "Répondre au sujet :";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_text']['new'] = "a créé un nouveau sujet dans la catégorie auquelle vous avez souscrit :<br/>\n<hr/>\n\n<hr/>\nLe sujet est situé :<br/> <br/>\n---<br/>\nTYPOlight Forum/Assistance Mailer<br/>\n(Veuillez conserver la balise réponse dans le sujet au cas où vous répondiez par e-mail)<br />";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_text']['reply'] = "a répondu au sujet auquel vous avez souscrit :<br/>\n<hr/>\n\n<hr/>\nLe message est situé : <br/>\n---<br/>\nTYPOlight Forum/Assistance Mailer<br/>\n(Veuillez conserver la balise réponse dans le sujet au cas où vous répondiez par e-mail)<br />";
$GLOBALS['TL_LANG']['tl_helpdesk_fcategories']['tickets'] = "Sujets";
 
?>
