<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/fr/tl_helpdesk_bbcode.php 
 * 
 * TYPOlight extension: helpdesk 1.3.0 stable 
 * French translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['code'] = "Code :";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['note'] = "Note :";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['edit'] = "Edition :";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['quote'] = "Citer :";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['caution'] = "Avertissement :";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['bold'] = "Gras";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['italics'] = "Italique";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['underlined'] = "Souligné";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['superscript'] = "Exposant";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['subscript'] = "Indice";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['centered'] = "Centré";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['rightaligned'] = "Aligné à droite";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['justified'] = "Justifié";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['list'] = "Liste simple";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['numberedlist'] = "Liste numérotée";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['romanlist'] = "Liste numérotée chiffres romains";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['alphalist'] = "Liste numérotée alphanumérique";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['listitem'] = "Elément de liste";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['code'] = "Code";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['php'] = "Code PHP";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['js'] = "Code Javascript";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['xml'] = "Code XML";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['html'] = "Code HTML";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['css'] = "Code CSS";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['c++'] = "Code C++";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['qt'] = "Code Qt";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['table'] = "Tableau";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['tablerow'] = "Ligne de tableau";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['tablecell'] = "Cellule de tableau";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['quote'] = "Citation :";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['information'] = "Information";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['warning'] = "Avertissement";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['hyperlink'] = "Lien hypertexte";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['image'] = "Image";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['preview'] = "Prévisualisation";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['help'] = "Aide";
 
?>
