<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/fr/tl_member.php 
 * 
 * TYPOlight extension: helpdesk 1.3.0 stable 
 * French translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_member']['helpdesk_timezone']['0'] = "Votre fuseau horaire";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_timezone']['1'] = "Sélectionnez votre fuseau horaire.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_role']['0'] = "Rôle";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_role']['1'] = "Entrez le rôle qui doit être affiché dans les messages du Forum / Assistance.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_showrealname']['0'] = "Afficher le vrai nom";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_showrealname']['1'] = "Afficher le vrai nom dans les messages du Forum / Assistance.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_showlocation']['0'] = "Localisation";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_showlocation']['1'] = "Votre localisation (ville, pays) à afficher dans les messages du Forum / Assistance.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_signature']['0'] = "Signature";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_signature']['1'] = "Saisir une signature pour le Forum / Assistance. Utiliser le BBCode pour le formatage.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_subscriptions']['0'] = "Souscriptions";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_subscriptions']['1'] = "Sélectionnez si vous voulez être averti par e-mail.";
$GLOBALS['TL_LANG']['tl_member']['helpdeskDetails'] = "Préférence du Forum/Assistance";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_notifymytickets'] = "Mes tickets et discussions";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_notifymyreplies'] = "Tickets et discussions auquels j'ai participé";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_allincategory'] = "Tous dans %s";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_noyes']['0'] = "Non";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_noyes']['1'] = "Oui";
 
?>
