<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/fr/tl_module.php 
 * 
 * TYPOlight extension: helpdesk 1.3.0 stable 
 * French translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['helpdesk_text']['0'] = "Texte du sommaire";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_text']['1'] = "Saisir un texte à afficher au-dessous du titre. Vous pouvez employer des balises HTML.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_categories']['0'] = "Catégories";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_categories']['1'] = "Choisir une ou plusieurs catégories qui seront affichées par ce module.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_links']['0'] = "Fonctions sur le sommaire";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_links']['1'] = "Afficher les fonctions de recherche et de navigations sur la page sommaire.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_hideempty']['0'] = "Cacher si vide";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_hideempty']['1'] = "Cachez le module quand aucune catégorie n'est trouvée.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode']['0'] = "Aficher le lien du profil";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode']['1'] = "Sélectionnez quand et pour qui le lien du profil est affiché.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode_options']['0'] = "Jamais";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode_options']['1'] = "Pour les modérateurs/assistants";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode_options']['2'] = "Pour les membres/clients";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode_options']['3'] = "Pour tout le monde";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profpage']['0'] = "Nom de la page profil";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profpage']['1'] = "Nom de la page/URL de la page profil des membres de TYPOlight, sans le paramêtre ID.<br/>Exemple : <em>http://www.example.com/memberlist.html</em>";
 
?>
