<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/ro/explain.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Romanian translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Ionuţ Purcaru (purcaruionut) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['0']['0'] = "Asistenţă privată";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['0']['1'] = "Asistenţă pe bază de tichete pentru membri: tichetele poti fi văzute în frontend doar de către creatorul acestora. Folisiţi acest tip de categorie de exemplu pentru suport formal. Nu este nevoie să creaţi o categorie pentru fiecare persoană în acest caz.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['1']['0'] = "Asistenţă restricţionat";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['1']['1'] = "Asistenţă pe bază de tichete pentru grupuri: În această categorie clienţii pot vedea (şi după cay pot răspunde la) tichetele celorlalţi. Un scenariu de utilizare pentru aceast tip de categorie este suportul formal pentru o companie unde mai mlţi angajaţi trebuie să poată vizualiza toate activităţile. În acest caz se va crea o categorie distinctă pentru fiecare companie.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['2']['0'] = "Asistenţă publică";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['2']['1'] = "Asistenţă pe bază de tichete publice: Toate tichetele din acest tip de categorie pot fi văzute de oricine în frontend, indiferent dacă sunt autentificaţi sau aparţin unui grup. Doar clienţii înregistraţi vor putea să deschidă tichete sau să răspundă la acestea.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['3']['0'] = "Forum restricţionat";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['3']['1'] = "Un forum clasic care este vizibil doar de către membrii înregistraţi şi nu este vizibil publicului.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['4']['0'] = "Forum public";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['4']['1'] = "Un forum public ce poate fi văzut de oricine indiferent dacă este autentificat sau dacă aparţine unui anumit grup. Doar membrii înregistraţi pot crea sau răspunde la mesaje.";
 
?>
