<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/ro/helpdesk.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Romanian translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Ionuţ Purcaru (purcaruionut) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['helpdesk']['useserverdef'] = "Setări iniţiale";
$GLOBALS['TL_LANG']['helpdesk']['today'] = "Astăzi";
$GLOBALS['TL_LANG']['helpdesk']['yesterday'] = "Ieri";
$GLOBALS['TL_LANG']['helpdesk']['ungrouped'] = "Negrupat";
 
?>
