<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/ro/modules.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Romanian translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Ionuţ Purcaru (purcaruionut) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['helpdesk_comments']['0'] = "Comentarii pe forum";
$GLOBALS['TL_LANG']['CTE']['helpdesk_comments']['1'] = "Acest element de conţinut permite vizitatorilor să adauge comentarii la un fir de discuţii sau la un tichet.";
$GLOBALS['TL_LANG']['MOD']['helpdesk'] = "Forum/Asistenţă";
$GLOBALS['TL_LANG']['MOD']['helpdesk_discuss']['0'] = "Discută";
$GLOBALS['TL_LANG']['MOD']['helpdesk_discuss']['1'] = "Participă în forum şi la asistenţă din backend";
$GLOBALS['TL_LANG']['MOD']['helpdesk_structure']['0'] = "Structură";
$GLOBALS['TL_LANG']['MOD']['helpdesk_structure']['1'] = "Gestionează categorii pentru forum şi asistenţă";
$GLOBALS['TL_LANG']['MOD']['helpdesk_settings']['0'] = "Setări";
$GLOBALS['TL_LANG']['MOD']['helpdesk_settings']['1'] = "Vizualizează şi editează setările pentru forum/asistenţă";
$GLOBALS['TL_LANG']['FMD']['helpdesktitle']['0'] = "Titlu de forum/asistenţă";
$GLOBALS['TL_LANG']['FMD']['helpdesktitle']['1'] = "Afişează un titlu de pagină valabil pentru forum/asistenţă.";
$GLOBALS['TL_LANG']['FMD']['helpdesk']['0'] = "Bloc de forum/asistenţă";
$GLOBALS['TL_LANG']['FMD']['helpdesk']['1'] = "Afişează un bloc cu categorii de forum/asistenţă.";
 
?>
