<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/ro/tl_content.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Romanian translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Ionuţ Purcaru (purcaruionut) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['helpdesk_category']['0'] = "Categorie";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_category']['1'] = "Alegeţi categoria ce va fi folosită pentru comentarii la forum/asistenţă.";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_reference']['0'] = "Item de comentat";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_reference']['1'] = "Selectaţi elementul la care se vor referi comentariile.";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_legend'] = "Setări pentru comentarii";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_item']['page'] = "Această pagină";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_item']['article'] = "Acest articol";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_item']['news'] = "Anunţuri în modulul de citire în articol";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_item']['faq'] = "Întrebări în modulul de citire în articol";
$GLOBALS['TL_LANG']['tl_content']['helpdesk_item']['event'] = "Evenimente în modulul de citire în articol";
 
?>
