<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/ro/tl_helpdesk_categories.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Romanian translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Ionuţ Purcaru (purcaruionut) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['header']['0'] = "Capăt";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['header']['1'] = "Capăt de pornire al unei categorii de grup. Lăsaţi gol altfel.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['title']['0'] = "Titlu";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['title']['1'] = "Titlu al acestei categorii";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['description']['0'] = "Descriere";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['description']['1'] = "O descriere opţională a acestei categorii";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['buttons']['0'] = "Butoane de etitare";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['buttons']['1'] = "Introduceţi o listă separată prin virgule de butoane pentru editare. Separaţi grupurile prin punct şi virgulă. Separaţi liniile prin Enter.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access']['0'] = "Acces";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access']['1'] = "Tipul de acces la categoria de front end.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['replyonly']['0'] = "Doar răspuns";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['replyonly']['1'] = "Noi subiecte sau tichete pot fi create doar de moderatori sau asistenţi. <br/> Membrii autorizaţi pot doar răspunde la subiectele existente.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['published']['0'] = "Publicat";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['published']['1'] = "Categoria este afişată în frontend la utilizatori cu acces.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_clients']['0'] = "Membri/Clienţi din frontend";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_clients']['1'] = "Membrii frontend autorizaţi ca şi membri/clienţi ai acestei categorii.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_supporters']['0'] = "Moderatori/Asistenţi din frontend";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_supporters']['1'] = "Membrii frontend autorizaţi ca şi moderatori/asistenţi ai acestei categorii.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_clients']['0'] = "Membri/Clienţi din backend";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_clients']['1'] = "Utilizatorii backend autorizaţi ca şi membri/clienţi ai acestei categorii.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_supporters']['0'] = "Moderatori/Asistenţi din backend";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_supporters']['1'] = "Utilizatorii backend autorizaţi ca şi moderatori/asistenţi ai acestei categorii.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['feed']['0'] = "Activează fluxuri RSS";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['feed']['1'] = "Optaţi să se activeaze fluxurile RSS pentru această categorie.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch']['0'] = "Activează ataşamente";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch']['1'] = "Activează folosirea de ataşamente.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_dir']['0'] = "Director de ataşamente";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_dir']['1'] = "Introduceţi calea unde fişierele ataşate sunt stocate.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_size']['0'] = "Mărime ataşament";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_size']['1'] = "Introduceţi mărimea totală maximă permisă pentru fişierele ataşate la un mesaj.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_types']['0'] = "Tipuri de fişiere";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_types']['1'] = "Introduceţi o listă de extensii de fişiere permise separate prin virgulă.<br />Introduceţi * pentru a permite orice extensie.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify']['0'] = "Permite notificare";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify']['1'] = "Notifică pe email pe cei ce au subscris.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_astext']['0'] = "Trimite ca text";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_astext']['1'] = "Bifaţi pentru a trimite ca text, debifaţi pentru a trimite ca HTML.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_name']['0'] = "Nume expeditor";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_name']['1'] = "Lăsaţi liber pentru a folosi doar adresa de email.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_sender']['0'] = "Adresa expeditorului";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_sender']['1'] = "Lăsaţi liber pentru a folosi adresa de email a administratorului.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_fe_url']['0'] = "Baza URL de frontend";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_fe_url']['1'] = "Trebuie să fie ceva de genul <em>http://www.example.com/forum</em><br/>\nSe foloseşte pentru notificări de frontend, fluxuri RSS şi comentare articole.<br/>\nLăsaţi liber pentru a dezactiva aceste facilităţi.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_be_url']['0'] = "Baza URL de backend";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_be_url']['1'] = "Trebuie să fie ceva de genul <em>http://www.yoursite.com/typolight/main.php?do=helpdesk</em><br />Lăsaţi liber pentru a dezactiva.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newsubj']['0'] = "Subiect pentru noi postări";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newsubj']['1'] = "Puteţi folosi tagurile [[poster]], [[subject]] şi [[replytag]].";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newtext']['0'] = "Text pentru noi postări";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newtext']['1'] = "Puteţi folosi tagurile [[poster]], [[subject]], [[message]] and [[link]].";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_replysubj']['0'] = "Subiect pentru răspunsuri";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_replysubj']['1'] = "Puteţi folosi tagurile [[poster]], [[subject]] and [[replytag]].";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_replytext']['0'] = "Text pentru răspunsuri";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_replytext']['1'] = "Puteţi folosi tagurile [[poster]], [[subject]], [[message]] and [[link]].";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import']['0'] = "Activează import de email";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import']['1'] = "Activează importul sau cererile de suport prin email.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_server']['0'] = "Server de email";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_server']['1'] = "Introduceţi numele serverului IMAP4/POP3.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_port']['0'] = "Număr de port";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_port']['1'] = "Introduceţi numărul portului, sau lăsaţi liber pentru a folosi valoarea iniţială.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_type']['0'] = "Tip de mailbox";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_type']['1'] = "Selectaţi tipul de mailbox.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tls']['0'] = "Mod TLS";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tls']['1'] = "Selectaţi modul TLS/SSL.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_username']['0'] = "Utilizator";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_username']['1'] = "Introduceţi contul de utilizator.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_password']['0'] = "Parolă";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_password']['1'] = "Introduceţi parola de utilizator.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_email']['0'] = "Către: adresa";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_email']['1'] = "Introduceţi <em>către</em> adresa, sau lăsaţi liber pentru a procesa toate mesajele.<br />(Aceasta ar trebui să se coreleze cu adresa expeditorului of notifications.)";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['0'] = "Asistenţă privată";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['1'] = "Asistenţă restricţionată";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['2'] = "Asistenţă publică";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['3'] = "Forum restricţionat";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['4'] = "Forum public";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_types']['0'] = "POP3";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_types']['1'] = "IMAP4";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['0'] = "Nu folosi TLS, chiar dacă serverul suportă.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['1'] = "Se foloseşte TLS dacă serverul suportă, cu validare de certificat.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['2'] = "Se foloseşte TLS dacă serverul suportă, cu validare de certificat.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['3'] = "Necesită TLS cu validare de certificat.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['4'] = "Necesită TLS fără validare de certificat.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['5'] = "Foloseşte SSL cu validare de certificat.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['6'] = "Foloseşte SSL fără validare de certificat.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['new']['0'] = "Categorie nouă";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['new']['1'] = "Creează o nouă categorie.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['edit']['0'] = "Editează";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['edit']['1'] = "Editează setările categoriei %s";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['copy']['0'] = "Clonează";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['copy']['1'] = "Face un duplicat al acestei categorii";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['delete']['0'] = "Şterge";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['delete']['1'] = "Şterge categoria %s cu toate tichetele incluse";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_notify']['0'] = "Activează notificare";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_notify']['1'] = "Activează notificarea pentru categoria %s";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_notify']['0'] = "Dezactivează notificarea";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_notify']['1'] = "Dezactivează notificarea pentru categoria %s";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_import']['0'] = "Activează importul de email";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_import']['1'] = "Activează importul de mesaje email pentru categoria %s";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_import']['0'] = "Dezactivează importul de email";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_import']['1'] = "Dezactivează importul de mesaje email pentru categoria %s";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['publish']['0'] = "Publică";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['publish']['1'] = "Publică categoria %s pentru clienţi";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['unpublish']['0'] = "Ascunde";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['unpublish']['1'] = "Ascunde categoria %s pentru clienţi";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderup']['0'] = "Mută în sus";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderup']['1'] = "Mută categoria în sus cu o poziţie";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderdown']['0'] = "Mută în jos";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderdown']['1'] = "Mută categoria în jos cu o poziţie";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['tickets'] = "Tichete";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['replies'] = "Răspunsuri";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_subject']['new'] = "Nou tichet: [[subject]] [[replytag]]";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_subject']['reply'] = "Răspuns la: [[subject]] [[replytag]]";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_text']['new'] = "[[poster]] a creat un nou tichet într-o categorie la care aţi subscris:<br />\n<hr />\n[[message]]\n<hr />\nTichetul este la:<br />\n[[link]]<br />\n---<br />\n<br />\n(Păstraţi tagul de reply în subiectul mesajului când răspundeţi prin email)<br />";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_text']['reply'] = "[[poster]] a răspuns la un tichet într-o categorie la care aţi subscris:<br />\n<hr />\n[[message]]\n<hr />\nMesajul este la:<br />\n[[link]]<br />\n---<br />\n<br />\n(Păstraţi tagul de reply în subiectul mesajului când răspundeţi prin email)<br />";
$GLOBALS['TL_LANG']['tl_helpdesk_fcategories']['tickets'] = "Topice";
 
?>
