<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/ro/tl_helpdesk_settings.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Romanian translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Ionuţ Purcaru (purcaruionut) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['title'] = "Setări generale pentru forum/asistenţă";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['version'] = "Versiune";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['yes'] = "Da";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['no'] = "Nu";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['confsync'] = "Doriţi sincronizarea statisticilor şi valorilor temporare?";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['synchronize']['0'] = "Sincronizează";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['synchronize']['1'] = "Sincronizează toate statisticile şi valorile temporare?";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['edit']['0'] = "Editează";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['edit']['1'] = "Editează setările pentru forum/asistenţă";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['tpage']['0'] = "Topice/tichete per pagină";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['tpage']['1'] = "Introduceţi numărul de topice/tichete pe pagină. 0 sau liber pentru a dezactiva paginarea.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['mpage']['0'] = "Mesaje per pagină";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['mpage']['1'] = "Introduceţi numărul de mesaje pe pagină. 0 sau liber pentru a dezactiva paginarea.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['spage']['0'] = "Rezulatate per pagină";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['spage']['1'] = "Introduceţi numărul de rezultate de căutare pe pagină. 0 sau liber pentru a dezactiva paginarea.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavsize']['0'] = "Mărimea paginii de navigare";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavsize']['1'] = "Introduceţi numărul de pagini listate în navigare. 0 pentru a afişa \"Pagina N din M\".";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavctl']['0'] = "Controale pentru navigare";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavctl']['1'] = "Selectaţi the page navigation controls.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['edits']['0'] = "Marchează editările la";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['edits']['1'] = "Selectaţi nivelul de urmarire pentru editări";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editswait']['0'] = "Marchează reeditare după (secunde)";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editswait']['1'] = "După cât timp un nou mesaj poate fi modificat fără să fie marcat ca fiind reeditat";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['postdelay']['0'] = "Aşteaptă pentru repostare (secunde)";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['postdelay']['1'] = "Perioada minimă între două postări pentru a împiedica un flood.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['searchdelay']['0'] = "Aşteaptă pentru nouă căutare (secunde)";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['searchdelay']['1'] = "Perioada minimă între două căutări pentru a împiedica atacurile DOS.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['searchmax']['0'] = "Număr maxim de potriviri";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['searchmax']['1'] = "Număr maxim de potriviri ce se vor returna ca rezultate la căutare.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['tlsearch']['0'] = "Permite indexarea de Contao";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['tlsearch']['1'] = "Permite indexarea topicelor/tichetelor de către motorul de căutare al Contao, în plus faţă de motorul de căutare al extensiei helpdesk.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['recenthours']['0'] = "Perioadă pentru mesaje recente";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['recenthours']['1'] = "Perioada maximă în ore pentru topice/tichete afişate ca recente.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['images']['0'] = "Director de imagini pentru frontend";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['images']['1'] = "Lăsaţi liber pentru a folosi directorul îniţial";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feeds']['0'] = "Activează fluxuri RSS";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feeds']['1'] = "Alegeţi pentru a activa fluxurile RSS asociate forumurilor şi asistenţei tehnice.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedmax']['0'] = "Număr de mesaje în flux";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedmax']['1'] = "Introduceţi numărul maxim de mesaje listate în flux";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedlimit']['0'] = "Dimensiune maximă mesaj";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedlimit']['1'] = "Introduceţi numărul maxim de caractere pentru textul unui mesaj";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedlink']['0'] = "Baza pentru fluxuri RSS";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedlink']['1'] = "Introduceţi <em>helpdesk</em> pentru nume flux http://www.example.com/helpdesk&lt;category-number&gt;.xml";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedtitle']['0'] = "Titlu flux RSS";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedtitle']['1'] = "Titlul va fi afişat în navigator şi va fi folosit ca nume la link-uri.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feeddescription']['0'] = "Descriere flux RSS";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feeddescription']['1'] = "Afişat ca subtitlu de către majoritatea navigatoarelor şi a aplicaţiilor de citire RSS.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['logging']['0'] = "Jurnal";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['logging']['1'] = "Introduceţi nivelul de păstrare a evenimentelor. Mesajele de log vor fi înregistrate în fişiere system/logs/Helpdesk*.log";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['loglevel']['0'] = "Inactiv";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['loglevel']['1'] = "Scurt";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['loglevel']['2'] = "Detaliat";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['loglevel']['3'] = "Depanare";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavoptions']['0'] = "Text";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavoptions']['1'] = "Iconuri";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editoptions']['0'] = "Nimeni";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editoptions']['1'] = "Doar membri";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editoptions']['2'] = "Toţi";
 
?>
