<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/ro/tl_helpdesk_bbcode.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Romanian translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Ionuţ Purcaru (purcaruionut) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['code'] = "Cod sursă:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['note'] = "Notă:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['edit'] = "Editare:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['quote'] = "Citat:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['caution'] = "Avertisment:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['bold'] = "Aldin";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['italics'] = "Cursiv";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['underlined'] = "Subliniat";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['superscript'] = "Exponent";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['subscript'] = "Indice";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['centered'] = "Centrat";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['rightaligned'] = "Aliniat la dreapta";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['justified'] = "Justificat";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['list'] = "Listă";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['numberedlist'] = "Listă numerotată zecimal";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['romanlist'] = "Listă numerotată roman";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['alphalist'] = "Listă numerotată alfanumeric";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['listitem'] = "Element de listă";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['code'] = "Cod sursă";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['php'] = "Sursă PHP";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['js'] = "Sursă Javascript";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['xml'] = "Sursă XML";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['html'] = "Sursă HTML";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['css'] = "Sursă CSS";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['c++'] = "Sursă C++";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['qt'] = "Sursă Qt";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['table'] = "Tabel";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['tablerow'] = "Rând de tabel";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['tablecell'] = "Celulă de tabel";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['quote'] = "Citat";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['information'] = "Informaţie";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['warning'] = "Avertisment";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['hyperlink'] = "Legătură";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['image'] = "Imagine";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['preview'] = "Previzualizare";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['help'] = "Ajutor";
 
?>
