<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/ro/tl_helpdesk_comments.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Romanian translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Ionuţ Purcaru (purcaruionut) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['commentsfor']['0'] = "[c]Comentarii şi discuţii pentru:";
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['commentsfor']['1'] = "[url=[[url]]][big][b][[title]][/b][/big][/url]";
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['commentsfor']['2'] = "(Trebuie să fiţi autentificat pentru a adăuga mesaje)[/c]";
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['writecomment'] = "Scrie comentariu";
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['readcomment'] = "Citeşte comentarii (un mesaj)";
$GLOBALS['TL_LANG']['tl_helpdesk_comments']['readcomments'] = "Citeşte comentarii (%s mesaje)";
 
?>
