<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/ro/tl_helpdesk_frontend.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Romanian translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Ionuţ Purcaru (purcaruionut) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_support']['advanced'] = "Setări avansate";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['mine'] = "Personale";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['recent'] = "Recente";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['views'] = "Vizualizări";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unanswered'] = "Nerăspunse";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unread'] = "Necitite";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['category'] = "Categorie";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['index'] = "Index";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['ticket'] = "Tichet";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['tickets'] = "Tichete";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['newticket'] = "Nou tichet";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['createticket'] = "Creează tichet";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nopaste'] = "Anulează tăiere/alipire";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['cutmessage'] = "Taie mesaj";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['cutticket'] = "Taie tichet";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['paste'] = "Alipeşte";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['postreply'] = "Trimite răspuns";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['updatemessage'] = "Modifică mesaj";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message'] = "Mesaj";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['replies'] = "Răspunsuri";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['latestpost'] = "Ultima trimitere";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['postedby'] = "de %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['lastedit'] = "[Ultima editare de %s, %s]";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['subject'] = "Subiect";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['client'] = "Client";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['supporter'] = "Asistent";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['owner'] = "Proprietar";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['creator'] = "Creator";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['poster'] = "Postat de";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nocategories'] = "Nu există categorii.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['notickets'] = "Nu există tichete.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nomessages'] = "Nu există mesaje.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status'] = "Status";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status-0'] = "Fără răspuns";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status-1'] = "Cu răspuns";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status-2'] = "Închis";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['reply'] = "Răspunde";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['close'] = "Închide";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['open'] = "Deschide";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['edit'] = "Editează";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['quote'] = "Citează";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['delete'] = "Şterge";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['publish'] = "Publică";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unpublish'] = "Ascunde";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['pinup'] = "Important";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unpin'] = "Normal";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['markcatread'] = "Categorie citită";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['markallread'] = "Totul citit";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['feed'] = "Flux RSS";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['globfeed'] = "Flux RSS global";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['wrote'] = "%s a scris:";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['deleteMessageConfirm'] = "Chiar doriţi să ştergeţi acest mesaj?";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['deleteTicketConfirm'] = "Chiar doriţi să ştergeţi acest tichet cu toate mesajele?";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['client_hint'] = "Alegeţi clientul sau angajatul în numele căruia doriţi să creaţi acest tichet, altfel lăsaţi liber.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['subject_missing'] = "Trebuie să întroduceţi un subiect!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['subject_hint'] = "Introduceţi un text scurt ce descrie motivul principal al acestui tichet.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_missing']['create'] = "Trebuie să introduceţi o descriere detaliată!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_missing']['reply'] = "Trebuie să introduceţi textul mesajului!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_missing']['edit'] = "Trebuie să introduceţi textul mesajului!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_hint']['create'] = "Introduceţi o descriere detaliată a problemei şi paşii după care aceasta se manifestă.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_hint']['reply'] = "Introduceţi textul răspunsului.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_hint']['edit'] = "Editaţi textul mesajului.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['published'] = "Publicat";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['published_hint'] = "Mesajul este publicat persoanelor autorizate în frontend.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messages_reverse'] = "Mesajele anterioare în ordine inversă:";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['firstpage'] = "« Primul";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['prevpage'] = "Anterior";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nextpage'] = "Următor";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['lastpage'] = "Ultimul »";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['page_n_of_m'] = "Pagina %s din %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['gotopage'] = "Mergi la pagina %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['attachments'] = "Fişiere ataşate";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['atch_size'] = "Mărimea maximă pentru toate ataşamentele:";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['atch_types'] = "Tipuri de fişiere permise:";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['atchtobig'] = "Fişierele ataşate depăşesc dimesiunea maximă permisă.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['filetobig'] = "%s depăşeşte dimesiunea de upload maximă permisă de acest server (verificaţi setările din php.ini).";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['filepartial'] = "%s s-a încărcat doar parţial.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['filebadtype'] = "%s nu este de un tip permis.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['matchinfo'] = "Cele mai probabile %s din %s potriviri";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['search'] = "Caută";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchresult'] = "Rezultate";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchinfo'] = "[#%s din %s, relevanţă %s]";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchterms'] = "Cuvinte căutate";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchterms_missing'] = "Trebuie să introduceţi unul sau mai multe cuvinte!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchterms_hint'] = "Introduceţi cel puţin un cuvânt.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['findmode'] = "Listă";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['findmode_hint'] = "Selectaţi ce entităţi trebuie listate ca rezultat.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmode'] = "Mod de căutare";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmode_hint'] = "Alegeţi modul de căutare.<br/>\nConsultaţi documentaţia online pentru mai multe informaţii despre căutările fulltext.<br/>\nMetacaracterele SQL % şi _ pot fi folosite în moduri de căutare de tip 'asemenea'.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchparts'] = "Secţiuni căutate";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchparts_unchecked'] = "Trebuie să bifaţi una sau mai multe secţiuni pentru căutare!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchparts_hint'] = "Alegeţi cel puţin o secţiune pentru căutare.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchcats'] = "Categorii căutate";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchcats_unchecked'] = "Trebuie să bifaţi cel puţin o categorie!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchcats_hint'] = "Alegeţi una sau mai multe categorii pentru căutare.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nomatches'] = "Căutarea a avut zero rezultate.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['postcount'] = "Postări: %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['fromloc'] = "De la : %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['viewprofile'] = "Vezi profil";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['warnsearchflood'] = "Aşteptaţi %s secunde înainte de a face o nouă căutare.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['warnpostflood'] = "Aşteptaţi %s secunde înainte de a face o nouă postare.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['continue'] = "Continuă";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messagetitle']['info'] = "Informaţii";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messagetitle']['warning'] = "Avertisment";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messagetitle']['error'] = "Eroare";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmodes']['natural'] = "Integrală naturală";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmodes']['boolean'] = "Integrală booleană";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmodes']['like'] = "Asemenea";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmodes']['binary'] = "Asemenea binar";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['findmodes']['messages'] = "Toate mesajele relevante";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['findmodes']['topics'] = "Prima potrivire în topicele relevante";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['ticket'] = "Topic";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['tickets'] = "Topice";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['newticket'] = "Nou topic";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['createticket'] = "Creează topic";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['cutticket'] = "Taie topic";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['client'] = "Membru";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['supporter'] = "Moderator";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['owner'] = "Creator";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['notickets'] = "Nu există topice.";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['status-0'] = "Important";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['status-1'] = "Normal";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['deleteTicketConfirm'] = "Chiar doriţi să ştergeţi acest topic cu toate mesajele sale?";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['client_hint'] = "Alegeţi membrul în numele căruia doriţi să creaţi acest tichet, altfel lăsaţi liber.";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['subject_hint'] = "Introduceţi un scurt text ce descrie subiectul acestui topic.";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['message_hint']['create'] = "Introduceţi o descriere detaliată.";
 
?>
