<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/ro/tl_module.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Romanian translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Ionuţ Purcaru (purcaruionut) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['helpdesk_text']['0'] = "Text de index";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_text']['1'] = "Introduceţi un text ce va fi afişat sub headline pe pagina de index. Se poate folosi cod HTML.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_categories']['0'] = "Categorii";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_categories']['1'] = "Selectaţi una sau mai multe categorii ce vor fi afişate în acest bloc.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_links']['0'] = "Funcţii la index";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_links']['1'] = "Arată butoanele cu funcţii pe pagina de index.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_hideempty']['0'] = "Ascunde modul";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_hideempty']['1'] = "Ascunde modul când niciuna dintre categoriile selectate nu este afişată.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode']['0'] = "Afişează link la profil";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode']['1'] = "Selectaţi când şi pentru cine apar link-uri la profil";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode_options']['0'] = "Niciodata";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode_options']['1'] = "La categoria moderatori/asistenţi";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode_options']['2'] = "La categoria membri/clienţi";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode_options']['3'] = "La toată lumea";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profpage']['0'] = "Nume de pagină la profil";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profpage']['1'] = "Nume pagină/url pentru profilul de membru, fără parametrul de membru ID.<br/>\nExemplu: <em>http://www.example.com/memberlist.html</em>";
 
?>
