<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/ro/tl_member.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Romanian translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Ionuţ Purcaru (purcaruionut) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_member']['helpdesk_timezone']['0'] = "Fus orar";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_timezone']['1'] = "Alegeţi un fus orar.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_role']['0'] = "Rol";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_role']['1'] = "Introduceţi rolul ce va fi afişat în postările de forum/asistenţă.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_showrealname']['0'] = "Numele real";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_showrealname']['1'] = "Numele real va fi afişat în postările de forum/asistenţă.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_showlocation']['0'] = "Arată-mi locaţia";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_showlocation']['1'] = "Locaţia (Oraş, Ţară) va fi afişată în postările de forum/asistenţă.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_signature']['0'] = "Semnătură";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_signature']['1'] = "Introduceţi o semnătură. Se poate folosi BBCode pentru formatare.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_subscriptions']['0'] = "Subscrieri";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_subscriptions']['1'] = "Selectaţi la ce doriţi să primiţi notificare prin email.";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_legend'] = "Forum/asistenţă";
$GLOBALS['TL_LANG']['tl_member']['helpdeskDetails'] = "Forum/asistenţă";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_notifymytickets'] = "Topicele şi tichetele mele";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_notifymyreplies'] = "Tichete şi topice la care am contribuit";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_allincategory'] = "Toate în %s";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_noyes']['0'] = "Nu";
$GLOBALS['TL_LANG']['tl_member']['helpdesk_noyes']['1'] = "Da";
 
?>
