<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/ro/tl_user.php 
 * 
 * Contao extension: helpdesk 1.3.0 stable 
 * Romanian translation file 
 * 
 * Copyright : (c) 2007-2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Ionuţ Purcaru (purcaruionut) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_user']['helpdesk_timezone']['0'] = "Fus orar";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_timezone']['1'] = "Selectaţi fusul orar al dv.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_role']['0'] = "Rol";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_role']['1'] = "Introduceţi rolul ce va fi afişat în posturile de forum/helpdesk.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_location']['0'] = "Locaţie";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_location']['1'] = "Locaţia (oraş, ţară) ce va apărea în postări.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_showrealname']['0'] = "Arată numele real";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_showrealname']['1'] = "Afişează numele real cu postările din forum/asistenţă.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_showlocation']['0'] = "Arată locaţia";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_showlocation']['1'] = "Afişează locaţia (oraş, ţară) cu postările din forum/asistenţă.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_signature']['0'] = "Semnătură";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_signature']['1'] = "Introduceţi o semnătură pentru postările din forum/asistenţă. Se poate folosi BBCode pentru formatare.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_subscriptions']['0'] = "Subscrieri";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_subscriptions']['1'] = "Selectaţi pentru ce doriţi să fiţi notificat pe email.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_legend'] = "Forum/asistenţă";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_notifymytickets'] = "Tichetele şi topicele personale";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_notifymyreplies'] = "Tichetele şi topicele la care contribui";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_allincategory'] = "Tot în %s";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_noyes']['0'] = "Nu";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_noyes']['1'] = "Da";
 
?>
