<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/pl/explain.php 
 * 
 * TYPOlight extension: helpdesk 0.9.0 stable 
 * Polish translation file 
 * 
 * Copyright : (c) 2007, 2008 by Acenes 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Marcin Lachowski (qrczak), http://www.typolight.pl 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['0']['0'] = "Wsparcie indywidualne";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['0']['1'] = "Wsparcie dla zgłoszeń indywidualnych: Zgłoszenia widoczne są tylko dla autora zgłoszenia na stronie serwisu. Można użyć tego rodzaju kategorii np. dla formalnych zgłoszeń indywidualnych. W tym przypadku nie ma potrzeby tworzenia osobnych kategorii dla każdego klienta.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['1']['0'] = "Wsparcie grupowe";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['1']['1'] = "Wsparcie dla zgłoszeń grupowych: W tej kategorii klienci widzą inne zgłoszenia i mogą na nie odpowiadać. Użyj te kategorii dla formalnego wsparcia dla firm gdzie wielu członków potrzebuje dostępu do wszystkich zgłoszeń. Można w tym przypadku utworzyć takie kategorie dedykowane dla każdej z firm.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['2']['0'] = "Wsparcie publiczne";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['2']['1'] = "Publiczne wsparcie zgłoszeń: Wszystkie zgłoszenia są widoczne dla każdego na stronie serwisu , nie ważne czy jest zalogowany czy nie i do jakiej grupy należy. Jednakże tylko zarejestrowani klienci mogą otwierać i odpowiadać na zgłoszenia.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['3']['0'] = "Forum niepubliczne";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['3']['1'] = "Forum, które jest widocznie wyłącznie dla zarejestrowanych członków oraz jest ukryte dla pozostałych.";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['4']['0'] = "Forum publiczne";
$GLOBALS['TL_LANG']['XPL']['helpdesk_categories_access']['4']['1'] = "Forum, które może być przeglądane przez każdego, nie ważne czy jest zalogowany czy nie i do jakiej grupy członków należy. Jednakże tylko zarejestrowani członkowie mogą tworzyć nowe lub odpowiadać na istniejące posty.";
 
?>
