<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/pl/helpdesk.php 
 * 
 * TYPOlight extension: helpdesk 0.9.0 stable 
 * Polish translation file 
 * 
 * Copyright : (c) 2007, 2008 by Acenes 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Marcin Lachowski (qrczak), http://www.typolight.pl 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['helpdesk']['useserverdef'] = "Użyj domyślne ustawienia serwera";
$GLOBALS['TL_LANG']['helpdesk']['today'] = "Dzisiaj";
$GLOBALS['TL_LANG']['helpdesk']['yesterday'] = "Wczoraj";
 
?>
