<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/pl/modules.php 
 * 
 * TYPOlight extension: helpdesk 0.9.0 stable 
 * Polish translation file 
 * 
 * Copyright : (c) 2007, 2008 by Acenes 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Marcin Lachowski (qrczak), http://www.typolight.pl 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['helpdesk_comments']['0'] = "Wpisy Forum/Helpdesk";
$GLOBALS['TL_LANG']['CTE']['helpdesk_comments']['1'] = "Ten element zawartości pozwala Twoim odwiedzającym dodawać wpisy do wątków lub zgłoszeń.";
$GLOBALS['TL_LANG']['MOD']['helpdesk'] = "Forum/Helpdesk";
$GLOBALS['TL_LANG']['MOD']['helpdesk_discuss']['0'] = "Dyskusje";
$GLOBALS['TL_LANG']['MOD']['helpdesk_discuss']['1'] = "Uczestnictwo w forum i helpdesk z panelu admina";
$GLOBALS['TL_LANG']['MOD']['helpdesk_structure']['0'] = "Struktura";
$GLOBALS['TL_LANG']['MOD']['helpdesk_structure']['1'] = "Zarządzanie kategoriami aplikacji forum/helpdesk";
$GLOBALS['TL_LANG']['MOD']['helpdesk_settings']['0'] = "Ustawienia";
$GLOBALS['TL_LANG']['MOD']['helpdesk_settings']['1'] = "Zobacz i edytuj ustawienia forum/helpdesk";
$GLOBALS['TL_LANG']['FMD']['helpdesktitle']['0'] = "Tytuł Forum/Helpdesk";
$GLOBALS['TL_LANG']['FMD']['helpdesk']['0'] = "Blok Forum/Helpdesk";
$GLOBALS['TL_LANG']['FMD']['helpdesk']['1'] = "Ten moduł wyświetla na stronie serwisu jedną lub więcej kategorii forum/helpdesk.";
 
?>
