<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/pl/tl_helpdesk_settings.php 
 * 
 * TYPOlight extension: helpdesk 0.9.0 stable 
 * Polish translation file 
 * 
 * Copyright : (c) 2007, 2008 by Acenes 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Marcin Lachowski (qrczak), http://www.typolight.pl 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['title'] = "Główne ustawienia Forum/Helpdesk";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['yes'] = "Tak";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['no'] = "Nie";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['confsync'] = "Czy naprawdę teraz chcesz zsynchronizować (odbudować) wszystkie statystyki i wartości cache?";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['synchronize']['0'] = "Synchronizuj";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['synchronize']['1'] = "Synchronizuj (odbuduj) wszystkie statystyki i wartości cache";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['edit']['0'] = "Edytuj";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['edit']['1'] = "Edytuj ustawienia forum/helpdesk";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['tpage']['0'] = "Wątków/zgłoszeń na stronie";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['tpage']['1'] = "Wpisz ilość wątków/zgłoszeń na jednej stronie. 0 lub puste pole wyłącza paginację.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['mpage']['0'] = "Wiadomości na stronie";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['mpage']['1'] = "Wpisz ilość wiadomości na jednej stronie. 0 lub puste pole wyłącza paginację.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['spage']['0'] = "Wyników wyszukiwania na stronie";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['spage']['1'] = "Wpisz ilość wyników wyszukiwania na jednej stronie. 0 lub puste pole wyłącza paginację.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavsize']['0'] = "Rozmiar paginacji";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavsize']['1'] = "Ilość stron w paginacji. Ustaw 0 by zamiast paginacji wyświetlić \"Strona N z M\".";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feeds']['0'] = "Włącz kanał";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedmax']['0'] = "Ilość wiadomości w kanale";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedmax']['1'] = "Wpisz maksymalną ilość wiadomości w kanale";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedlimit']['0'] = "Limit rozmiaru wiadomości";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedlimit']['1'] = "Wpisz maksymalną ilość znaków na jedną wiadomość";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedlink']['0'] = "Nazwa główna kanału";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedlink']['1'] = "Np. wpisz <em>helpdesk</em> dla kanału o nazwie http://www.example.com/helpdesk&lt;category-number&gt;.xml";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedtitle']['0'] = "Tytuł kanału";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feedtitle']['1'] = "Tytuł będzie wyświetlany np. na zakładce przeglądarki, sugeruje się używać krótkich nazw.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feeddescription']['0'] = "Opis kanału";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['feeddescription']['1'] = "W większosci przeglądarek i kanałów wyświetla się jako podtytuł.";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['logging']['0'] = "Dziennik";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['logging']['1'] = "Zaznacz poziom dziennika. Informacje dziennika będą zapisywane w pliku system/logs/Helpdesk*.log";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['loglevel']['2'] = "Szczegóły";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavoptions']['0'] = "Tekst";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['pagenavoptions']['1'] = "Ikony";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editoptions']['0'] = "Nikt";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editoptions']['1'] = "Tylko zwykli członkowie";
$GLOBALS['TL_LANG']['tl_helpdesk_settings']['editoptions']['2'] = "Wszyscy";
 
?>
