<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/pl/tl_helpdesk_bbcode.php 
 * 
 * TYPOlight extension: helpdesk 0.9.0 stable 
 * Polish translation file 
 * 
 * Copyright : (c) 2007, 2008 by Acenes 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Marcin Lachowski (qrczak), http://www.typolight.pl 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['code'] = "Kod:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['note'] = "Informacja:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['edit'] = "Edytowano:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['quote'] = "Cytat:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['caution'] = "Uwaga:";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['bold'] = "Pogrubienie";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['italics'] = "Kursywa";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['underlined'] = "Podkreślone";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['superscript'] = "Indeks górny";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['subscript'] = "Indeks dolny";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['centered'] = "Wyśrodkowane";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['rightaligned'] = "Do prawej";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['justified'] = "Justowanie";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['list'] = "Lista nieuporządkowana";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['numberedlist'] = "Lista numerowana liczbami dziesiętnymi";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['romanlist'] = "Lista numerowana rzymskimi znakami";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['alphalist'] = "Lista numerowana znakami alfanumerycznymi";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['listitem'] = "Lista pozycji";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['code'] = "Kod";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['php'] = "Kod PHP";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['js'] = "Kod Javascript";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['xml'] = "Kod XML";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['html'] = "Kod HTML";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['css'] = "Kod CSS";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['c++'] = "Kod C++";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['qt'] = "Kod Qt";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['table'] = "Tabela";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['tablerow'] = "Wiersz tabeli";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['tablecell'] = "Komórka tabeli";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['quote'] = "Cytat";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['information'] = "Informacja";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['warning'] = "Ostrzeżenie";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['hyperlink'] = "Odnośnik";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['image'] = "Obrazek";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['preview'] = "Podgląd";
$GLOBALS['TL_LANG']['tl_helpdesk_bbcode']['fnc']['help'] = "Pomoc";
 
?>
