<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/pl/tl_helpdesk_categories.php 
 * 
 * TYPOlight extension: helpdesk 0.9.0 stable 
 * Polish translation file 
 * 
 * Copyright : (c) 2007, 2008 by Acenes 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Marcin Lachowski (qrczak), http://www.typolight.pl 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['header']['0'] = "Nagłówek";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['header']['1'] = "Wprowadź nagłówek aby utworzyć nową grupę kategorii. Jeśli nie chcesz utworzyć nowej grupy kategorii pozostaw to pole puste.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['title']['0'] = "Tytuł";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['title']['1'] = "Tytuł tej kategorii.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['description']['0'] = "Opis";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['description']['1'] = "Opcjonalny opis tej kategorii.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['buttons']['0'] = "Przyciski edytora";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['buttons']['1'] = "Wprowadź, rozdzieloną przecinkami, listę przycisków edytora. Możesz grupować przyciski za pomocą średnika. Oddzielna lista przycisków powstanie po dodaniu ich w nowej linii.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access']['0'] = "Dostęp";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access']['1'] = "Typ kategorii w serwisie.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['replyonly']['0'] = "Tylko odpowiedzi";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['replyonly']['1'] = "Nowe wątki/zgłoszenia mogą być tworzone przez moderatorów/asystentów.<br/>Autoryzowani członkowie/klienci mogą tylko odpowiadać na istniejące wątki.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['published']['0'] = "Publikuj";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['published']['1'] = "Kategoria jest wyświetlana na stronach serwisu dla przypisanych do niej użytkowników.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_clients']['0'] = "Członkowie/Klienci serwisu";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_clients']['1'] = "Członkowie/Klienci serwisu przypisani do tej kategorii.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_supporters']['0'] = "Moderatorzy/Asystenci serwisu";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['fe_supporters']['1'] = "Członkowie serwisu, którzy będą asystentami (helpdesk) lub moderatorami (forum) tej kategorii.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_clients']['0'] = "Członkowie/Klienci admin panelu";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_clients']['1'] = "Użytkownicy admin panelu, którzy będą członkami/klientami tej kategorii.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_supporters']['0'] = "Moderatorzy/Asystenci admin panelu";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['be_supporters']['1'] = "Użytkownicy admin panelu, którzy będą asystentami (helpdesk) lub moderatorami (forum) tej kategorii.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['feed']['0'] = "Włącz kanał RSS";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['feed']['1'] = "Kliknij aby włączyć kanał RSS dla tej kategorii.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch']['0'] = "Włącz załączniki";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch']['1'] = "Włącz używanie załączników.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_dir']['0'] = "Folder załączników";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_dir']['1'] = "Wpisz ścieżkę gdzie pliki załaczników będą przechowywane.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_size']['0'] = "Rozmiar załaczników";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_size']['1'] = "Wpisz całkowity dozwolony rozmiar wszystkich załaczników w jednej wiadomości.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_types']['0'] = "Typy załączników";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['atch_types']['1'] = "Wprowadź, rozdzielając przecinkiem, listę dozwolonych rozszerzeń załączników.<br />Wpisz * by zezwolić na wszystkie rozszerzenia.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify']['0'] = "Włącz powiadamiania";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify']['1'] = "Powiadamiania subskrybentów przez email.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_astext']['0'] = "Wyślij jako tekst";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_astext']['1'] = "Zaznacz by wysłać jako tekst, niezaznaczaj by wysłać jako HTML.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_name']['0'] = "Nazwa nadawcy";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_name']['1'] = "Zostaw puste by użyć tylko adresu email.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_sender']['0'] = "Adres nadawcy";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_sender']['1'] = "Zostaw puste by użyć adresu email administratora.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_fe_url']['0'] = "URL do strony serwisu";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_fe_url']['1'] = "Powinno to być coś takiego: <em>http://www.twojastrona.com/forum</em><br />Zostaw puste by wyłączyć powiadamianie członków serwisu.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_be_url']['0'] = "URL do panelu admina";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_be_url']['1'] = "Powinno to być coś takiego: <em>http://www.twojastrona.com/typolight/main.php?do=helpdesk</em><br />Zostaw puste by wyłączyć powiadamianie użytkowników admin panelu.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newsubj']['0'] = "Tytuł nowego tematu";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newsubj']['1'] = "Możesz używać tagów [[poster]], [[subject]] i [[replytag]].";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newtext']['0'] = "Treść nowego tematu";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_newtext']['1'] = "Możesz używać tagów [[poster]], [[subject]], [[message]] i [[link]].";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_replysubj']['0'] = "Tytuł odpowiedzi";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_replysubj']['1'] = "Możesz używać tagów [[poster]], [[subject]] i [[replytag]].";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_replytext']['0'] = "Treść odpowiedzi";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_replytext']['1'] = "Możesz używać tagów [[poster]], [[subject]], [[message]] i [[link]].";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import']['0'] = "Włącz import wpisów przez email";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import']['1'] = "Włącz import wpisów przez email.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_server']['0'] = "Serwer poczty";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_server']['1'] = "Wpisz nazwe serwera IMAP4/POP3.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_port']['0'] = "Numer portu";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_port']['1'] = "Wpisz numer portu lub zostaw puste pole by użyć ustawień domyślnych.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_type']['0'] = "Typ skrzynki";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_type']['1'] = "Wybierz typ skrzynki pocztowej.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tls']['0'] = "Transport Layer Security (TLS)";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tls']['1'] = "Wybierz tryb TLS/SSL.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_username']['0'] = "Nazwa użytkownika";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_username']['1'] = "Wpisz użytkownika konta email.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_password']['0'] = "Hasło";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_password']['1'] = "Wpisz hasło dla konta email.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_email']['0'] = "Do: email";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_email']['1'] = "Wpisz w pole <em>do</em> adres email lub zostaw puste aby przetworzyć całą pocztę niezależnie od nadawcy.<br />(Adresy nadawców powinny odpowiadać adresom osób powiadamianych, emaile od osób nie będących w bazie osób powiadamianych będą ignorowane.)";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['0'] = "Wsparcie indywidualne";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['1'] = "Wsparcie grupowe";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['2'] = "Wsparcie publiczne";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['3'] = "Forum niepubliczne";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['access_options']['4'] = "Forum publiczne";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_types']['0'] = "POP3";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_types']['1'] = "IMAP4";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['0'] = "Nie używaj TLS nawet jeśli jest obsługiwane.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['1'] = "Użyj TLS jeśli jest obsługiwane, potwierdzony certyfikat.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['2'] = "Użyj TLS jeśli jest obsługiwane, nie potwierdzony certyfikat.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['3'] = "Wymagany TLS, potwierdzony certyfikat.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['4'] = "Wymagany TLS, nie potwierdzony certyfikat.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['5'] = "Użyj SSL, potwierdzony certyfikat.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['import_tlsopts']['6'] = "Użyj SSL, nie potwierdzony certyfikat.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['new']['0'] = "Nowa kategoria";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['new']['1'] = "Utwórz nową kategorię.";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['edit']['0'] = "Edytuj";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['edit']['1'] = "Edytuj ustawienia kategorii %s";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['copy']['0'] = "Duplikuj";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['copy']['1'] = "Duplikuj tę kategorię";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['delete']['0'] = "Skasuj";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['delete']['1'] = "Skasuj kategorie %s oraz wszystkie jej zgłoszenia";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_notify']['0'] = "Włącz powiadomienia";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_notify']['1'] = "Włącz powiadomienia dla kategorii %s";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_notify']['0'] = "Wyłącz powiadomienia";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_notify']['1'] = "Wyłącz powiadomienia dla kategorii %s";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_import']['0'] = "Włącz import wpisów przez email";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['ena_import']['1'] = "Włącz import wpisów przez email dla kategorii %s";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_import']['0'] = "Wyłącz import wpisów przez email";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['dis_import']['1'] = "Wyłącz import wpisów przez email dla kategorii %s";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['publish']['0'] = "Publikuj";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['publish']['1'] = "Publikuj kategorię %s na stronach twojego serwisu";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['unpublish']['0'] = "Nie publikuj";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['unpublish']['1'] = "Nie publikuj kategorii %s na stronach twojego serwisu";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderup']['0'] = "Przesuń w górę";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderup']['1'] = "Przesuń kategorię jedna pozycję w górę";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderdown']['0'] = "Przesuń w dół";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['orderdown']['1'] = "Przesuń kategorię jedna pozycję w dół";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['tickets'] = "Zgłoszenia";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['replies'] = "Odpowiedzi";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_subject']['new'] = "Nowy wpis: [[subject]] [[replytag]]";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_subject']['reply'] = "Odpowiedź do wpisu: [[subject]] [[replytag]]";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_text']['new'] = "[[poster]] utworzył nowy wątek w kategorii, do której jesteś zapisany:<br/>\n<hr/>\n[[message]]\n<hr/>\nWątek jest dostępny pod tym adresem: [[link]]<br/>\n---<br/>\nSystem pocztowy TYPOlight Forum/Helpdesk<br/>\n(Pozostaw reply tag w temacie kiedy odpowiadasz poprzez email)<br/>";
$GLOBALS['TL_LANG']['tl_helpdesk_categories']['notify_text']['reply'] = "[[poster]] odpowiedział w wątku, do którego jesteś zapisany:<br/>\n<hr/>\n[[message]]\n<hr/>\nOdpowiedź jest dostępna pod tym adresem: [[link]]<br/>\n---<br/>\nSystem pocztowy TYPOlight Forum/Helpdesk<br/>\n(Pozostaw reply tag w temacie kiedy odpowiadasz poprzez email)<br/>";
$GLOBALS['TL_LANG']['tl_helpdesk_fcategories']['tickets'] = "Wątki";
 
?>
