<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/pl/tl_helpdesk_frontend.php 
 * 
 * TYPOlight extension: helpdesk 0.9.0 stable 
 * Polish translation file 
 * 
 * Copyright : (c) 2007, 2008 by Acenes 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Marcin Lachowski (qrczak), http://www.typolight.pl 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_helpdesk_support']['mine'] = "Moje";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['recent'] = "Nowe";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['views'] = "Odsłon";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unanswered'] = "Bez odpowiedzi";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unread'] = "Nieczytane";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['category'] = "Kategoria";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['index'] = "Lista kategorii";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['ticket'] = "Zgłoszenie";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['tickets'] = "Zgłoszenia";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['newticket'] = "Nowe zgłoszenie";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['createticket'] = "Utwórz zgłoszenie";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nopaste'] = "Anuluj wytnij/wklej";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['cutmessage'] = "Wytnij wiadomość";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['cutticket'] = "Wytnij zgłoszenie";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['paste'] = "Wklej";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['postreply'] = "Wyślij odpowiedź";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['updatemessage'] = "Uaktualnij wiadomość";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message'] = "Wiadomość";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['replies'] = "Odpowiedzi";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['latestpost'] = "Ostatni wpis";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['postedby'] = "przez %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['lastedit'] = "[Ostatnio edytowany przez %s, %s]";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['subject'] = "Temat";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['client'] = "Klient";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['supporter'] = "Asystent";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['owner'] = "Właściciel";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['creator'] = "Autor";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['poster'] = "Napisane przez";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nocategories'] = "Nie znaleziono żadnych kategorii.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['notickets'] = "Nie znaleziono żadnych zgłoszeń.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nomessages'] = "Nie znaleziono żadnych wiadomości.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status'] = "Status";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status-0'] = "Unanswered";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status-1'] = "Odpowiedziane";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['status-2'] = "Zamknięte";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['reply'] = "Odpowiedz";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['close'] = "Zamknij";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['open'] = "Otwórz";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['edit'] = "Edytuj";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['quote'] = "Cytuj";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['delete'] = "Skasuj";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['publish'] = "Publikuj";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unpublish'] = "Nie publikuj";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['pinup'] = "Przypnij";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['unpin'] = "Odepnij";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['markcatread'] = "Zaznacz kategorię jako przeczytaną";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['markallread'] = "Wszystko przeczytane";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['feed'] = "Kanał RSS";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['globfeed'] = "Ogólny kanał RSS";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['wrote'] = "%s napisał/a:";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['deleteMessageConfirm'] = "Czy naprawdę chcesz skasować tę wiadomość?";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['deleteTicketConfirm'] = "Czy naprawdę chcesz skasować to zgłoszenie z wszystkimi jego wiadomościami?";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['client_hint'] = "Wybierz klienta, w imieniu którego tworzysz to zgłoszenie lub zostaw to pole puste.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['subject_missing'] = "Musisz wpisać tytuł!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['subject_hint'] = "Wpisz krótki tekst opisujący główną przyczynę zgłoszenia.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_missing']['create'] = "Musisz wprowadzić szczegółowy opis!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_missing']['reply'] = "Musisz wprowadzić tekst wiadomości!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_missing']['edit'] = "Musisz wprowadzić tekst wiadomości!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_hint']['create'] = "Wpisz szczegółowy opis oraz podaj wszystkie informacje dotyczące problemu.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_hint']['reply'] = "Wpisz twój tekst odpowiedzi.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['message_hint']['edit'] = "Edytuj tekst widomości.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['published'] = "Opublikuj";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['published_hint'] = "Wiadomość będzie wyświetlona na stronach serwisu uprawnionym osobom.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messages_reverse'] = "Poprzednie wiadomości w odwrotnej kolejności:";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['firstpage'] = "Pierwsza strona";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['prevpage'] = "Poprzednia strona";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nextpage'] = "Następna strona";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['lastpage'] = "Ostatnia strona";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['page_n_of_m'] = "Strona %s z %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['gotopage'] = "Idź do strony %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['attachments'] = "Załączniki";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['atch_size'] = "Maksymalny rozmiar wszystkich załączników:";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['atch_types'] = "Dozwolone typy załączników:";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['atchtobig'] = "Załączniki przewyższają maksymalny dozwolony rozmiar.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['filetobig'] = "%s przewyższa maksymalny rozmiar pliku, który mozna przesłać na ten serwer (sprawdź ustawienia php.ini).";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['filepartial'] = "%s got only partially uploaded.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['filebadtype'] = "%s nie jest dozwolonym typem pliku.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['matchinfo'] = "Najlepsze %s ze wszystkich %s trafień";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['search'] = "Szukaj";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchresult'] = "Wyniki";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchinfo'] = "[#%s by %s, trafność %s]";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchterms'] = "Wpisz zapytanie";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchterms_missing'] = "Musisz wpisać jedną lub więcej fraz do wyszukiwania!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchterms_hint'] = "Wpisz jedną lub więcej fraz do wyszukiwania!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['findmode'] = "Lista";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmode'] = "Tryb wyszukiwania";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchmode_hint'] = "Wybierz tryb wyszukiwania.<br/>\nConsult <a href=\"http://dev.mysql.com/doc/refman/6.0/en/fulltext-search.html\">MySQL documentation</a> for more information on fulltext search.<br/>\nSQL wildcards % and _ can be used in 'like' search modes.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchparts'] = "Wyszukiwane części";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchparts_unchecked'] = "Musisz zaznaczyć jedną lub więcej części do wyszukiwania!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchparts_hint'] = "Zaznacz jedną lub więcej części do wyszukiwania!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchcats'] = "Wyszukiwane kategorie";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchcats_unchecked'] = "Musisz zaznaczyć przynajmniej jedna kategorię!";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['searchcats_hint'] = "Zaznacz jedną lub więcej kategorii do wyszukiwania.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['nomatches'] = "Wyszukiwanie nie zwróciło żadnych wyników.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['postcount'] = "Postów: %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['fromloc'] = "Z: %s";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['viewprofile'] = "Zobacz profil";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['warnsearchflood'] = "Poczekaj %s sekund przed rozpoczęciem kolejnego wyszukiwania.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['warnpostflood'] = "Poczekaj %s sekund przed opublikowaniem kolejnego postu.";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['continue'] = "Kontynuuj";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messagetitle']['info'] = "Informacja";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messagetitle']['warning'] = "Ostrzeżenie";
$GLOBALS['TL_LANG']['tl_helpdesk_support']['messagetitle']['error'] = "Błąd";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['ticket'] = "Wątek";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['tickets'] = "Wątki";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['newticket'] = "Nowy wątek";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['createticket'] = "Utwórz wątek";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['cutticket'] = "Wytnij wątek";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['client'] = "Użytkownik";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['supporter'] = "Moderator";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['owner'] = "Autor";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['notickets'] = "Nie znaleziono żadnych wątków.";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['status-0'] = "Przypięte";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['status-1'] = "Normalne";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['deleteTicketConfirm'] = "Czy naprawdę chcesz skasować ten wątek z wszystkimi jego postami?";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['client_hint'] = "Wybierz członka, w imieniu którego tworzysz tę wiadomość lub zostaw to pole puste.";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['subject_hint'] = "Wpisz krótki tekst opisujący temat wątku.";
$GLOBALS['TL_LANG']['tl_helpdesk_forum']['message_hint']['create'] = "Wpisz szczegółowy opis.";
 
?>
