<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/pl/tl_module.php 
 * 
 * TYPOlight extension: helpdesk 0.9.0 stable 
 * Polish translation file 
 * 
 * Copyright : (c) 2007, 2008 by Acenes 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Marcin Lachowski (qrczak), http://www.typolight.pl 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['helpdesk_text']['0'] = "Tekst";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_text']['1'] = "Wprowadzony tekst będzie widoczny pod nagłówkiem. Możesz używać tagów HTML.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_categories']['0'] = "Kategorie";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_categories']['1'] = "Zaznacz jedną lub więcej kategorii do wyświetlenia przez ten moduł.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_hideempty']['0'] = "Ukryj jeśli pusty";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_hideempty']['1'] = "Ukryj moduł kiedy, żadna kategoria nie zostanie znaleziona.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode']['0'] = "Wyświetl odnośnik do profilu";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode']['1'] = "Zaznacz kiedy i dla kogo odnośniki profilów będą pokazane.";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode_options']['0'] = "Nigdy";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profmode_options']['3'] = "Do wszystkich";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profpage']['0'] = "Nazwa strony profilu";
$GLOBALS['TL_LANG']['tl_module']['helpdesk_profpage']['1'] = "Nazwa/url strony profilu członka tej instalacji TYPOlight, bez parametru ID członka.<br/>\nPrzykład: <em>http://www.strona.pl/lista_uzytkownikow.html</em>";
 
?>
