<?php
/**
 * TL_ROOT/system/modules/helpdesk/languages/pl/tl_user.php 
 * 
 * TYPOlight extension: helpdesk 0.9.0 stable 
 * Polish translation file 
 * 
 * Copyright : (c) 2007, 2008 by Acenes 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Marcin Lachowski (qrczak), http://www.typolight.pl 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_user']['helpdesk_timezone']['0'] = "Twoja strefa czasowa";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_timezone']['1'] = "Zaznacz Twoją strefę czasową.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_location']['0'] = "Lokalizacja";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_location']['1'] = "Wyświetl lokalizację w forum/helpdesk (miasto, kraj)";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_showrealname']['0'] = "Pokaż swoje imię";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_showrealname']['1'] = "Wyświetl w postach forum/helpdesk swoje prawdziwe imię.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_showlocation']['0'] = "Pokaż lokalizację";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_showlocation']['1'] = "Wyświetl lokalizację (miasto, kraj) w forum/helpdesk";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_signature']['0'] = "Podpis";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_signature']['1'] = "Wpisz podpis dla forum/helpdesk. Użyj BBCode do formatowania.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_subscriptions']['0'] = "Subskrypcje Helpdesk";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_subscriptions']['1'] = "Zaznacz kategorie, o których chcesz być informowany przez email.";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_notifymytickets'] = "Moje zgłoszenia i wątki";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_notifymyreplies'] = "Zgłoszenia i wątki, w których uczestniczę";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_allincategory'] = "Wszystko z %s";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_noyes']['0'] = "Nie";
$GLOBALS['TL_LANG']['tl_user']['helpdesk_noyes']['1'] = "Tak";
 
?>
